### ISSUE TITLE
[linux] - small change to the Wiki instructions when cloning the project

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#1007]
I know OpenXRay is all-together the xray-16, the xray-15, and the xray repositories. 
But I propose that in the WIKI instructions, on how to compile in Linux, add this little change:

`git clone https://github.com/OpenXRay/xray-16.git OpenXRay --recurse-submodules`

so all the code goes to the folder `OpenXRay` instead of folder `xray-16`

and so make other pertinent changes in the instructions to reflect that like:

`cd OpenXRay && mkdir bin && cd bin`

**Comment by Xottab-DUTY** [comment]
Well, we often use `xray-16` naming in chats, when helping people with git commands, etc. and it's also beneficial for better differentiation from `xray-15` and `xray`, because there are people that interested in these repositories.

So, in short, it's better to keep `xray-16` in the instructions.
