### ISSUE TITLE
main menu isn't handling the pressed keys correctly

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#1008]
**Describe the bug**
in Main Menu if you press once Intro over "New Game", you can't select the difficulty because there isn't an interruption of the pressed key when the menu changes, so you "auto select" the first default option in the next menu (the skill menu), and so the game starts.

**To Reproduce**
start the engine.
press enter
the game will start without a chance to select the skill!

**Expected behavior**
whenever the menu changes all keys should still wait a "press out" in case they're being "pressed in" before being able to be "pressed in" again.

**Screenshots**
nope

**BugTrap error report**
none

**Desktop (please complete the following information):**
 - OS: [Ubuntu 21.10]
 - OpenXRay build version [615d98bcf8729cbb42a85c19d7e745e39edcde23]

**Additional context**
none

**Comment by Xottab-DUTY** [comment]
Thanks!
