### ISSUE TITLE
Ошибка при входе в Лиманск в December 2021 RC1 (Clear Sky)

### ISSUE THREAD

**Issue by steelpuxnastik** [Swartz27/xray-16#1010]
При переходе в Лиманск или загрузке любого созханения в Лиманске с December 2021 RC1 вылетает в Windows с ошибкой

```
ODE INTERNAL ERROR 2
---------------------------
no first body, can't set axis rel=1 (C:\projects\xray-16\Externals\ode\ode\src\joint.cpp:2506)
---------------------------
ОК   
```

Можно было бы пользоваться December 2020 Preview если бы ее какая-то тотальная нестабильность (по крайней мере у меня, из-за чего и попробовал December 2021 RC1 и до этого момента был доволен, 34 часа без единого вылета) не дает играть. В том же Лиманске, когда я вернул December 2020 Preview игра вылетает, в лучшем случае, через минуту если ничего не делать или если начать что-то перемещать в инвентаре, допустим при попытке поменять артефакты местами, которые перестали отображаться закрепленными в инвентаре. Попробую все таки хотя бы выбраться из Лиманска, чтоб понять, появляется ли ошибка дальше где-то еще дальше?

Система Windows 10 21H2 x64
OpenXRay Rx64 build 8339, Dec  6 2021

Больше добавить, в принципе нечего не могу, прикрепил архив с репортом

[OpenXRay_error_report_220427-170225.zip](https://github.com/OpenXRay/xray-16/files/8572751/OpenXRay_error_report_220427-170225.zip)

**Comment by Xottab-DUTY** [comment]
Долго не мог понять в чём дело...
Баг был исправлен сразу в декабре, через короткое время после выхода December 2021 RC1 в коммите 2ad78a4c0f8cfab08adcc18421ddb886156598a3, а эта issue была открыта в апреле, я уже и забыл, что оно исправлено...

В следующий релиз попадёт это исправление. А, пока, всё-таки, лучше на December 2020 Preview играть.

**Comment by LATEXPHONE** [comment]
Та же ошибка с вылетом при переходе в Лиманск (ЧН):
no first body, can't set axis rel=1 (C:\projects\xray-16\Externals\ode\ode\src\joint.cpp:2506)

Перепробованы все версии (2021, 2020, Nightly), переустновки, проверены форумы — решения нет, а проблема до сих пор всплывает.

Система Windows 10, запуск на macOS Sequoia 15.1 и через Wine, и через CrossOver 
 
[logandsave.zip](https://github.com/user-attachments/files/17927298/logandsave.zip)
