### ISSUE TITLE
Changed graphics settings can't be reverted automatically

### ISSUE THREAD

**Issue by OPNA2608** [Swartz27/xray-16#1024]
**Describe the bug**
When you change some graphics settings (for example, resolution), the game will do some short reloading with the new settings and show a prompt with a timeout asking if you would like to keep these settings or revert them. Choosing to revert (or letting the prompt time out) will cause another reload, but it doesn't actually revert the settings.

**To Reproduce**
1. Go to 'Options'
2. Change the resolution
3. Hit 'Apply'
4. On the prompt, hit 'No' or let the timer run out
5. Observe that the settings haven't been reverted

**Expected behavior**
The game should do what it says it'll do: Revert the settings.

**Screenshots**

https://user-images.githubusercontent.com/23431373/167248418-6a912bf9-f493-4779-901a-4dda71f2c999.mp4

(The game window size & graphical artifacts after resizing is not a problem, just a curiosity of the recording program, but it helps with visualizing that the resolution doesn't in fact get reverted)

**BugTrap error report**
n/a

**Desktop (please complete the following information):**
 - OS: NixOS 21.11 (Linux)
 - OpenXRay build version: commit 78dd002c8c29c5eede7ff18eb5949e6c08576759

**Additional context**
n/a

**Comment by Xottab-DUTY** [comment]
If this issue is only about the resolution settings, then it should have been fixed with #1383.
@OPNA2608, can you check it?

**Comment by Xottab-DUTY** [comment]
So, I believe this issue is related to resolution only, other options should be reversible as usual.
Please, reopen if I'm incorrect.
