### ISSUE TITLE
Can't compile on Fedora 36

### ISSUE THREAD

**Issue by evgnor86** [Swartz27/xray-16#1045]
Fedora 36

xray-16/Externals/cximage/ximajpg.h:33:11: fatal eror: jpeg/jpeglib.h: File not found

I'm try to remove jpeglib-turbo and manualy install libjpeg9, but this error always show

Any ideas?

**Comment by eagleivg** [comment]
Try instal devel - version of this packet

**Comment by Xottab-DUTY** [comment]
Yes, you need dev/devel version of this  packet :)

**Comment by Xottab-DUTY** [comment]
To fix the issue, developer version of libjpeg-turbo packet is needed. Also, after 2d3b3e4fbf301d5fce6ff0423c676eae867c03d3, even if it's missing it will compile anyway now, so this issue can be closed.
