### ISSUE TITLE
[Linux] Flatpak support or other distro independent solution

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [Swartz27/xray-16#1050]
**Is your feature request related to a problem? Please describe.**
Currently project for Linux compiles only binary files for Ubuntu, while the guide have instructions for other major distros like Fedora or Arch, while Ubuntu users can simply download binary from github actions or other site listed, Arch users can use AUR to install engine users of other distros like Fedora or OpenSUSE have to compile it manually and this is not good solution for less experienced users also sometimes it may be problematic as my issue (#1044) confirms it.

**Describe the solution you'd like**
Creating distro independent package like snap, flatpak or appimage can help both promoting the project,  installing and maintaining for end user since then can simply run update command (snap or flatpak) or download latest appimage. Other source ports like various doom ports (gzdoom, chocolate doom), OpenJK or Augustus (Caesar 3 source port) uses this solution.

There's a documentation on how we can add OpenXRay to Flatpak: [docs.flathub.org/docs/for-app-authors/submission](https://docs.flathub.org/docs/for-app-authors/submission/)

**Describe alternatives you've considered**
Alternative would be adding at least autobuilding rpm files since arch have AUR and Gentoo is mainly used by power users so they can maitain it themself while Fedora or OpenSUSE users are not as fluent in linux or in this case programming to fix if something happen during compiling. I am not a programmer and have never used Github actions but i've found this for building rpm's:

https://github.com/marketplace/actions/rpm-build

**Additional context**
Sources:

My issue: 
https://github.com/OpenXRay/xray-16/issues/1044

Source port using distro independent packaging:
https://snapcraft.io/openjk
https://flathub.org/apps/details/org.zdoom.GZDoom
https://flathub.org/apps/details/org.dhewm3.Dhewm3
https://github.com/Keriew/augustus/releases/tag/v3.1.0

**Comment by eagleivg** [comment]
As far as I know, none of the developers use RPM or Flatpack. Therefore, the implementation may be delayed. If you want to speed up this process, you can provide a PR that solves this problem.

**Comment by Xottab-DUTY** [comment]
To reduce a number of issues, let's track this task in #1403.
