### ISSUE TITLE
Видимый полигонаж на персонажах - дх11 ?

### ISSUE THREAD

**Issue by JIuBeP** [Swartz27/xray-16#1068]
**Describe the bug**
Не знаю что произошло, возможно проблема во мне, но похоже что я стал видеть гребаные полигоны...

**To Reproduce**
1. Go to '.'
2. Go to '..'
3. Go to '...'

**Expected behavior**

**Screenshots**
![S T A L K E R   Call of Pripyat Screenshot 2022 08 15 - 18 51 42 91](https://user-images.githubusercontent.com/40402596/184670162-52ba60e1-9e4b-448a-898e-31a865a5eeb8.png)

**Desktop (please complete the following information):**
 - OS:  Windows 7 x64 
 - OpenXRay build version last dev
 - Nvidia gtx 900 series

**Additional context**

**Comment by Xottab-DUTY** [comment]
Консольные команды `rs_wireframe` и `r4_wireframe` выключены?

Если да, то есть какой-то баг, который к этому приводит, вроде, даже в оригинале.. Но я не помню какой..

**Comment by JIuBeP** [comment]
r4 wireframe была почему то включена, похоже перезапуск и отключение помогли. Это как то относится к тесселяции?

**Comment by JIuBeP** [comment]
Немного не в тему, но вспомнил вот...
дверь баржи Ноя после выстрела в нее:
![S T A L K E R   Call of Pripyat Screenshot 2022 08 15 - 18 44 11 99](https://user-images.githubusercontent.com/40402596/184675854-397f554f-db4b-44f8-9a08-aa240b04596e.png)
с другими объектами вроде таких проблем не замечал. В ванили было такое?

**Comment by Xottab-DUTY** [comment]
> r4 wireframe была почему то включена, похоже перезапуск и отключение помогли. Это как то относится к тесселяции?

К тесселяции не относится. Ну, значит проблема решена.

> Немного не в тему, но вспомнил вот... дверь баржи Ноя после выстрела в нее: ![S T A L K E R Call of Pripyat Screenshot 2022 08 15 - 18 44 11 99](https://user-images.githubusercontent.com/40402596/184675854-397f554f-db4b-44f8-9a08-aa240b04596e.png) с другими объектами вроде таких проблем не замечал. В ванили было такое?

Не хватает фикса шейдеров из OpenXRay Plus. Вообще, просто советую удалить user.ltx и настроить игру из настроек игры, особо не трогая консоль вручную :)))

**Comment by JIuBeP** [comment]
Ок, благодарю!
