### ISSUE TITLE
Великие и ужасные саншафты губят перфоменс по утрам

### ISSUE THREAD

**Issue by JIuBeP** [Swartz27/xray-16#1069]
**Describe the bug**
Утренние лучи солнца сильно влияют на производительность, как в ЧН или даже хуже? Даже при дожде с намоканием у меня кадров намного больше ( с ограничением), карта почти отдыхала. На среднем солнце с лучами (почти ртх?) в 40-50 и порой карту загружает до 100. Может все таки что-то не так?

**To Reproduce**
1. Go to '6:00' on zone with good weather
2. Go to '..'
3. Go to '...'

**Expected behavior**

**Screenshots**

![S T A L K E R   Call of Pripyat Screenshot 2022 08 15 - 19 13 13 30](https://user-images.githubusercontent.com/40402596/184678221-db918337-3833-4e80-af6b-9b818d5e4888.png)
![S T A L K E R   Call of Pripyat Screenshot 2022 08 15 - 19 15 44 99](https://user-images.githubusercontent.com/40402596/184678252-32515372-9dfa-4cc6-b69b-9d535e83d6a0.png) 

**Desktop (please complete the following information):**
 - OS: [ Windows 7
 - OpenXRay build version last dev CI #1996 [xrRender: cached inverted view transform (#1066)](https://github.com/OpenXRay/xray-16/actions/runs/2860339614)

**Additional context**

**Comment by Xottab-DUTY** [comment]
Многие жаловались, что в ЗП вообще саншафтов нет. На моей памяти, они были какие-то очень слабенькие...

В общем, были возвращены саншафты как в ЧН, вот и...

**Comment by Xottab-DUTY** [comment]
Саншафты на каком уровне качества стоят?

**Comment by JIuBeP** [comment]
На среднем, как и солнце. Кстати согласен, что они и в оригинале были, но ощутимо полегче.

**Comment by Limemani** [comment]
Если что мощность так сказать саншафтов можно сделать поменьше через консоль отладки на Ё
