### ISSUE TITLE
Перевернутое изображение в Clear Sky

### ISSUE THREAD

**Issue by Kron4ek** [Swartz27/xray-16#1073]
Начиная с коммита https://github.com/OpenXRay/xray-16/commit/4da8cdbd814301c65bf3f8673d1d4cd3d5ceb6f2 в Clear Sky изображение перевернутое, на предыдущем коммите 3924a7a909434a17e9d710cae1eaadac2ccddd47 проблемы нет. В Call of Pripyat проблема не проявляется.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/13851877/184826699-bfe33d30-83c9-433e-8743-9bf02d51e5b7.jpg)

**Desktop (please complete the following information):**
 - OS: Linux
 - OpenXRay build version aa756a63a607d947b9b0ecd6e1a3bde39afd00b0

**Comment by Xottab-DUTY** [comment]
@vTurbine упс 🙃

**Comment by Xottab-DUTY** [comment]
@Kron4ek, а ты шейдер новый ставил? Который обновился как раз в 4da8cdbd814301c65bf3f8673d1d4cd3d5ceb6f2...

Я только что сейчас проверил. Со старым шейдером - перевёрнуто. С новым - исправно.

**Comment by Kron4ek** [comment]
@Xottab-DUTY Не знал, что нужно шейдер обновить. Но действительно, с новым шейдером изображение не перевернутое, спасибо за подсказку. Стоит тогда, наверное, gamedata для Clear Sky на Wiki обновить, чтобы там сразу из коробки новый шейдер был.

**Comment by Xottab-DUTY** [comment]
Обновил gamedata для ЧН и инструкцию.

**Comment by Kron4ek** [comment]
@Xottab-DUTY Спасибо.
