### ISSUE TITLE
Asahi Linux M1 Apple Silicon 

### ISSUE THREAD

**Issue by DoktorCranium** [Swartz27/xray-16#1080]
Hello - no issue just a report of a successful build and run of Xray "Call of Pripyat"  on the Apple Silicon (Macbook Air M1) with Asahi Linux ( https://asahilinux.org/ ) 

The code compiles and runs but unfortunately there is not yet a native GPU driver for the M1 so the game runs only via software rendering (slow slide-show) but runs :) 

Reference and screens here https://twitter.com/astr0baby/status/1564728692009484288

**Comment by q4a** [comment]
Sceens from twitter:
![screen1](https://user-images.githubusercontent.com/1950719/187599481-ecfbd694-f300-462d-ac56-e428c0268f0b.jpg)
![screen2](https://user-images.githubusercontent.com/1950719/187599519-7eb5fbd5-aaab-495c-a849-a2eb4291f18d.jpg)
![screen3](https://user-images.githubusercontent.com/1950719/187599536-d8cbf2c2-8151-4bd3-98f2-7d037753050d.jpg)
