### ISSUE TITLE
Call Of Pripyat Benchmark

### ISSUE THREAD

**Issue by MartyShepard** [Swartz27/xray-16#1083]
**Describe the bug**
 Just for fun. Actually, I wanted to see how OpenXray has progressed using the benchmark tool from "https://cop.stalker-game.com/?page=downloads" (stkcop-bench-setup.exe). Under the wiki is cop specified as a full playable, so I thought I could test the new graphics card with the benchmark tool and look how and see how it is in 64-bit. It Doenst Start, see only 3x the the Splash.

**To Reproduce**
1. Go to '.' - Renamed bin_test Folder to Backup
2. Go to '..' - Copy the Contents from Github Release Build Archive (Bin, Gamedata and fsgame.ltx - not fsuser..) to the Banchmark Folder
3. Go to '...' - Renamed folder in Benchmark directory "bin" to "bin_test". Start Benchmark 

**Expected behavior**
---

**Screenshots**
---
[OpenXRay_error_report_220903-163654.zip](https://github.com/OpenXRay/xray-16/files/9482805/OpenXRay_error_report_220903-163654.zip)

**BugTrap error report**
added a crashreport if you have it. It should be located in `_appdata_/reports` folder

**Desktop (please complete the following information):**
 - OS: 
 - Windows 7 SP1
 - AMD FX 8350
 - 32GB Ram
 - RTX 2060 12GB
 - OpenXRay build version 1565 from AppVeyor Build [Image: Visual Studio 2019; Configuration: Release; Platform: x64](https://ci.appveyor.com/project/OpenXRay/xray-16/build/job/uv88wdimil0lwr2c)

**Additional context**
Maybe it's not a bug and I did something wrong?

**Comment by Xottab-DUTY** [comment]
Thank you!

Yep, the benchmark is broken currently, it was a known bug, but I forgot to create the issue here.

**Comment by Xottab-DUTY** [comment]
I just removed the support for original COP benchmark, it was more problematic than fancy.

We need to think on implementing some in-game benchmarking tool that can be run using just a console command or a button inside the in-game editor
