### ISSUE TITLE
Перевёрнутое изображение на OpenGL

### ISSUE THREAD

**Issue by NeXProgger** [Swartz27/xray-16#1094]
При выборе рендерера rgl изображение за исключением некоторых шейдеров и моделей перевернуто по вертикали, также, при первых нескольких входах в меню анимированная часть фона заменена зеленым цветом. При перезаходе в игру с включенным rgl при пропуске интро игра часто вылетает без создания репорта и запуска BugTrap
![ss_dimac_10-02-22_15-13-39_(marsh)](https://user-images.githubusercontent.com/86261298/193451110-08967357-4994-4c6b-babc-956055189296.jpg)
ОС: Windows 10 21H2 19044.1889

**Comment by Xottab-DUTY** [comment]
Не хватает обновлённого шейдера. Только пока не понимаю каким образом получилось, что шейдеры для OpenGL у тебя есть, но старые...

Версия движка? Откуда был скачан?

**Comment by NeXProgger** [comment]
> Не хватает обновлённого шейдера. Только пока не понимаю каким образом получилось, что шейдеры для OpenGL у тебя есть, но старые...
> 
> Версия движка? Откуда был скачан?

Версия движка на момент написания последняя из actions. Шейдеры из gamedata вроде, которая на вики. Игра - сталкер чистое небо.

**Comment by Xottab-DUTY** [comment]
@NeXProgger, шейдер `combine_1.vs` нужно положить не из gamedata, которая на вики, а из gamedata, которая в архиве с Actions.

> При перезаходе в игру с включенным rgl при пропуске интро игра часто вылетает без создания репорта и запуска BugTrap

А можешь поподробнее описать?

**Comment by Xottab-DUTY** [comment]
Дубликат #647, #1073

**Comment by NeXProgger** [comment]
> @NeXProgger, шейдер `combine_1.vs` нужно положить не из gamedata, которая на вики, а из gamedata, которая в архиве с Actions.
> 
> > При перезаходе в игру с включенным rgl при пропуске интро игра часто вылетает без создания репорта и запуска BugTrap
> 
> А можешь поподробнее описать?

игра как будто закрывается, происходит не всегда.

**Comment by johndoe71rus** [comment]
OpenXRay Release build 8838, Apr 19 2023 (Linux 64-bit, shared)
Custom build from commit[c3d7cc7d266bc473c72ec4cc7028972b092fe898] branch[dev]
перевернуто. геймдата из репы.

**Comment by johndoe71rus** [comment]
![ss_johndoe_04-23-23_12-48-09_(marsh)](https://user-images.githubusercontent.com/7861172/233893799-ef0091a8-1e67-4e54-848c-4fc693c154fc.jpg)
![ss_johndoe_04-23-23_12-48-17_(marsh)](https://user-images.githubusercontent.com/7861172/233893817-c02cc9a0-88e5-4a75-a66a-c3bf2d00ac5e.jpg)

**Comment by johndoe71rus** [comment]
перепроверил. gamedata из wiki. удалил старые шейдеры из _appdata_ запустил снова.

**Comment by GermanAizek** [comment]
@johndoe71rus,
1. gamedata for clear sky needed download from here:
https://github.com/OpenXRay/xray-16/wiki/[EN]-How-to-install-and-play#user-content-installation-on-clear-sky
or direct link here: 
https://github.com/OpenXRay/xray-16/files/4348865/gamedata.zip

2. replace `shaders/ogl` from `res/gamedata` in OpenXRay repo

**Comment by johndoe71rus** [comment]
@GermanAizek 
выше это и проверил, gamedata из вики актуальная на 25 апреля. Сейчас скачал файл снова, идентичные.
Перед запуском удалил что было в appdata.

**Comment by GermanAizek** [comment]
Да но ты забыл явно шейдеры opengl перекинуть из res/gamedata, вчера такая же проблема была. Просто скопируй шейдеры из репозитория из каталога shaders/gl и замени все.

**Comment by johndoe71rus** [comment]
я не забыл. я следовал инструкции. 
https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-install-and-play#user-content-installation-on-clear-sky
удалить gamedata, распаковать ее из архива.

оказывается после этого надо дополнительно взять ТОЛЬКО /res/gamedata/shaders/gl/ и скопировать в gamedata для ЧН. При копировании некоторые файлы переписывает.

**Comment by GermanAizek** [comment]
@johndoe71rus, забыли обновить инструкцию, бывает.

**Comment by Xottab-DUTY** [comment]
Обновил инструкцию по установке для ЧН. Закрою, т.к. по зелёному интро есть #647 и вылет при пропуске интро это, скорее всего, #1433 и #1420.
