### ISSUE TITLE
Clear Sky widescreen patch doesn't work properly

### ISSUE THREAD

**Issue by catsuperberg** [Swartz27/xray-16#1097]
Если использовать файлы из xray-16\bin\Win64\Mixed для запуска Stalker Чистое Небо (GOG версия), то при запуске в верхнем правом углу появляется красный текст:
**! UNABLE TO FIND SOFTWARE\GSC GAME WORLD\STALKER-COP\ IN REGISTRY
! PLAYER NAME REGISTRY KEY ( INSTALLUSERNAME) NOT FOUND !
! UNABLE TO FIND SOFTWARE\GSC GAME WORLD\STALKER-COP\ IN REGISTRY
! NVIDIA ANSEL: : FAILED TO LOAD ANSELSDXXX. DLL**
![image](https://user-images.githubusercontent.com/9151200/194288092-6ac38002-7be3-4373-8133-f2bbe93cfb58.png)

После этого запуск новой игры или загрузка вызывает вылет с ошибкой в файле Actor.cpp.

Чтобы воспроизвести баг:
1. Скачать игру из GOG
2. Скопировать папку с игрой, в ярлыке "Launch S.T.A.L.K.E.R. Clear Sky" исправить Target и StartIn
3. В fsgame.ltx изменить "$game_data$ = false| true|  $fs_root$|  gamedata\" на "$game_data$ = true| true|  $fs_root$|  gamedata\"
4. Распаковать папку gamedata (взятую с wiki по установке) в корень игры
5. Склонированный гитом проект собрать в конфигурации Mixed
6. Закинуть в папку игры bin собранные файлы
7. Запустить игру

Если билдить Release, то игра запускается, точно также как и с билдом который можно скачать тут в разделе Release 

Конфигурация:
- Windows 11
- рендерер: r4 (насколько я понял это dx11 рендер, который и является основным для проекта?)
- репозиторий склонирован 5 октября (версию билда не понял где можно посмотреть)

Странно ещё то, что он ищет записи в реестре по SOFTWARE\GSC GAME WORLD\STALKER-COP\, когда игры на 64 бит операционке делают записи в SOFTWARE\WOW6432Node\GSC Game World\STALKER-STCS\. На всякий случай пробовал установить таки COP (ради записей в реестре), но это ничего не поменяло.

**Comment by Xottab-DUTY** [comment]
Вылет то какой?

**Comment by catsuperberg** [comment]
> Вылет то какой?

Вот, это при запуске новой игры.
![image](https://user-images.githubusercontent.com/9151200/194295572-63a51920-44c3-4ff5-ba85-83b4bc37f1bc.png)


**Сорри, что-то не подумал что это просто ассерт и его можно попробовать пропустить. Игра дальше работает но выдаёт больше ошибок**
![image](https://user-images.githubusercontent.com/9151200/194296293-076a8a55-d317-469f-8549-f5933bd56a30.png)

**Comment by Xottab-DUTY** [comment]
Верно, это не вылет, это просто VERIFY, который можно пропускать. Есть R_ASSERT, который пропускать уже не стоит... Но по окошку ты не отличишь р_ассерт от верифая, только в коде) ну, и, по памяти, что не было таких окошек на релизе)

Красный текст это всего лишь последние 5 ошибок из лога.

Это норма.

**Comment by catsuperberg** [comment]
Ок, спасибо. А убрать сообщения както можно? Удалить логи?
Ещё вопрос небольшой, какой рендер оптимальнее использовать? А то с r4 саншафты через стены винды. И планируется ли что-то со смещением шрифтоф в кнопках, а то я попробовал закинуть Widescreen Patch из SRP и не помогло, как это работает в оригинале.

**Comment by Xottab-DUTY** [comment]
Есть консольная команда `show_red_text` (точное название не помню, но в подсказках она вылезет), она выключает красный текст с ошибками на экране. Ещё есть ключ запуска – `-xclsx`.
Для R4 шейдеры из ЗП, по идее, нужны, а для шейдеров ЧН – оптимальнее R3.

Можешь насчёт шрифтов накидать скринов, что за проблема?
И как должно выглядеть после widescreen patch)

**Comment by catsuperberg** [comment]
В основном проблема с кнопками (хотя я пока не начал играть, чтобы везде заметить).
Кстати, попробовал opengl и r3 (dx10 в настройках?), в r3 тоже саншафты через стену лезут (пробовал удалить r3 в gamedata/shaders - тоже самое), в opengl всё вроде красиво.

**Вот в OpenXRay (текст на кнопках выше центра):**
![xrEngine_2022_10_06_14_17_37_883](https://user-images.githubusercontent.com/9151200/194301798-477ef91b-e656-4ece-848e-82fca76123b5.jpg)
![xrEngine_2022_10_06_14_17_54_015](https://user-images.githubusercontent.com/9151200/194301810-ccec7d8a-8723-4e0d-8055-338884db39b7.jpg)
![xrEngine_2022_10_06_14_24_58_696](https://user-images.githubusercontent.com/9151200/194301821-beb610a5-c1c9-46cc-ac52-947e936c61d2.jpg)


**Вот оригинал с Widescreen Patch (текст на кнопках по центу):**
![xrEngine_2022_10_06_14_25_58_154](https://user-images.githubusercontent.com/9151200/194301921-0cf9a2ed-40f1-46b4-a881-7538e6d1639d.jpg)
![xrEngine_2022_10_06_14_26_03_054](https://user-images.githubusercontent.com/9151200/194303471-b8ea1f0d-16d8-4c9d-87df-b3244430021d.jpg)
![xrEngine_2022_10_06_14_26_40_319](https://user-images.githubusercontent.com/9151200/194301952-9770cff3-1530-48dd-8136-8d29d8dcff9e.jpg)

**Comment by Xottab-DUTY** [comment]
Неправильное расположение кнопок починил в ba154b88bba43fedbe9b8ca5b7cea6e899dac30b и 9e11f227a5c9be1ac9ae43266c69a486ebf6543b
