### ISSUE TITLE
Crash when trying to swap primary weapon while not having a pistol in the arsenal - Stalker Clear Sky

### ISSUE THREAD

**Issue by GiulianoB-1** [Swartz27/xray-16#1099]
I progressed at the game a lot, got to the duty part where I need to get underground, I am using SRP 1.1.4. I tried to swap my weapon, and the game just crashed. It doesnt matter which weapon I will try to swap with. I managed to swap my weapon by dropping the weapon that I want to swap with and moving my weapon to the inventory and then grabbing my weapon that I dropped before. I tried after that to swap again to check if the bug is caused only with specific weapon or not, but the game crashes no matter which weapon I am holding in my arsenal and no matter which weapon I want to swap with. Here's the crash reports:

[OpenXRay_error_report_221009-115703.zip](https://github.com/OpenXRay/xray-16/files/9741151/OpenXRay_error_report_221009-115703.zip)
[OpenXRay_error_report_221009-115623.zip](https://github.com/OpenXRay/xray-16/files/9741152/OpenXRay_error_report_221009-115623.zip)
[OpenXRay_error_report_221009-115620.zip](https://github.com/OpenXRay/xray-16/files/9741153/OpenXRay_error_report_221009-115620.zip)
[OpenXRay_error_report_221009-115541.zip](https://github.com/OpenXRay/xray-16/files/9741154/OpenXRay_error_report_221009-115541.zip)
[OpenXRay_error_report_221009-115537.zip](https://github.com/OpenXRay/xray-16/files/9741155/OpenXRay_error_report_221009-115537.zip)
[OpenXRay_error_report_221009-120147.zip](https://github.com/OpenXRay/xray-16/files/9741156/OpenXRay_error_report_221009-120147.zip)
[OpenXRay_error_report_221009-120144.zip](https://github.com/OpenXRay/xray-16/files/9741157/OpenXRay_error_report_221009-120144.zip)
[OpenXRay_error_report_221009-115706.zip](https://github.com/OpenXRay/xray-16/files/9741158/OpenXRay_error_report_221009-115706.zip)

**Comment by GiulianoB-1** [comment]
I moved some of my items to a box to have less weight while I am in the Agroprom underground. So apparently, because I moved my pistol to the box, it causes the bug. I checked if dropping the pistol will have the same affect and it does. Not having a pistol causes a crash when swapping between primary weapons.

**Comment by Xottab-DUTY** [comment]
Clear Sky had two separate slots for pistols and rifles, while Call of Pripyat has two equal slots.
This engine is COP engine, so, even in Clear Sky, slots are equal...
But there is a problem: pistol slot in CS is too small to fit a rifle and it crashes because of that.

**Comment by Xottab-DUTY** [comment]
Fixed with 12ec2f5d9d93ab3f7fcba91ebb10eb895fae3e67
