### ISSUE TITLE
Untouchable NPCs (including myself) - Stalker Clear Sky

### ISSUE THREAD

**Issue by GiulianoB-1** [Swartz27/xray-16#1101]
I went into Cordon through the Receiving Post to eliminate a bandits that captured the outpost. There was only one bandit, I was shooting at him to kill him and it did nothin at all(no even blood stains or something). He also tried to shoot me, but it didn't damage me either. I could even go through the bandit's body. A squad of stalkers arrived to capture the post and started shooting the bandit, but neither them could have damage the bandit. I tried to shoot the stalkers to check if it will damage them, it did nothing, same as the bandit. I even tried to kill myself with a grenade and it didn't do anything at all. I have zero idea what connection it has, I dont know if it can only occur in cordon, and I dont know how it happens

**Comment by Xottab-DUTY** [comment]
What version of the engine you are using?

**Comment by GiulianoB-1** [comment]
> What version of the engine you are using?

The lastest, 2021 RC1(Note: I am also using SRP 1.1.4)

**Comment by Xottab-DUTY** [comment]
@GiulianoB-1, did you used exactly 2021 RC1 version, or a latest nighly builds? (latest on 9th of October)

**Comment by GiulianoB-1** [comment]
> @GiulianoB-1, did you used exactly 2021 RC1 version, or a latest nighly builds? (latest on 9th of October)

exactly 2021 RC1 version

**Comment by Xottab-DUTY** [comment]
For sure, 0eba8bda1e14acdd44fcbf4e8aab7c5cc8a8b2ea should fix the issue.
