### ISSUE TITLE
Unknown Crashes - Stalker Clear Sky

### ISSUE THREAD

**Issue by GiulianoB-1** [Swartz27/xray-16#1102]
Playing at the aprogrom research institute, fighting some bandits and mutants and I am suddenly getting some random crashes. Looks familiar, like the SRP-combat crashes that was reported and maybe fixed with SRP 1.1.4
[OpenXRay_error_report_221010-102807.zip](https://github.com/OpenXRay/xray-16/files/9744021/OpenXRay_error_report_221010-102807.zip)
[OpenXRay_error_report_221010-102804.zip](https://github.com/OpenXRay/xray-16/files/9744022/OpenXRay_error_report_221010-102804.zip)
[OpenXRay_error_report_221010-103829.zip](https://github.com/OpenXRay/xray-16/files/9744023/OpenXRay_error_report_221010-103829.zip)
[OpenXRay_error_report_221010-103827.zip](https://github.com/OpenXRay/xray-16/files/9744024/OpenXRay_error_report_221010-103827.zip)

It looked like when I killed a bandit that was about to throw a grenade, I got a crash. I also got a crash after a grenade explosion . Maybe a coincidence cuz it has nothing to do with the mutants, I didn't and neither a stalker threw a grenade when it happened

**Comment by GiulianoB-1** [comment]
It might be instability of my pc after undervolting my cpu, tho I am sure it is worth to check the crash notes if it was a bug or instability.

**Comment by Xottab-DUTY** [comment]
Combat crashes related to grenades are probably related to #768, and that was fixed.
Moreover, there was many other fixes for CS, so I'm closing this as it's tooooo old.
