### ISSUE TITLE
build failed on artix linux

### ISSUE THREAD

**Issue by hypeq** [Swartz27/xray-16#1111]
[ 44%] Linking CXX shared library ../../x64/Release/xrGame.so
collect2: fatal error: ld terminated with signal 7 [Bus error]
compilation terminated.
make[2]: *** [src/xrGame/CMakeFiles/xrGame.dir/build.make:20401: x64/Release/xrGame.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1368: src/xrGame/CMakeFiles/xrGame.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by Xottab-DUTY** [comment]
@eagleivg, @masterkatze, @007exe, hi guys, maybe you have some ideas?

@hypeq, just as a guess.. Are there enough RAM? And what are builds options (e.g. what terminal commands you have executed)

**Comment by hypeq** [comment]
yay -S openxray

**Comment by hypeq** [comment]
![image](https://user-images.githubusercontent.com/95980101/196550128-1af5f319-62a9-45f8-8de9-0ae03dcbed61.png)
neofetch output

**Comment by eagleivg** [comment]
3.8 - 1.7 = 2.1 Gb. I presume that its not enough for linking xrGame. On my system the linker consumes about 6.1 gigabytes. Try use swap in the missing amount of memory, then it may build (although it will be extremely long, it is better to leave such a build overnight). Or use prebuild artefacts from GitHub Actions.

**Comment by hypeq** [comment]
swap already used (5gb)

**Comment by 007exe** [comment]
It looks like a lack of memory, but I successfully built the engine on a similar configuration. Perhaps there are some nuances related to Artis, I am not familiar with this distribution. @hypeq Out of interest, try to build openxray-git is a fresh slice of the source code.

**Comment by dasehak** [comment]
The engine is currently compiling and running on Artix.

**Comment by Xottab-DUTY** [comment]
Thanks for the update!
