### ISSUE TITLE
Unable to enter Limansk - Stalker clear sky

### ISSUE THREAD

**Issue by GiulianoB-1** [Swartz27/xray-16#1112]
After lowering the bridge to limansk, going to through the tunnel to Limansk resulting in a crash with an error:
![image](https://user-images.githubusercontent.com/67099534/196627414-a3c58810-ee30-462e-8b98-d47d70470acd.png)

[OpenXRay_error_report_221019-103535.zip](https://github.com/OpenXRay/xray-16/files/9817999/OpenXRay_error_report_221019-103535.zip)

I am using the latest 2021 openxray build and SRP 1.1.4

**Comment by Xottab-DUTY** [comment]
I still not sure how this crash has appeared in 2021 pre-release, but it was fixed... There was no new release yet, though.

**Comment by Castlesoap** [comment]
По логу видно: завис set_patrol_extrapolate_callback. Скорее всего, это и вызвало ошибку!  У меня такое было на Агропроме, когда из пещеры вылазили снорки! Как я понимаю, баг вызывает схема mob_jump. Вместо Нил используется пустая строка. У меня нет сейчас игры и скриптов под рукой, но вспомню… если покажете мне Колбек весь. Там вместо Нил нужно ещё добавить проверку и на пустую строку. Это все что я помню!

**Comment by GiulianoB-1** [comment]
> I still not sure how this crash has appeared in 2021 pre-release, but it was fixed... There was no new release yet, though.

Oh that's sucks so bad, I hope a fix will be released soon for that

**Comment by AnirohDev** [comment]
Is there any workaround for the 2021 version maybe? Would be really much appreciated so I can finish the game. I've tried several dev builds from the last 3 months, but all of them crash when loading a savegame from the 2021 version.

Error report when loading savegame:
[OpenXRay_error_report_221031-004549.zip](https://github.com/OpenXRay/xray-16/files/9897074/OpenXRay_error_report_221031-004549.zip)
