### ISSUE TITLE
Color issue with the river under Limansk's bridge

### ISSUE THREAD

**Issue by GiulianoB-1** [Swartz27/xray-16#1113]
![image](https://user-images.githubusercontent.com/67099534/196628683-f44d72e3-649a-4e5b-a125-28e006a1eeb7.png)

No idea how does it occurs at all, just loaded my save and boom

**Comment by Xottab-DUTY** [comment]
This should have been fixed with 4beaf75ee1a6cb6bf6bae6de5f6458832e2fabe5.
