### ISSUE TITLE
Fix memory leak in CCC_DebugFonts

### ISSUE THREAD

**Issue by Xottab-DUTY** [Swartz27/xray-16#1123]
https://github.com/OpenXRay/xray-16/blob/14a049e809c923488f77079d5d722198736d08fd/src/xrGame/console_commands.cpp#L1058

**Comment by Aty-0** [comment]
```
static auto debugFonts = xr_new<CUIDebugFonts>();
debugFonts->ShowDialog(true); 
```
Я немного залетный и не шарю за xray, так что не уверен пойдет ли подобный код.

**Comment by Xottab-DUTY** [comment]
> ```
> static auto debugFonts = xr_new<CUIDebugFonts>();
> debugFonts->ShowDialog(true); 
> ```
> 
> Я немного залетный и не шарю за xray, так что не уверен пойдет ли подобный код.

Ну, да, оно лучше!
С оригинальным кодом, сколько раз ты вызвал консольную команду `debug_fonts`, столько раз и произойдёт утечка.
С твоим кодом, утечка произойдёт только один раз.

В идеале, надо найти какое-то место, куда пристроить это выделение памяти, чтобы потом и освобождение сделать.

**Comment by Aty-0** [comment]
Может временно повесить умный указатель туда `std::unique_ptr`? Или вы std не используете в проекте ?

**Comment by Xottab-DUTY** [comment]
> Может временно повесить умный указатель туда `std::unique_ptr`? Или вы std не используете в проекте ?

Дак, а причём он тут)
Его же точно так же нужно будет повесить куда-то. Если его прям в этой функции повесить, он освободится сразу после выхода из неё.

P.S. std используем активно, бывают некоторые исключения, например: вместо `std::unique_ptr` используется `xr_unique_ptr`.
