### ISSUE TITLE
Investigate if multiplayer UI was ported to SDL2 correctly

### ISSUE THREAD

**Issue by Xottab-DUTY** [Swartz27/xray-16#1127]
Какое-то подозрительное использование Escape
![image](https://user-images.githubusercontent.com/2989212/198905021-36c46426-dcb1-402c-bbeb-c17e15e4ad10.png)

DIK_1 и DIK_0 у DirectInput расположены непоследовательно. А у SDL2 – последовательно.
Получается, при использовании SDL2, условие выполняется всегда и всегда происходит ранний return в CUIDialogWnd::OnKeyboardAction.
![image](https://user-images.githubusercontent.com/2989212/198905023-cb0bf822-2cf4-43b2-a846-cdeafb0dd67b.png)

**Comment by Plotja** [comment]
В первом случае действительно ошибка. Там будет некорректное отображение быстрых клавиш покупки в окне торговли.

В описании второго случая возможно неточность(прошу меня исправить, если я не прав): 

В SDL2 клавиши  '0' и '1' расположены **непоследовательно**:
![image](https://user-images.githubusercontent.com/45823818/200136647-44444126-a64d-41da-8acd-82dc14215fe2.png)

Точно так же как и в реализации оригинальной игры:
![image](https://user-images.githubusercontent.com/45823818/200136820-7cd8e78b-2abf-47d4-974a-42bcb8581735.png)

**Comment by Xottab-DUTY** [comment]
Спасибо!
