### ISSUE TITLE
[Call of Pripyat] combine_1 making all terrain and models upside down

### ISSUE THREAD

**Issue by deltanedas** [Swartz27/xray-16#1133]
**Describe the bug**
All terrain, characters, guns, shells, etc. are upside down.
Only things I've seen normally are:
- the sky
- "shadows" of terrain that are completely black
- water??? on terrain
the latter 2 can only effectively be seen

**To Reproduce**
1. Start game
2. See that everything is fucked

**Expected behavior**
Terrain and stuff lining up with their "shadows".

**Screenshots**
Looking down:
![22:41:54](https://user-images.githubusercontent.com/39013340/201548922-d55af980-5fcd-4eee-ab35-575cb8c0f179.png)
Looking up:
![22:42:17](https://user-images.githubusercontent.com/39013340/201548948-56cd725c-2a42-4285-bd59-2b6bb59ae9ee.png)

**Desktop:**
 - OS: Debian Sid
 - GPU: GT 740
 - GL: 4.6.0 NVIDIA 390.154
 - OpenXRay commit 43536393bf5cfa8002554ececc63186154a5bbae

**Additional context**
Tried to fix by replacing the `-I.P.y` with `I.P.y` in combine_1.vs but backface culling or something made none of it render, gave up after that.

**Comment by eagleivg** [comment]
Where did you get the gamedata from? Is the link to the shader correct?

**Comment by deltanedas** [comment]
`fsgame.ltx levels localization mp patches resources` are symlinks to steam data, gamedata/shaders/gl is a symlink to `/usr/local/share/openxray/gamedata/shaders/gl` which exists, modifications work when `ninja install`'d but don't know how to fix

**Comment by Xottab-DUTY** [comment]
It looks like you had OpenXRay installed previously, but now you have updated the engine?
Did you updated the shaders in `/usr/local/share/openxray/gamedata/shaders/gl` with the new ones from `xray-16/res/gamedata/shaders/gl`?

**Comment by deltanedas** [comment]
yes they are updated by `ninja install` along with the engine

**Comment by Xottab-DUTY** [comment]
@deltanedas, can you try to update them manually?

**Comment by deltanedas** [comment]
yeah i copy them myself from res/gamedata didnt help

**Comment by sobkas** [comment]
Couldn't reproduce.

**Comment by Xottab-DUTY** [comment]
The issue happens when engine is updated and shaders are not, or vice-versa.

Similar to #1073 and #1094.

I've updated the Clear Sky instructions on the wiki and the way how COP gamedata is installed, so I think this can be closed.
