### ISSUE TITLE
Bug with permanently destroyed light sources

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1147]
**Describe the bug**
Light bulbs and light sources are destroyed with grenades and are no longer being created after load save.

**To Reproduce**
1. Watch videos

**Screenshots**
https://user-images.githubusercontent.com/21138600/204701100-07c97db5-239a-4484-af25-9e7700ee892c.mp4
https://user-images.githubusercontent.com/21138600/204701113-592bf7cb-4667-4666-b0d5-9080b67f54d0.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Any CoP stalker and OpenXRay

**Comment by Xottab-DUTY** [comment]
It's not a bug.
