### ISSUE TITLE
Linux - Installation broken

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#1200]
**Describe the bug**
`sudo make install` doesn't finish

**BugTrap error report**
```
Make Error at misc/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/home/biel/code/xray/OpenXray/misc/bash-completion": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:62 (include)
```

**Desktop (please complete the following information):**
 - OS: [Linux22.10]
 - OpenXRay build version [0d8c5b46fcb886ecc6c765603b6274fae63fa6e1]

**Comment by Xottab-DUTY** [comment]
Fixed in c191e0135cc4a4beaba69fea51b8095441a6c85f, thanks for the report! 👍
