### ISSUE TITLE
Не стартует квест "Отправиться к форпосту с проводником"

### ISSUE THREAD

**Issue by 0xA50C1A1** [Swartz27/xray-16#1212]
**Describe the bug**
Не стартует квест "Отправиться к форпосту с проводником". Должен появляться после диалога с торговцем.

**To Reproduce**
1. Получить квест "Помочь форпосту"
2. Поговорить с проводником

**Expected behavior**
Должен запуститься квест "Отправиться к форпосту с проводником", в диалоге с проводником должны появиться соответствующие реплики.

**Screenshots**
![Текущие квесты](https://user-images.githubusercontent.com/105977161/211190163-ff2990e0-b6d2-4ad5-8f90-66664c7c053b.png)
![Диалог с проводником](https://user-images.githubusercontent.com/105977161/211190164-64bd70e8-d7e5-457c-8192-2f1d066fe1aa.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Сборка OpenXRay из dev ветки

**Comment by 0xA50C1A1** [comment]
Квест стартует только при корректном завершении диалога с торговцем. В оригинальном Clear Sky он стартовал в любом случае.

**Comment by RomashkaTea** [comment]
Поставь gamedata [отсюда](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-install-and-play) и всё заработает как надо

**Comment by Xottab-DUTY** [comment]
За полтора года поддержка ЧН улучшилась, так что баг мог быть уже исправлен (если это баг на стороне движка).
Пока закрою, можно переоткрыть, если баг всё ещё воспроизводится на свежих ночных сборках.
