### ISSUE TITLE
Game crashes loading savegame

### ISSUE THREAD

**Issue by Arrigi** [Swartz27/xray-16#1234]
**Describe the bug**
I played the game for a few hours on monday. Worked fine. Quicksave, quit.
Started the game the next day, crashed after a few minutes. Re-started, re-opened save game. Crashed again after a few minutes. This seemed to be after trading some stuff, but I wanted to sell something. The trading could be irrelevant.

At some point I made a new quicksave after the trade. Game crashed again. This quicksave now immediately crashes when trying to load.

I've tried a full, clean re-install with fresh openxray. No dice.

**To Reproduce**
1. Start game.
2. Open included savegame.
3. Crash on loading screen.

**Expected behavior**
Loading the game without crashing.

**Screenshots**
N/A

**BugTrap error report**
OpenXRay_error_report_230124-223305.zip

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - OpenXRay Release Master Gold build 8754 (happens on december 2021 build as well)

**Additional context**

[OpenXRay_error_report_230124-223305.zip](https://github.com/OpenXRay/xray-16/files/10504443/OpenXRay_error_report_230124-223305.zip)
[jef - quicksave.zip](https://github.com/OpenXRay/xray-16/files/10504445/jef.-.quicksave.zip)

**Comment by Xottab-DUTY** [comment]
> This quicksave now immediately crashes when trying to load.

The save file is corrupted for some reason.
Unfortunately, I'm unable to identify the reason :(

Since this is a stale issue, I can only close it. We can reopen the bug, if the original crash is reproducible on the newest nightly builds.
