### ISSUE TITLE
Запуск CoP

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [Swartz27/xray-16#1236]
Всегда запускал все сталкера с ярлыка с изменённой рабочей папкой (без папки bin):
![изображение](https://user-images.githubusercontent.com/38873082/215242061-e96aab9d-2bab-4d5d-9a34-da31373891db.png)
Что даёт запуск CoP через [дефолтный лайнчер](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-install-and-play#installation-on-call-of-pripyat) (4. Launch the game using original launcher Stalker-COP.exe), кроме просто запуска?
P.S. В стиме CoP запускается напрямую, без лаунчера.

**Comment by Xottab-DUTY** [comment]
Ничего не даёт. Просто так проще.
