### ISSUE TITLE
Проблема при подключении мода Dynamic news (говорят, на х64 движках ее быть не должно)

### ISSUE THREAD

**Issue by Darkkys** [Swartz27/xray-16#1253]
Собственно проблема в заголовке.
При подключении мода новостей спам в лог на bind_monster. Где спрашивал - пишут что эта ошибка только на ванильном движке должна быть. На х64 с этим "что-то сделано", поэтому пишу сюда..

На игре это сказывается - новости со временем просто перестают приходить.. (в новостях о мутантах не заполняются их "имена" )
`! [LUA]  CharacterCommunity available only for InventoryOwner
stack traceback:
	...\s.t.a.l.k.e.r. cop\gamedata\scripts\vs_send_news.script:660: in function 'GiveStalker'
	...\s.t.a.l.k.e.r. cop\gamedata\scripts\vs_send_news.script:590: in function 'SeeMonstersNews'
	e:\games\s.t.a.l.k.e.r. cop\gamedata\scripts\vsm.script:51: in function 'func'
	...es\s.t.a.l.k.e.r. cop\gamedata\scripts\vscallback.script:79: in function 'OnMutantSpawn'
	...\s.t.a.l.k.e.r. cop\gamedata\scripts\bind_monster.script:312: in function <...\s.t.a.l.k.e.r. cop\gamedata\scripts\bind_monster.script:295>
	
! [LUA]  CharacterCommunity available only for InventoryOwner
stack traceback:
	...\s.t.a.l.k.e.r. cop\gamedata\scripts\vs_send_news.script:660: in function 'GiveStalker'
	...\s.t.a.l.k.e.r. cop\gamedata\scripts\vs_send_news.script:590: in function 'SeeMonstersNews'
	e:\games\s.t.a.l.k.e.r. cop\gamedata\scripts\vsm.script:51: in function 'func'
	...es\s.t.a.l.k.e.r. cop\gamedata\scripts\vscallback.script:79: in function 'OnMutantSpawn'
	...\s.t.a.l.k.e.r. cop\gamedata\scripts\bind_monster.script:312: in function <...\s.t.a.l.k.e.r. cop\gamedata\scripts\bind_monster.script:295>
	
! [LUA]  CharacterCommunity available only for InventoryOwner
stack traceback:
	...\s.t.a.l.k.e.r. cop\gamedata\scripts\vs_send_news.script:660: in function 'GiveStalker'
	...\s.t.a.l.k.e.r. cop\gamedata\scripts\vs_send_news.script:590: in function 'SeeMonstersNews'
	e:\games\s.t.a.l.k.e.r. cop\gamedata\scripts\vsm.script:51: in function 'func'
	...es\s.t.a.l.k.e.r. cop\gamedata\scripts\vscallback.script:79: in function 'OnMutantSpawn'
	...\s.t.a.l.k.e.r. cop\gamedata\scripts\bind_monster.script:312: in function <...\s.t.a.l.k.e.r. cop\gamedata\scripts\bind_monster.script:295>`

**Comment by Xottab-DUTY** [comment]
Странно, что я сразу не заметил эту issue :D

Дело не в x64.
Дело в том, что в движке ЗП у монстров вырезали инвентарь, а DynamicNews пытается узнать в какой группировке находятся мутанты, но это возможно только у тех, у кого есть инвентарь.

У нас он возвращён, но пока только для режима ТЧ/ЧН. Включать эти режимы тоже чревато, так будет ещё куча вещей включено, что вряд ли нужно))

Через какое-то время сделаем возможность включить инвентарь для монстров через openxray.ltx без включения полноценного режима ТЧ или ЧН. :)
