### ISSUE TITLE
Stalker COP crash after launch in Wine on macOS

### ISSUE THREAD

**Issue by Drovosek01** [Swartz27/xray-16#1254]
**Describe the bug**
I installed game S.T.A.L.K.E.R. Call of Pripyat [GOG] in Wine. It starts and works without problems, but if I choose improved dynamic lighting with DX10 in the graphics settings, then after that the sun rays disappear in the game. The same problem exists in older versions of Crossover, but when using the latest Crossover 22.1, there is no problem with the rays of the sun.

I wrote a bug about this in the Wine repository and the developer replied to me that the problem is that the game is 32-bit, but the new version of Crossover added a Directx translator for 32-bit versions.

I thought it might be possible to fix this by making the game 64-bit using a new engine. I downloaded the latest version of OepnXRay for Windows and replaced the files according to the instructions. After starting the game in Wine, the game logo is displayed first, and then a Crash Log window appears. Then I downloaded the 2021 RC version and replaced the files in the game with files from this version and then launched Wine wrapper, but the game also did not start

**To Reproduce**
1. Make blank Wineskin wrapper using engine WS11WineCX64Bit22.0.1-2 or WS11WineCX64Bit22.0.1-1
2. Download "S.T.A.L.K.E.R.: Call of Pripyat v1.6.0.2" GOG version
3. Install game in wrapper and select default path for base Windows app `"C:\GOG Games\S.T.A.L.K.E.R. Call of Pripyat\Stalker-COP.exe" `
4. Test Run. It works because GOG installer include and install some DirectX and Visual C++ components
5. In game menu open settings and set "Enhanced full dyn. lighting (DX10)", Apply changes and restart game/wrapper
6. Start new game or load any saves and look on sky, trees and environment
7. Using Winetricks install all d3d* components
8. Using Winetricks install all visual c++ / vcrun components 
9. Run game and repeat point 6 and see no sun rays
10. Install OpenXRay to folder with game
11. Run Wineskin wrapper

**Expected behavior**
Game launch

**Screenshots**
`-`

**BugTrap error report**
[OpenXRay_error_report_230219-161856.zip](https://github.com/OpenXRay/xray-16/files/10777143/OpenXRay_error_report_230219-161856.zip)

**Desktop (please complete the following information):**
- OS: macOS Monterey 12.6.2
- Winery version: 1.8.4.2
- Master Wrapper version: Wineskin-2.9.1.6
- Engine version: WS11WineCX64Bit22.0.1-2
- Hardware: MacPro 2013 Hackintosh - Xeon E5-2666 v3, RX 580 4GB, 64GB RAM, SSD NVMe
- Application/Game Name: S.T.A.L.K.E.R. Call of Pripyat [GOG]
- OpenXRay: latest nightly build for Windows and also tried version "December 2021 RC1"

**Additional context**
https://github.com/Gcenx/WineskinServer/issues/355

**Comment by Xottab-DUTY** [comment]
I fixed crashes on DX11 with DXVK in 6152011880afb68a2991807918c315dcbd18cddb and 5b0085c9360f8a40b43d84c091dc687325967aeb. Though, you've launched through Wine, in the log I see the same crash as with DXVK.

@Drovosek01, could you check?

**Comment by Xottab-DUTY** [comment]
I want to reduce amount of stale issues. So, since this exact crash was fixed, I'd like to close this issue :)
