### ISSUE TITLE
Linux - [CS/COP] - When EAX is on: all sounds seem to cut-off at the 1'' mark after start playing. 

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#1271]
**Describe the bug**

when EAX is on, and after quitting the engine and re-starting again (to make sure all sound is initialized with EAX on)  any sound, form any movie/music/or longer sound effect like ambience, seems to cut-off after a second of it is reproduced (the movies, and the ui keeps working just the sound is cut-off.
within the game, since most sound of the gameplay are shorter than 1 second this is not noticeable.

Strangely after a time has passed the music (which is clearly longer than 1 second :) ) plays correctly.

I don't know if Sound is cut-off or if its volume is lowered to silence.
 
**To Reproduce**
1. select the option of EAX on
2. restart the engine to make sure sound is properly initialized
3. already the movies at the start of the engine should have the sound cut-off around the 1 second mark after start, so all the rest of music of the UI.

**Expected behavior**
sound should last al long as it should as it properly happens with EAX off

**Screenshots**
non-applicable

**BugTrap error report**
none

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.10]
 - OpenXRay build version [b65ea4ae5e7881effc95f0b471839e03ab9d843e]

**Additional context**
none

**Comment by Xottab-DUTY** [comment]
@BielBdeLuna, can you check if this bug has appeared after merging #1231 or it has existed before?

**Comment by BielBdeLuna** [comment]
It existed before, it had been for a long time

**Comment by johncurley** [comment]
This bug is caused by the sound being interrupted by a misplaced error that is caused in a different place. I haven't managed to track down the source of the error but it can be mitigated by flushing the error cache.

**Comment by BielBdeLuna** [comment]
now that you tell this, in the console there is non-stop:
**! update:: source state check failed (0x40963)**
**! update:: source state check failed (0x40963)**
**! update:: source state check failed (0x40963)**
**! update:: source state check failed (0x40963)**
in red coloured lettering

**Comment by johncurley** [comment]
> 

Yes, that is the interruption of the sound updating by the error. It isn't the actual problem, though I haven't tracked down where the error is initially occurring.

**Comment by BielBdeLuna** [comment]
I can confirm that this recurring message only appears if EAX is ON

**Comment by johncurley** [comment]
> I can confirm that this recurring message only appears if EAX is ON

Thanks for letting me know. Everything else with sound on Linux should be functional once this is fixed. In the initial commit I had a error flush routine but it was in the incorrect place as the error is cached and carried through to the next error check. So once this is fixed the sound should be working with EFX effects on Linux.

**Comment by BielBdeLuna** [comment]
great!

**Comment by johncurley** [comment]
> great!

Should be fixed now. Hopefully it gets merged quickly. It was a conversion function that wasn't needed giving wrong parameter errors.

https://github.com/OpenXRay/xray-16/pull/1272/commits/fc24d647218b00235934003f0b88bb6c3c9f90df

**Comment by Xottab-DUTY** [comment]
Hurray!

**Comment by BielBdeLuna** [comment]
I'm sorry I can't test the results with the mimallloc error going on!

**Comment by BielBdeLuna** [comment]
after https://github.com/OpenXRay/xray-16/issues/1273#issuecomment-1489168167 now I could test it! great it works! :)
