### ISSUE TITLE
grass casting shadows was axed out by GSC for eficiency sake, could it be reversed?

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#1303]
**Is your feature request related to a problem? Please describe.**
after the first version of Stalker SOC the first thing that GSC axed in favour of rendering efficiency was the grass casting shadows, it never came back.

in CS the tall grass of the swamps cast shadows, but still the normal grass don't.

**Describe the solution you'd like**
could it be possible to restore back all grass shadows?

**Describe alternatives you've considered**
none...

**Additional context**
here is an example of how in version 1.000 the grass casted shadows: https://www.youtube.com/live/-v-ErJ87_vc?feature=share&t=104

and here is how CS tall grass in the swamps cast shadows but the normal grass don't:
![Captura de pantalla de 2023-04-18 18-57-46](https://user-images.githubusercontent.com/2709433/232850332-3bb41f4b-e06c-463e-a15e-2776c7b7827e.png)

**Comment by Xottab-DUTY** [comment]
It was restored in OpenXRay several years ago (in 2019 or 2020). Sorry for lack of documentation.

**Comment by Xottab-DUTY** [comment]
Use `r2_sun_details on` in console 😊
