### ISSUE TITLE
Dynamic geometry disappear after loading a game after loading a multiplayer game first

### ISSUE THREAD

**Issue by Xottab-DUTY** [Swartz27/xray-16#1307]
**To Reproduce**
1. Start multiplayer game (first map in the list)
2. Disconnect
3. Load singleplayer game from a save
4. Dynamic geometry (visuals) disappears from the rendering

**Additional context**
Something happens with camera in multiplayer game, so that frustum culling in spatial culls everything with the certain camera angles.

Reported by @vTurbine

**Comment by SkyLoaderr** [comment]
The reason for the disappearance of dynamic geometry is the lack of updating data in SpatialBase class after changing map. In `void ISpatial_DB::initialize(Fbox& BB)` there is a check for `m_root` which doesnt work because `m_root` already exists from last map.
