### ISSUE TITLE
[Call of Pripyat] Game hangs when entering a location "lab X8"

### ISSUE THREAD

**Issue by ivanednor98** [Swartz27/xray-16#1333]
**Describe the bug**
I'm not able to enter lab X8 on the latest version.
I'm receiving an error "malloc(): invalid next size (unsorted)" in the end.
Attaching the debug log from engine built with an option "-DCMAKE_BUILD_TYPE=Debug".

**To Reproduce**
1. Install the latest version on xray-16 (commit d44cd796f80fcc3993d2394a47f3e582f7c8a697).
2. Go to elevator and press F to enter lab X8
3. See game hangs

**Expected behavior**
Normally enter lab X8.

**Screenshots**
game hangs:
![Screenshot from 2023-05-08 12-16-22](https://user-images.githubusercontent.com/103031176/236799469-ecb7b1ec-ca68-487b-8cca-b0ea786770ca.png)

**BugTrap error report**
Debug log:
[xr_3da.log](https://github.com/OpenXRay/xray-16/files/11420213/xr_3da.log)
[user.ltx](https://github.com/OpenXRay/xray-16/files/11442941/user.ltx.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2
 - OpenXRay build version d44cd796f80fcc3993d2394a47f3e582f7c8a697 (1.6.02_amd64)

Thanks in advance!

**Comment by ivanednor98** [comment]
Please let me know if I can provide more details

**Comment by vTurbine** [comment]
Could you please attach your `user.ltx` as well?

**Comment by ivanednor98** [comment]
@vTurbine sure
[user.ltx](https://github.com/OpenXRay/xray-16/files/11442932/user.ltx.txt)

**Comment by vTurbine** [comment]
Thank you for the config. I tried to repro the issue locally but realized that I need an access card to use x8 elevator. Could you please attach a save file, so I can check load/unload sequence for x8 level?

**Comment by ivanednor98** [comment]
> Thank you for the config. I tried to repro the issue locally but realized that I need an access card to use x8 elevator. Could you please attach a save file, so I can check load/unload sequence for x8 level?

of course, attaching the savegame
[before_x8_elevator.scop.zip](https://github.com/OpenXRay/xray-16/files/11445889/before_x8_elevator.scop.zip)

**Comment by Xottab-DUTY** [comment]
> malloc(): invalid next size (unsorted)

Interesting. I'm curious if that's related to #863? 🤔

**Comment by vTurbine** [comment]
Unfortunately, I can't repro it on my Windows machine. But after some guesswork, I found one suspicious place in alife initialization, which does autosave with malformed strings in names. Sometimes. I would recommend trying the next:
* switch the game to English language and try your luck with elevator again (this will use a correct name for intermediate autosave). To do this, set `g_language` to `en` in your `user.ltx` file
* If you can modify and re-compile the code, find a function with signature `void CALifeUpdateManager::load(LPCSTR game_name, bool no_assert, bool new_only)` and put a `Msg` print at the very beginning with `game_name` as argument. Then check the log for the printed message.

**Comment by ivanednor98** [comment]
> Unfortunately, I can't repro it on my Windows machine. But after some guesswork, I found one suspicious place in alife initialization, which does autosave with malformed strings in names. Sometimes. I would recommend trying the next:
> 
>     * switch the game to English language and try your luck with elevator again (this will use a correct name for intermediate autosave). To do this, set `g_language` to `en` in your `user.ltx` file
> 
>     * If you can modify and re-compile the code, find a function with signature `void CALifeUpdateManager::load(LPCSTR game_name, bool no_assert, bool new_only)` and put a `Msg` print at the very beginning with `game_name` as argument. Then check the log for the printed message.

Thanks for the thoughts on this, but no luck:

printing the game_name gives nothing weird, just "ivan - autosave" and then still `malloc(): invalid next size (unsorted)`
![image](https://github.com/OpenXRay/xray-16/assets/103031176/c4cb8c7f-f1d5-4541-a526-afd085e5e090)

changing `g_language` to `en` does not actually affect the game language and I get same issue, but this is probably not where the problem lies

**Comment by vTurbine** [comment]
I see. I made a mistake specifying the language code, it should be `eng`, not `en`.
At this point I can’t do much and someone from community with Linux machine should check this.
But if you have time and will, you can try:
* move debug message around ai loading code (I strongly suspecting it) to see when it disappears in the log, so you can narrow the scope where problem code is
* run the game with Valgrind or through GDB to see the callstack at moment of crash

You also can jump into project Discord if you need more operative responses.

**Comment by GermanAizek** [comment]
@vTurbine,
![image](https://github.com/OpenXRay/xray-16/assets/21138600/090d162d-eb40-4f88-8924-d00330656d39)

**Comment by delvin-fil** [comment]
Тоже самое.
OpenXRay Release build 8906, Jun 26 2023 (Linux 64-bit, shared)
Custom build from commit[38a8381737011f313fefbd33599f4b9699cc2d2e] branch[HEAD]
![изображение](https://github.com/OpenXRay/xray-16/assets/20687641/35c784c6-ed78-4675-8745-d65ec9492e89)

**Comment by sobkas** [comment]
Was able to enter X8 when openxray was built with libmimalloc-dev
Crashes with regular allocator.
Will take a look into regular allocator crash.

**Comment by delvin-fil** [comment]
> Was able to enter X8 when openxray was built with libmimalloc-dev
Crashes with regular allocator.

all right
в режиме БОГА 100% не входит
в обычном убивают у лифта ДАЖЕ В ЭКЗО(специально удалял gamedata, копировал файл экзоскелета и наращивал защиту = БРОНЮ до 40000%)

**Comment by sobkas** [comment]
Fix: https://github.com/OpenXRay/xray-16/pull/1431
Crashes because writing past nodes array.

**Comment by ivanednor98** [comment]
I've built the latest version of engine and I'm able to continue game now :fire: :fire: :fire: :fire:  . Thank you so much! :heart: :heart: :heart: :heart: :heart: :heart: 
@sobkas
