### ISSUE TITLE
Sprinting while holding Forward and Backward causes player to stand still while sprint animation plays

### ISSUE THREAD

**Issue by yohjimane** [Swartz27/xray-16#1365]
**Describe the bug**
Sprinting while holding Forward and Backward causes player to stand still while sprint animation plays

**To Reproduce**
1. Start sprinting forward
2. hold down backwards key without letting go of forward key
3. Observe player stands still, but sprint animation still plays

**Expected behavior**
Sprint animation should end if player is not moving

**Video**
https://github.com/OpenXRay/xray-16/assets/11345783/218ebeaf-0400-4ffd-8407-11d19cdad424

**Comment by GermanAizek** [comment]
@yohjimane, hasn't it been fixed here?
https://github.com/OpenXRay/xray-16/pull/1142

**Comment by yohjimane** [comment]
@GermanAizek I don't think so, I tested this on latest openxray dev. I'm not seeing anything in the [changed files](https://github.com/OpenXRay/xray-16/pull/1142/files) that looks like it would fix this
