### ISSUE TITLE
CHUDState m_hud_item_state, m_nextState incorrect initialization on new game

### ISSUE THREAD

**Issue by yohjimane** [Swartz27/xray-16#1374]
**Describe the bug**
m_hud_item_state and m_nextState initialize with incorrect value `eIdle` on new game. The value they should initialize with is `eHidden`.

**To Reproduce**
1. put breakpoint in `CWeapon::OnActiveItem` function, on the first line
2. Load into new game with debugger enabled
3. On initial load when breakpoint is hit, observe CHUDState m_hud_item_state, m_nextState = 0 `eIdle`
4. Switch to a different weapon, observe CHUDState m_hud_item_state, m_nextState = 0 `eIdle`
5. Switch to initial weapon again, observe observe CHUDState m_hud_item_state, m_nextState = 3 `eHidden`

**Expected behavior**
On initial load, items should have eHidden state. It looks like [this logic should work](https://github.com/OpenXRay/xray-16/blob/dev/src/xrGame/HudItem.h#L38), but it does not.

**Screenshots**
Initial load state:
![image](https://github.com/OpenXRay/xray-16/assets/11345783/c7bcbdff-d4b2-44b2-a935-2da50fd4f04e)

State after switching to different weapon, and then switching back
![image](https://github.com/OpenXRay/xray-16/assets/11345783/4991baca-a8d6-4e46-9398-480fbfb2539e)

**Comment by yohjimane** [comment]
This doesn't really effect anything in vanilla game + openxray, but in my fork I want to defer some logic under certain conditions until hud items are in `eIdle` state. 

The logic works in every other case, but doesn't work correctly on initial load due to this bug.

**Comment by yohjimane** [comment]
Looks like the root cause of the issue is due to wpn_state default value getting overridden in net_Spawn:
```cpp
bool CWeapon::net_Spawn(CSE_Abstract* DC)
{
    ...
    CSE_Abstract* e = (CSE_Abstract*)(DC);
    CSE_ALifeItemWeapon* E = smart_cast<CSE_ALifeItemWeapon*>(e);
    ...
    SetState(E->wpn_state); // BUG: wpn_state is always 0 on initial load!
    SetNextState(E->wpn_state);
    ...
}
```

It looks like this wpn_state data comes from packet, and on initial load since there is no packet it is defaulting to 0...

**Comment by Xottab-DUTY** [comment]
Fixed

**Comment by Creshhh** [comment]
how do I fix these weapon icons?
![Uploading Снимок экрана 2024-11-22 231956.png…]()

**Comment by Creshhh** [comment]
how do I fix these weapon icons?
![Снимок экрана 2024-11-22 231956](https://github.com/user-attachments/assets/5e9043c3-7ad7-4b16-9750-e3d2b8d2bf33)
