### ISSUE TITLE
Вылетает при попытке подойти к Прачечной

### ISSUE THREAD

**Issue by delvin-fil** [Swartz27/xray-16#1377]
Вопрос в заголовке.
Изменения в файлах:
1. Увеличена убойность "Винтореза"
2. Увеличена переносимая масса
3. Увеличен прыжок
4. Установлен "Повелитель зоны"(версию не помню)(без мода все тоже самое)

Есть "Сердце оазиса"

[Log](https://pastebin.com/W9DCgmUd) 

> **BugTrap error report**
Please, add a crashreport if you have it. It should be located in `_appdata_/reports` folder
отсутствует такой каталог

Gentoo
OpenXRay Release Master Gold build 8850, May  1 2023 (Linux 64-bit, shared)
Custom build from commit[025120a4dee7d4aa3d9c1b5d2e15ec1860a80fcc] branch[dev]

**Comment by Xottab-DUTY** [comment]
@vTurbine, a crash in the renderer :)

**Comment by delvin-fil** [comment]
> @vTurbine, a crash in the renderer :)

Так а что с этим делать то? Оазис не выбросить, ученые его тоже брать не хотят.
Заново проходить?

**Comment by Xottab-DUTY** [comment]
А причём тут Оазис, вылет совершенно не из-за него.

**Comment by Xottab-DUTY** [comment]
Можешь приложить user.ltx, с которым играешь?

**Comment by vTurbine** [comment]
Билд от 1 мая. Обновить бы

**Comment by delvin-fil** [comment]
> Можешь приложить user.ltx, с которым играешь?

https://pastebin.com/pvNVHE7p

**Comment by delvin-fil** [comment]
сохраненка: https://yadi.sk/d/-TBDyogeQEVtQg
может нужна

**Comment by Xottab-DUTY** [comment]
@delvin-fil попробуй обновить движок до свежих коммитов и собрать. После 1 мая как раз были фиксы по рендеру 😊

**Comment by delvin-fil** [comment]
[Ошибка](https://i.imgur.com/kFQnTmz.png)

**Comment by Xottab-DUTY** [comment]
(скриншоты можно вставлять прям сюда, просто Ctrl+V)

А как ты до этого движок собрал?

Странненькая ошибка, не может найти линкер

**Comment by delvin-fil** [comment]
![изображение](https://github.com/OpenXRay/xray-16/assets/20687641/db5a351d-f7b9-427f-85e2-8d6a9b350b4c)
какой самый свежий для i3 + Radeon HD 5500 с  "для мододелов"?


> А как ты до этого движок собрал?

никак - с рутрекера скачал 

> Странненькая ошибка, не может найти линкер

может потому что выбрал latest-nightly?

**Comment by Xottab-DUTY** [comment]
latest-nightly, верно. Самая свежая версия. Остальные теги все устаревшие.

Не может найти ld, возможно, потому что ld не установлен... Или ld.gold не установлен.

"Для мододелов" это нужно просто собирать с выключенной опцией MASTER_GOLD.

А что за раздача на рутрекере?
Попросить бы автора обновить :)

**Comment by delvin-fil** [comment]
>Не может найти ld, возможно, потому что ld не установлен... Или ld.gold не установлен.

```
lh /usr/bin/ld
lrwxrwxrwx 1 root root 22 мая  7 06:57 /usr/bin/ld -> x86_64-pc-linux-gnu-ld*
```

**Comment by Xottab-DUTY** [comment]
А ld gold?
При сборке CMake, скорее всего, выбирает ld gold, которого в системе нет

**Comment by delvin-fil** [comment]
![изображение](https://github.com/OpenXRay/xray-16/assets/20687641/d2298ea6-6d18-43b1-9cd2-bfa726746301)
да, действительно, binutils без gold

>с выключенной опцией MASTER_GOLD

как выключить?

**Comment by Xottab-DUTY** [comment]
При запуске команды cmake указать, например:
`cmake .. -DMASTER_GOLD=OFF`

**Comment by delvin-fil** [comment]
> cmake .. -DMASTER_GOLD=OFF

А так не пойдет?
-DCMAKE_BUILD_TYPE=Mixed

**Comment by Xottab-DUTY** [comment]
Не пойдёт, по пунктам:
1) Mixed есть только на винде, под линуксом это Debug.
2) Debug это вообще отладочная сборка с кучей лишнего для простой игры функционала.
Если он не нужен, а нужны только читы, то лучше собирать Release с выключенным Master Gold.

**Comment by delvin-fil** [comment]
Понял.
binutils пересобрал с gold и компиляция с параметрами
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_BINDIR=/usr/games/bin -DMASTER_GOLD=OFF
пошла.
Спасибо!

**Comment by delvin-fil** [comment]
![изображение](https://github.com/OpenXRay/xray-16/assets/20687641/809d7014-373d-492c-ad71-981c2a9f8bd2)
Собрал. Работает! Спасибо!
