### ISSUE TITLE
Broken screenshots on OpenGL renderer

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1378]
**Describe the bug**
Render OpenGL on Linux screenshots in  `_appdata_/screenshots` folder are not displayed correctly.

**To Reproduce**
1. Press F12
2. Check folder

**Screenshots**
![ss_ubuntu_12-23-22_03-28-22_(zaton)](https://github.com/OpenXRay/xray-16/assets/21138600/3f955d3a-2f25-44a4-b60e-7c91b53e4af5)

![ss_ubuntu_12-23-22_18-58-33_(jupiter)](https://github.com/OpenXRay/xray-16/assets/21138600/c5d1f971-0b4e-490b-8ff1-59a3ddd940f3)

**Desktop:**
 - OS: Ubuntu 22.04
 - OpenXRay build version [[fc6ad72](https://github.com/GermanAizek/xray-16/commit/fc6ad72e13da13d2b6053becc21d82ba652e5ed4)]

**Comment by sobkas** [comment]
Can't reproduce with 481d4dc8edd58866a79e072dc65355259c08fe5b
Screenshots look ok, maybe can be closed?
![ss_krzysztof sobiecki_08-20-23_14-30-23_(marsh)](https://github.com/OpenXRay/xray-16/assets/116554/68b2adae-053e-43db-a544-6cdfe38971b9)
![ss_krzysztof sobiecki_08-20-23_14-33-54_(zaton)](https://github.com/OpenXRay/xray-16/assets/116554/22aa4084-38b2-43e6-bf3a-32408c230ec5)

**Comment by Xottab-DUTY** [comment]
@sobkas, could I ask you to try to reproduce it with llvmpipe driver?

**Comment by sobkas** [comment]
Main menu looks ok, but loading save or starting new game hangs at load screen.
![ss_krzysztof sobiecki_08-20-23_19-13-14_(mainmenu)](https://github.com/OpenXRay/xray-16/assets/116554/c914f097-ae31-4e05-913e-c6bd228dd806)
It hangs for some reason:
![Zrzut ekranu z 2023-08-20 19-18-54](https://github.com/OpenXRay/xray-16/assets/116554/522d0a5c-7d3b-4936-9876-eb554eb2dca4)
Will take a look at what's going on

**Comment by sobkas** [comment]
It hangs inside llvmpipe:

> #5  0x00007fffdc9113b9 in cnd_wait (cond=<optimized out>, mtx=<optimized out>) at ../src/c11/impl/threads_posix.c:135
#6  0x00007fffdcef85ab in lp_fence_wait (f=f@entry=0x5555890a0d60) at ../src/gallium/drivers/llvmpipe/lp_fence.c:127
#7  0x00007fffdcef5920 in llvmpipe_fence_finish (screen=<optimized out>, ctx=<optimized out>, fence_handle=0x5555890a0d60, timeout=18446744073709551615)
    at ../src/gallium/drivers/llvmpipe/lp_screen.c:917
#8  0x00007fffdcef882d in llvmpipe_finish (pipe=pipe@entry=0x555556e2b920, reason=reason@entry=0x7fffdda9a356 "sampler_view")
    at ../src/gallium/drivers/llvmpipe/lp_flush.c:97
#9  0x00007fffdcef890f in llvmpipe_flush_resource (pipe=pipe@entry=0x555556e2b920, resource=0x55555758c710, level=level@entry=0, 
    read_only=read_only@entry=1 '\001', cpu_access=cpu_access@entry=0 '\000', do_not_block=do_not_block@entry=0 '\000', reason=0x7fffdda9a356 "sampler_view")
    at ../src/gallium/drivers/llvmpipe/lp_flush.c:143
#10 0x00007fffdcf27c5b in llvmpipe_set_sampler_views (pipe=0x555556e2b920, shader=MESA_SHADER_FRAGMENT, start=0, num=3, unbind_num_trailing_slots=0, 
    take_ownership=true, views=0x7fffffffabe0) at ../src/gallium/drivers/llvmpipe/lp_state_sampler.c:152
#11 0x00007fffdcbc75cb in update_textures (st=0x555557062f80, shader_stage=MESA_SHADER_FRAGMENT, prog=<optimized out>)
    at ../src/mesa/state_tracker/st_atom_texture.c:271

**Comment by sobkas** [comment]
Too soon to know what is a problem

**Comment by sobkas** [comment]
It hangs in two places

> #3  0x00007ffff7cce8dd in Sleep (ms=<optimized out>) at ./src/Common/PlatformLinux.inl:68
#4  CRenderDevice::ProcessFrame (this=0x7ffff7dfedc0 <Device>) at ./src/xrEngine/device.cpp:284
#5  CRenderDevice::ProcessFrame (this=0x7ffff7dfedc0 <Device>) at ./src/xrEngine/device.cpp:257
#6  0x00007ffff7ccefa9 in CRenderDevice::message_loop (this=this@entry=0x7ffff7dfedc0 <Device>) at ./src/xrEngine/device.cpp:398

And then in

#5  0x00007fffd61113b9 in cnd_wait (cond=<optimized out>, mtx=<optimized out>) at ../src/c11/impl/threads_posix.c:135
#6  0x00007fffd66f85ab in lp_fence_wait (f=f@entry=0x5555afdaa770) at ../src/gallium/drivers/llvmpipe/lp_fence.c:127
#7  0x00007fffd66f5920 in llvmpipe_fence_finish (screen=<optimized out>, ctx=<optimized out>, fence_handle=0x5555afdaa770, timeout=18446744073709551615)
    at ../src/gallium/drivers/llvmpipe/lp_screen.c:917
#8  0x00007fffd66f882d in llvmpipe_finish (pipe=pipe@entry=0x555556e32200, reason=reason@entry=0x7fffd729a356 "sampler_view")
    at ../src/gallium/drivers/llvmpipe/lp_flush.c:97
#9  0x00007fffd66f890f in llvmpipe_flush_resource (pipe=pipe@entry=0x555556e32200, resource=0x55555759c9a0, level=level@entry=0, 
    read_only=read_only@entry=1 '\001', cpu_access=cpu_access@entry=0 '\000', do_not_block=do_not_block@entry=0 '\000', reason=0x7fffd729a356 "sampler_view")
    at ../src/gallium/drivers/llvmpipe/lp_flush.c:143
#10 0x00007fffd6727c5b in llvmpipe_set_sampler_views (pipe=0x555556e32200, shader=MESA_SHADER_FRAGMENT, start=0, num=1, unbind_num_trailing_slots=0, 
    take_ownership=true, views=0x7fffffffabe0) at ../src/gallium/drivers/llvmpipe/lp_state_sampler.c:152
#11 0x00007fffd63c75cb in update_textures (st=0x555557067840, shader_stage=MESA_SHADER_FRAGMENT, prog=<optimized out>)
    at ../src/mesa/state_tracker/st_atom_texture.c:271
both hangs repeat

As it's only happens with llvmpipe, I believe it's the culprit 
Opened https://gitlab.freedesktop.org/mesa/mesa/-/issues/9667

**Comment by Xottab-DUTY** [comment]
> Too soon to know what is a problem

It's possible to just take a screenshot in the main menu

**Comment by Xottab-DUTY** [comment]
I don't know if it's actual.
