### ISSUE TITLE
Graphical artefacts on R4 renderer using any Proton version

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1381]
**Describe the bug**
Tested versions:
 - lutris-GE-Proton7-x86_64
 - Proton Experimental
 
DXVK version: v2.2
VKD3D version: v2.9
D3D Extras: v2
DXVK-NVAPI / DLSS: v0.6.3

**Screenshots**

https://github.com/OpenXRay/xray-16/assets/21138600/e0a855c3-a20b-4ab9-9176-19d8cfc9cc37

**Desktop:**
 - OS: Ubuntu 22.04
 - OpenXRay build version [[fc6ad7](https://github.com/OpenXRay/xray-16/commit/fc6ad72e13da13d2b6053becc21d82ba652e5ed4)]

**Comment by Xottab-DUTY** [comment]
This should be reported to Proton devs. Probably as a separate issue (not in the original game compatibility thread listed below).

Compatibility reports with **original** games:
1. https://github.com/ValveSoftware/Proton/issues/1174
2. https://github.com/ValveSoftware/Proton/issues/1166
