### ISSUE TITLE
OpenXRay crashed on Wine 6.0.3

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1384]
**Describe the bug**
```
$ wine64 --version
wine-6.0.3 (Ubuntu 6.0.3~repack-1)
```

**Screenshots**
![image](https://github.com/OpenXRay/xray-16/assets/21138600/2d73dfd0-699f-43fe-a8ee-515a0d7e7e03)

**Desktop:**
 - OS: Ubuntu 22.04
 - OpenXRay build version [[1cadea](https://github.com/OpenXRay/xray-16/commit/1cadeae20a81c56a1986b3484fccad8e31c09f71)]

**Comment by Xottab-DUTY** [comment]
Fixed with 6152011880afb68a2991807918c315dcbd18cddb and 5b0085c9360f8a40b43d84c091dc687325967aeb.

**Comment by Xottab-DUTY** [comment]
Thanks!
