### ISSUE TITLE
On latest commits Debug configuration enabled spheres that appear when killing NPCs with knife

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1388]
**Describe the bug**
I do not know commands to disable these spheres.

**Screenshots**
https://github.com/OpenXRay/xray-16/assets/21138600/920fd08b-8268-4422-a034-6e29d06f4413

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - OpenXRay build version [[1cadea](https://github.com/OpenXRay/xray-16/commit/1cadeae20a81c56a1986b3484fccad8e31c09f71)]

**Comment by Xottab-DUTY** [comment]
It's not an issue.
