### ISSUE TITLE
Clear Sky Зависает при переходе в "яму мутантов" на "Агропроме" и в "Рыжий лес"

### ISSUE THREAD

**Issue by delvin-fil** [Swartz27/xray-16#1413]
В заголовке

**Screenshots**
![разные разрешения игры и экрана](https://github.com/OpenXRay/xray-16/assets/20687641/a32201f2-5f3f-483f-b792-d0100990b2f6)

**BugTrap error report**
отсутствует

**Desktop (please complete the following information):**
Gentoo
openxray-025120a

```
tail -20 scs/appdata/logs/openxray_delvin.log 
[LUA]  _se_smart_terrain: set load marker: 1267
[LUA]  _CCombat_manager: set load marker: 1267
[LUA]  _CCover_manager: set load marker: 1282
[LUA]  _CCover_manager: LOAD DIF: 2
[LUA]  _CCombat_manager: LOAD DIF: 19
[LUA]  _se_smart_terrain: LOAD DIF: 23
[LUA]  _se_smart_terrain: set load marker: 432
[LUA]  _CCombat_manager: set load marker: 432
[LUA]  _CCover_manager: set load marker: 529
[LUA]  _CCover_manager: LOAD DIF: 2
[LUA]  _CCombat_manager: LOAD DIF: 101
[LUA]  _se_smart_terrain: LOAD DIF: 177
[LUA]  _se_smart_terrain: set load marker: 334
[LUA]  _CCombat_manager: set load marker: 334
[LUA]  _CCover_manager: set load marker: 349
[LUA]  _CCover_manager: LOAD DIF: 2
[LUA]  _CCombat_manager: LOAD DIF: 19
[LUA]  _se_smart_terrain: LOAD DIF: 23
[LUA]  _se_smart_terrain: set load marker: 355
[LUA]  _CCombat_manager: set
```

**Comment by dasehak** [comment]
Полный лог, пожалуйста.
(P.S. Через какую утилиту столбец справа делал?)

**Comment by GermanAizek** [comment]
@dasehak, dude you ...
https://github.com/brndnmtthws/conky

**Comment by delvin-fil** [comment]
> Полный лог, пожалуйста. (P.S. Через какую утилиту столбец справа делал?)

сейчас лог с чистым выходом, ибо вышел с Юпитера на Агропром
Чуть позже дам.

по боковой панели - [GermanAizek](https://github.com/GermanAizek) ответил - conky

**Comment by Hrusteckiy** [comment]
> Юпитера на Агропром

0_o

**Comment by delvin-fil** [comment]
> > Юпитера на Агропром
> 
> 0_o

Ошибся
![изображение](https://github.com/OpenXRay/xray-16/assets/20687641/541ec045-ea6b-4521-9d35-a172ccdbf6d0)


лог опять чистый
позже сыграю
там псизона

**Comment by delvin-fil** [comment]
очищаю лог и начаинаю игру - мин

**Comment by delvin-fil** [comment]
Полный лог:
ttps://yadi.sk/d/KgxNjB7J3_JacA

**Comment by Xottab-DUTY** [comment]
@delvin-fil, проверь на свежих коммитах.
Один вылет при переходах по локациям был исправлен в #1431.

**Comment by delvin-fil** [comment]
@Xottab-DUTY проверю позже - на работе уматываюсь.
Спасибо!

**Comment by delvin-fil** [comment]
# git checkout  2088-august-2023-rc1
# cd bin/
# cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Mixed -DCMAKE_INSTALL_BINDIR=/usr/games/bin
# make

```[  4%] Building CXX object src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/cmake_pch.hxx.gch
In file included from /home/delvin/games/stalker/xray-16/src/Common/Common.hpp:6,
                 from /home/delvin/games/stalker/xray-16/src/utils/xrMiscMath/pch.hpp:3,
                 from /home/delvin/games/stalker/xray-16/bin/src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/delvin/games/stalker/xray-16/src/Common/Platform.hpp:78:5: ошибка: #error Unknown configuration
   78 | #   error Unknown configuration
      |     ^~~~~
cc1plus: замечание: unrecognized command-line option «-Wno-interference-size» may have been intended to silence earlier diagnostics
make[2]: *** [src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/build.make:77: src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/cmake_pch.hxx.gch] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:1034: src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/all] Ошибка 2
make: *** [Makefile:156: all] Ошибка 2
```

**Comment by Xottab-DUTY** [comment]
Ты чё-то не то делаешь :)
Mixed'а нету под линуксом и `2088-august-2023-rc1` это не самые свежие коммиты, там фикса нет, нужно прям самую свежую ветку dev.

**Comment by delvin-fil** [comment]
1144-december-2021-rc1
1725-weather-editor
1728-january-2023-rc2
1747-january-2023-rc3
2088-august-2023-rc1
21
221
421
510
558
730-july-preview
784-october-preview
812-december-preview
822-december-preview
b6762
b6764
latest-nightly
xd132
xd187
xd216
xd239
xd261
xd58

**Comment by delvin-fil** [comment]
git checkout  latest-nightly
mkdir bin
cd bin
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Mixed -DCMAKE_INSTALL_BINDIR=/usr/games/bin

```
[  4%] Built target xrLuajit
[  4%] Building CXX object src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/cmake_pch.hxx.gch
In file included from /home/delvin/games/stalker/xray-16/src/Common/Common.hpp:6,
                 from /home/delvin/games/stalker/xray-16/src/utils/xrMiscMath/pch.hpp:3,
                 from /home/delvin/games/stalker/xray-16/bin/src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/delvin/games/stalker/xray-16/src/Common/Platform.hpp:84:5: ошибка: #error Unknown configuration
   84 | #   error Unknown configuration
      |     ^~~~~
cc1plus: замечание: unrecognized command-line option «-Wno-interference-size» may have been intended to silence earlier diagnostics
make[2]: *** [src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/build.make:77: src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/cmake_pch.hxx.gch] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:1034: src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/all] Ошибка 2
make: *** [Makefile:156: all] Ошибка 2
```

**Comment by Xottab-DUTY** [comment]
Mixed нету под линуксом, только под виндой.
Надо -DCMAKE_BUILD_TYPE=Release указывать

**Comment by delvin-fil** [comment]
```bash
git checkout latest-nightly
mkdir bin
cd bin
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_BINDIR=/usr/games/bin
```
теперь работает
но вылетов стало больше
спасибо

**Comment by delvin-fil** [comment]
Теперь не зависает, а просто вылетае при переходе на "Лиманск"
[Лог](https://yadi.sk/d/nym0wm8tEF0NCg)

**Comment by Xottab-DUTY** [comment]
@delvin-fil, можешь дать сохранение, на котором вылетает?

**Comment by delvin-fil** [comment]
@Xottab-DUTY  автосейв или перед тем как в локицию пойти?

**Comment by Xottab-DUTY** [comment]
Можно даже оба 😁

**Comment by delvin-fil** [comment]
@Xottab-DUTY
у перехода "limansk.sav" - иду в тоннель
"delvin - autosave.sav" - уже висим
[оба здесь](https://yadi.sk/d/q1oI3AZDVH-hfA)

**Comment by sobkas** [comment]
Loading autosave is ok.
Trying to load limansk.sav

I'm getting:
```
FATAL ERROR
 
[error] Expression    : ini_file.section_exist(section)
[error] Function      : process
[error] File          : ./src/xrGame/trade_parameters_inline.h
[error] Line          : 70
[error] Description   : cannot find section trade_friend_sell
```
Do you use any mods?

**Comment by delvin-fil** [comment]
@sobkas only [this one](https://www.playground.ru/stalker_clear_sky/cheat/s_t_a_l_k_e_r_chistoe_nebo_vse_predmety_u_torgovtsev-758260)

**Comment by Hrusteckiy** [comment]
Какая-то васянка, раз новый список торговли добавлен. Да и непонятно, зачем такое, ломает баланс и логику торговцев, где у каждого *свой* ассортимент.

**Comment by Xottab-DUTY** [comment]
@Hrusteckiy так это чит мод же

**Comment by delvin-fil** [comment]
Распаковал оригинальную gamedata
чуть позде попробую с ней

**Comment by Xottab-DUTY** [comment]
@delvin-fil, я глянул. Надо при сборке ещё добавить `-DMASTER_GOLD=ON`.
У тебя он выключенным оказался.

**Comment by Xottab-DUTY** [comment]
Недостаточно данных для определения причины проблемы.
