### ISSUE TITLE
Graphical errors in skybox, changing level graphics does not affect.

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1416]
**Describe the bug**
More glxinfo for determining causes of graphical bugs.
[glxinfo.txt](https://github.com/OpenXRay/xray-16/files/12295261/glxinfo.txt)
[glxinfo_b.txt](https://github.com/OpenXRay/xray-16/files/12295263/glxinfo_b.txt)

lspci info:
[lspci.txt](https://github.com/OpenXRay/xray-16/files/12295501/lspci.txt)

**Screenshots**
![screen](https://github.com/OpenXRay/xray-16/assets/21138600/667288b2-1578-4268-955f-fc57e69352cd)

**BugTrap error report**
[openxray_debian.log](https://github.com/OpenXRay/xray-16/files/12295255/openxray_debian.log)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - OpenXRay Release Master Gold build 8720, Dec 22 2022 (Linux 64-bit, shared)
Custom build from commit[d79ae01c6ac04bfab843b6eec9dc1772230bf540] branch[dev]

**Comment by Xottab-DUTY** [comment]
What's the conditions you are running in? (device, gpu, it's an emulator??)

**Comment by Xottab-DUTY** [comment]
You are submitting too many issues without the corresponding info.
I had to ask you about your hardware, while it is you who should supply this information when **creating** the issue.
And more over, you are saying that you have supplied all required info. No, you are not.
You didn't even told here that your CPU is ARM and told that in chat just suddenly.

Reopen this, when all info is gathered and attached here.

**Comment by Xottab-DUTY** [comment]
Banned this inadequate user.

**Comment by GermanAizek** [comment]
> Banned this inadequate user.

@Xottab-DUTY,  Unban discord, I have become adekvat.

**Comment by Xottab-DUTY** [comment]
> > Banned this inadequate user.
> 
> @Xottab-DUTY, Unban discord, I have become adekvat.

Cool! Done.
