### ISSUE TITLE
Monsters from different communities are not fighting each other.

### ISSUE THREAD

**Issue by Neloreck** [Swartz27/xray-16#1445]
**Describe the bug**

All the configuration of monster relations is ignored and all communities fallback to team `8`, which unifies all of them in one community. As result, all the `is_enemy` checks in monsters manager are `false`, we do not check further if teams are same.

**To Reproduce**

a) Just meet different monsters together and they will not fight
b) Spawn boars and dogs with script - same behaviour

**Expected behavior**

- game_relations.ltx should affect game logics
- with default game relations monsters should fight each other according to relation tables

**Additional context**

I have investigated issue because I thought that problem is with my simulation scripting changes. After debugging C++ I found following:

- I believe it is related to: https://github.com/OpenXRay/xray-16/commit/3dc9f5a846bf637b1f6091df60189c2120864a29#diff-c095d29a70369993326dcccce294233a4ae73a7d180f1e53d62ec074ab59741cR336
- When I remove these lines from net_spawn everything works as expected
- The problem is that inventory owners are not handling switch like:
```
 CSE_ALifeMonsterBase* monster = smart_cast<CSE_ALifeMonsterBase*>(E);
        if (monster)
        {
            MONSTER_COMMUNITY monster_community;
            monster_community.set(pSettings->r_string(*cNameSect(), "species"));

            if (monster_community.team() != 255)
                id_Team = monster_community.team();
        }
```
- Inventory owner code takes effect on going online, which usually just rewrites all settings applied from scripts/spawn logics before it

Solution might be simple, but I have not even tried running CS so knowledge of compatibility nuances is crucial here. 

**Actions needed**

- Fix community initialization for monsters
- When go online, check previous settings and rely on already existing community instead of hardcoded one
- Verify it with COP
- Verify it with CS

**Comment by Xottab-DUTY** [comment]
After looking at the code, I have a question: are monsters don't fight each other in vanilla Clear Sky because of this bug?

I've fixed the bug without introducing special case for Clear Sky support. That could result in monsters begin to fight each other on OpenXRay if they weren't in original X-Ray 1.5.

If something bad happens to Clear Sky we could add a special behaviour for Clear Sky back like this:
```cpp
void CInventoryOwner::SetMonsterCommunity()
{
    CHARACTER_COMMUNITY community;
    community.set("monster", true);
    if (community.index() != NO_COMMUNITY_INDEX)
    {
        if (ClearSkyMode)
            SetCommunity(community.index());
        else
            CharacterInfo().SetCommunity(community.index());
    }
}
```

**Comment by Xottab-DUTY** [comment]
Much thanks for the report!
