### ISSUE TITLE
Unable to compile with malloc (DMEMORY_ALLOCATOR=standard)

### ISSUE THREAD

**Issue by nickbailuc** [Swartz27/xray-16#1461]
Hey guys, sorry for another 'issue', I am having severe memory leaks running the engine on my M1 Mac (running Debian). After about 20 minutes into the game the memory use is over 2 GB and starts to lag heavily (often locks up the computer). I have 8 GB RAM and created a 10 GB swap file, but it seems to hog both of them. Theres something weird about these macs, they require a 16 K page file, and software has to be compatible with that (it ususally is).

Anyways I wanted to try compiling without using `mimalloc` but using the standard `malloc`, but no arguments that I pass allow me to do that, cmake keeps reporting `qUsing mimalloc memory allocator.
```
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_SYSTEM_PROCESSOR: aarch64
-- MASTER_GOLD: ON
-- STATIC_BUILD: ON
-- USE_ADDRESS_SANITIZER: OFF
-- Performing Test GOLD_LINKER_AVAILABLE
-- Performing Test GOLD_LINKER_AVAILABLE - Success
-- Performing Test LLD_LINKER_AVAILABLE
-- Performing Test LLD_LINKER_AVAILABLE - Success
CMake build Release, -Wno-attributes -Wl,--no-undefined 
-- Found OpenGL: /usr/lib/aarch64-linux-gnu/libOpenGL.so   
-- Found GLEW: /usr/include (found version "2.2.0") 
-- Found OpenAL: /usr/lib/aarch64-linux-gnu/libopenal.so  
-- Found JPEG: /usr/lib/aarch64-linux-gnu/libjpeg.so (found version "62") 
-- Found Ogg: /usr/lib/aarch64-linux-gnu/libogg.so  
-- Found Vorbis: /usr/lib/aarch64-linux-gnu/libvorbis.so   
-- Found Theora: /usr/lib/aarch64-linux-gnu/libtheora.so   
-- Found LZO: /usr/lib/aarch64-linux-gnu/liblzo2.so  
Using mimalloc memory allocator
git commit: c8cb6d38a0230733076099c18f4dc179ed5df4c8
git branch: dev
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
rm -f luajit libluajit.a libluajit.so host/minilua host/buildvm lj_vm.S lj_bcdef.h lj_ffdef.h lj_libdef.h lj_recdef.h lj_folddef.h host/buildvm_arch.h jit/vmdef.lua *.o host/*.o *.obj *.lib *.exp *.dll *.exe *.manifest *.pdb *.ilk
-- Configuring done (1.2s)
-- Generating done (0.2s)
-- Build files have been written to: /home/nick/Downloads/xray-16/bin
```

I've tried 
```
DMEMORY_ALLOCATOR=standard cmake ..
DMEMORY_ALLOCATOR=malloc cmake ..
CFLAGS="-DMEMORY_ALLOCATOR=standard" CXXFLAGS="-DMEMORY_ALLOCATOR=standard" cmake ..
```

Has anyone been able to compile with malloc on Linux?

**Comment by Xottab-DUTY** [comment]
If I'm correct, you should pass the setting after the `cmake` command: `cmake .. -DMEMORY_ALLOCATOR=standard`
`-D` is a cmake flag, which accepts the actual setting name after it.


Also talking about the leaks, are you building latest dev branch?

**Comment by nickbailuc** [comment]
> If I'm correct, you should pass the setting after the `cmake` command: `cmake .. -DMEMORY_ALLOCATOR=standard` `-D` is a cmake flag, which accepts the actual setting name after it.
> 
> Also talking about the leaks, are you building latest dev branch?

you were absolutely right, it is because the memalloc flag has to be after `cmake`
I just thought it had to be before as with `CFLAGS="-march=native" CXXFLAGS="-march=native" cmake ..` for example.

However, unfortunately doing it with the standard `malloc` now produces the LuaJIT issue #1296  as with my other ARM laptop during runtime (at compile time theres no errors)


Regarding mem leaks, yes I'm compiling latest `dev` branch (i just do the git pull recurse submodules) but confirmed it in fact automatically pulls the dev branch .


**Question**

I got a 2nd laptop with me i use to monitor memory use of x-ray as well as `dmesg` kernel logs (system loicks up usually when app and cache memory together take over 90% and the kernel reports cpu stall caused by `kswapd0` which is the process that deals with swapping things in and out. Essentailly a lot of cache is loaded into memory and the system freaks out.
The GPU on the M1 has unified RAM&VRAM, but Gallium (or any other Mesa component) doesn't show how much VRAM is being used. 
Is there a way to report VRAM use by the engine itself? I feel like its the video memory that takes up so much space. On average once the renderer loaded a map, itll take just around 1 GB memory (unified/total), but every quickload costs another 30-50MB sometimes 100MB, and it adds up quite fast. Once the memory use exceeds 2GB (minus cache) itll start stuttering, and I can see the kernel starts `kswapd` to dump 500 MB into swap. The process continues, the game can easily exceed 4GB if played for about an hour.


Of course this laptop im using is quite experimental (although luckily the Asahi Linux team works very fast, they just pushed Linux 6.5 yesterday for the M1/M2 macs). Most likely its an OS stability issue more than with open-xray, but I just wanted to see how much of that RAM use is actually Video RAM.

Couple days ago I tried starting it with one of the "dont load textures into ram" kind of options, I think it may have been `-noramtex` (even though it says only for DirectX, maybe it was a different option) and engine consistently only used around 200 MB and change, laggy (of course), but memory use didnt grow from save/load

**Comment by nickbailuc** [comment]
P.S.
I closed the issue because it was the cmake thing, whereas for the memory leaks I'm trying to record and read through logs as much as I can, but at this time not ready to file a proper bug report as I understand so little about the cause, I think it's probably the M1 mac on Linux doing that rather than the engine itself
