### ISSUE TITLE
Support for Alien Logic?

### ISSUE THREAD

**Issue by Noimp1** [Swartz27/xray-16#1494]
Something no one asked for, but it would be cool to see another game in the project being supported...
Alien Logic is the first known game released on the X-Ray Engine, it is a puzzle game set in a far future where player is representing the whole humanity in a IQ contest against other alien species.
It's a abandonware for several years.

**Is your feature request related to a problem? Please describe.**
Because it is a very ancient and possibly modified version of X-Ray Engine (which was being used in the development of S.T.A.L.K.E.R.: Oblivion Lost) it is highly incompatible with modern machines.

**Describe the solution you'd like**
Evaluate the possibility and then proceed. (an advantage is the fact that the assets are open)

**Additional context**
It's purely optional because the game is very boring😴😴😴😴😴

**Comment by Xottab-DUTY** [comment]
Not possible.
1. As far as I know, X-Ray has really changed for S.T.A.L.K.E.R. and is completely different from Alien Logic's X-Ray
2. It's even completely different game,
