### ISSUE TITLE
OpenAL: Can't create sound device on RDP session or audiodriver removed

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1501]
**Describe the bug**
Run remote desktop client over RDP or FreeRDP protocol or other opensource RDP protocols. By default, to optimize network traffic, Windows Audio service is disabled for server remote users.
or
Turn off/plug out cable speakers and disable/remove drivers your audio controller manufacturer (example: realtek high definition audio)

![image](https://github.com/OpenXRay/xray-16/assets/21138600/43aa5ea4-2afe-44bf-a64f-d300a5a1ff2a)

![image](https://github.com/OpenXRay/xray-16/assets/21138600/29a07600-35ce-410d-a724-d324ce786d9b)

**Desktop:**
 - OS server: Windows 10, Windows Server 2022

 - OS client: any OS
 - OpenXRay build version [dfc96a](https://github.com/OpenXRay/xray-16/commit/dfc96a154d1899598d0b2ec4854cd98e10c1e7f7)

**Comment by Xottab-DUTY** [comment]
> OS server:
[Windows 2000](https://ru.wikipedia.org/wiki/Windows_2000) — Windows NT 5.0 (2000)
[Windows XP](https://ru.wikipedia.org/wiki/Windows_XP)[[22]](https://ru.wikipedia.org/wiki/Windows#cite_note-22)[[23]](https://ru.wikipedia.org/wiki/Windows#cite_note-23)[[24]](https://ru.wikipedia.org/wiki/Windows#cite_note-24)[[25]](https://ru.wikipedia.org/wiki/Windows#cite_note-25) — Windows NT 5.1 (2001)
[Windows XP 64-bit Edition](https://ru.wikipedia.org/wiki/Windows_XP_64-bit_Edition) — Windows NT 5.2 (2003)
[Windows Server 2003](https://ru.wikipedia.org/wiki/Windows_Server_2003) — Windows NT 5.2 (2003)
[Windows XP Professional x64 Edition](https://ru.wikipedia.org/wiki/Windows_XP_Professional_x64_Edition) — Windows NT 5.2 (2005)
[Windows Home Server](https://ru.wikipedia.org/wiki/Windows_Home_Server) — Windows NT 5.2 (2007)
[Windows Vista](https://ru.wikipedia.org/wiki/Windows_Vista) — Windows NT 6.0 (2007)
[Windows Server 2008](https://ru.wikipedia.org/wiki/Windows_Server_2008) — Windows NT 6.0 (2008)
[Windows Small Business Server](https://ru.wikipedia.org/wiki/Windows_Small_Business_Server) — Windows NT 6.0 (2008)
[Windows 7](https://ru.wikipedia.org/wiki/Windows_7)[[26]](https://ru.wikipedia.org/wiki/Windows#cite_note-26)[[27]](https://ru.wikipedia.org/wiki/Windows#cite_note-27) — Windows NT 6.1 (2009)
[Windows Server 2008 R2](https://ru.wikipedia.org/wiki/Windows_Server_2008_R2) — Windows NT 6.1 (2009)
[Windows Home Server 2011](https://ru.wikipedia.org/wiki/Windows_Home_Server_2011) — Windows NT 6.1 (2011)
[Windows 8](https://ru.wikipedia.org/wiki/Windows_8)[[28]](https://ru.wikipedia.org/wiki/Windows#cite_note-28)[[29]](https://ru.wikipedia.org/wiki/Windows#cite_note-29)[[30]](https://ru.wikipedia.org/wiki/Windows#cite_note-30)[[31]](https://ru.wikipedia.org/wiki/Windows#cite_note-31)[[32]](https://ru.wikipedia.org/wiki/Windows#cite_note-32)[[33]](https://ru.wikipedia.org/wiki/Windows#cite_note-33) — Windows NT 6.2 (2012)
[Windows Server 2012](https://ru.wikipedia.org/wiki/Windows_Server_2012) — Windows NT 6.2 (2012)
[Windows 8.1](https://ru.wikipedia.org/wiki/Windows_8.1)[[34]](https://ru.wikipedia.org/wiki/Windows#cite_note-34) — Windows NT 6.3 (2013)
[Windows Server 2012 R2](https://ru.wikipedia.org/wiki/Windows_Server_2012#Windows_Server_2012_R2) — Windows NT 6.3 (2013)
[Windows 10](https://ru.wikipedia.org/wiki/Windows_10)[[35]](https://ru.wikipedia.org/wiki/Windows#cite_note-35)[[36]](https://ru.wikipedia.org/wiki/Windows#cite_note-36)[[37]](https://ru.wikipedia.org/wiki/Windows#cite_note-37)[[38]](https://ru.wikipedia.org/wiki/Windows#cite_note-38) — Windows NT 10.0 (2015)[[39]](https://ru.wikipedia.org/wiki/Windows#cite_note-:0-39)[[40]](https://ru.wikipedia.org/wiki/Windows#cite_note-:1-40)[[41]](https://ru.wikipedia.org/wiki/Windows#cite_note-:2-41)
[Windows Server 2016](https://ru.wikipedia.org/wiki/Windows_Server_2016) — Windows NT 10.1 (2016)
[Windows Server 2019](https://ru.wikipedia.org/wiki/Windows_Server_2019) — Windows NT 10.2 (2019)
[Windows 11](https://ru.wikipedia.org/wiki/Windows_11) — Windows NT 10.0.22000 (2021)
[Windows Server 2022](https://ru.wikipedia.org/wiki/Windows_Server_2022) — Windows NT 10.3 (2021)

Don't shitpost with this entire OS list. You don't have these. You should post only **your** OS.

**Comment by GermanAizek** [comment]
@Xottab-DUTY fix it.
