### ISSUE TITLE
OpenAL: Can't create sound device if there are no audio devices (without speakers)

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1502]
**Describe the bug**
Turn off/plug out cable speakers and disable/remove drivers your audio controller manufacturer (example: realtek high definition audio)

![image](https://github.com/OpenXRay/xray-16/assets/21138600/43aa5ea4-2afe-44bf-a64f-d300a5a1ff2a)

![image](https://github.com/OpenXRay/xray-16/assets/21138600/29a07600-35ce-410d-a724-d324ce786d9b)

**Desktop:**
 - OS: Windows 10
 - OpenXRay build version [dfc96a](https://github.com/OpenXRay/xray-16/commit/dfc96a154d1899598d0b2ec4854cd98e10c1e7f7)

**Comment by Xottab-DUTY** [comment]
It may seem different, but in fact, it's identical to #1501.
