### ISSUE TITLE
xrEngine does can't how to scan entire root folder game and internal directories

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1503]
**Describe the bug**
Engine does not know how to check fsgame.ltx file above directory or in root game folder.

![image](https://github.com/OpenXRay/xray-16/assets/21138600/af090f6f-2d92-46cf-933e-93038bc783b3)

**Desktop (please complete the following information):**
 - OS: any
 - OpenXRay build version [dfc96a](https://github.com/OpenXRay/xray-16/commit/dfc96a154d1899598d0b2ec4854cd98e10c1e7f7)

**Comment by Xottab-DUTY** [comment]
Not a bug. Stop creating issues, fix previous issues opened by you.
