### ISSUE TITLE
There is no way to select r2.5 running using PowerShell

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1527]
**Describe the bug**
PowerShell separates dot as another parameter, in default cmd.exe there is no such problem.

**Screenshots**
![image](https://github.com/OpenXRay/xray-16/assets/21138600/ccda9ea5-006b-4438-9bbc-344e64d23e8c)

In log result:
```
OpenXRay Mixed build 9048, Nov 15 2023 (Windows 64-bit, shared)
Custom build from commit[7dc09604acc59df42260a0cb11c58d4b03901a74] branch[fix-numa]
 
command line -fsltx D:\cop\fsgame.ltx -r2 .5

* CPU features: RDTSC, MMX, SSE, AVX
* CPU threads: 8

Initializing File System...
$fs_root$ = D:\cop\
using fs-ltx D:\cop\fsgame.ltx
FS: 25933 files cached 26 archives, 20Kb memory used.
Init FileSystem 0.267824 sec
-----loading d:\cop\gamedata\configs\system.ltx
-----loading d:\cop\gamedata\configs\system.ltx
Starting INPUT device...
Loading module: xrRender_R1
Loading module: xrRender_R2
Loading module: xrRender_R4
Loading module: xrRender_GL
Loading module: d3d9
refCount:pD3D 1
m_buffers_list.size() = 0
Loading module: d3d9
refCount:pD3D 1
m_buffers_list.size() = 0
Loading module: dxgi
Loading module: d3d11
* GPU [vendor:1414]-[device:8C]: Microsoft Basic Render Driver
* CREATE: DeviceREF: 3
*   Texture memory: 0 M
refCount:m_pSwapChain 1
refCount:pContext 1
refCount:pContext 1
refCount:pContext 1
refCount:pContext 1
refCount:pContext 1
refCount:pDevice: 1
refCount:m_pAdapter 1
refCount:m_pFactory 1
m_buffers_list.size() = 0
Available render modes[7]:
renderer_r1
renderer_r2a
renderer_r2
renderer_r2.5
renderer_r3
renderer_r4
renderer_rgl
Selected renderer: renderer_r2
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OpenXRay build version [[7dc0960](https://github.com/OpenXRay/xray-16/commit/8ff7b671369cdfbc44d203923966602f2bba10fc)]

**Comment by Xottab-DUTY** [comment]
Can you use quotes ""?

**Comment by Xottab-DUTY** [comment]
> Can you use quotes ""?

Hey, answer the question ple

**Comment by Xottab-DUTY** [comment]
> Can you use quotes ""?

@GermanAizek, hey! What's your answer?

**Comment by GermanAizek** [comment]
> @GermanAizek, hey! What's your answer?

Why not just rename to r2_5 for better compatibility with cmd, powershell, vbscript and [COMMAND.COM](https://en.wikipedia.org/wiki/COMMAND.COM)?

**Comment by Xottab-DUTY** [comment]
> > @GermanAizek, hey! What's your answer?
> 
> Why not just rename to r2_5 for better compatibility with cmd, powershell, vbscript and [COMMAND.COM](https://en.wikipedia.org/wiki/COMMAND.COM)?

1. It doesn't have problems with cmd.
2. There's no problem change that really, but we can just use quotes, isn't it? If so, I don't want to change the vanilla key (to stay compatible with vanilla engine).
