### ISSUE TITLE
Engine incorrectly selects renderer without manually editing user.ltx

### ISSUE THREAD

**Issue by GermanAizek** [Swartz27/xray-16#1537]
**Describe the bug**
By default, without user.ltx config, system starts r2 renderer, but r2 maybe does not work, only r3 and r4 are available or old GPUs only r1 renderer. Why doesn't engine automatically select a working renderer from all possible ones?

**Desktop (please complete the following information):**
 - OS: any
 - OpenXRay build version [[4fe8751](https://github.com/OpenXRay/xray-16/commit/4fe8751425dfb21eabf2eedc04b6526022b4bb6f)]

**Comment by GermanAizek** [comment]
https://github.com/OpenXRay/xray-16/issues/1528

on my configuration works only r3 and r4, engine does not start without manually fixing parameter in user.ltx or -r3 -r4 key in commandline

**Comment by Xottab-DUTY** [comment]
Thanks for report!
DX9 renderers now won't be selected if d3dx9_31.dll is unavailable.
