### ISSUE TITLE
Game broken in Windows. Portable build is missing system.ltx. The system.ltx and the folders gamedata\config\ are in root instead of bin.

### ISSUE THREAD

**Issue by ghost** [Swartz27/xray-16#1562]
**Describe the bug**
When trying to launch C:\Games\OpenXRay\bin\xrEngine.exe it says it can't find the file fsgame.ltx. 
This file is in the root folder, not in bin, and, moving it to bin, makes the game spit a new unresolvable error.

Now, the game wants OpenXRay\bin\gamedata\config\system.ltx
gamedata\config in in root instead of bin
system.ltx isn't anywhere. Not in root, nor in subfolders

**To Reproduce**
1. Extract files anywhere
2. Go to OpenXRay\bin\ and execute xrEngine.exe
3. First error asking for fsgame.ltx appears
4. Copy fsgame.ltx from \OpenXRay to \OpenXRay\bin and second error appears.

**Expected behavior**
The game should start

**Screenshots, videos**
![image](https://github.com/OpenXRay/xray-16/assets/130172696/c0dc4e0a-8933-4676-abff-a4f2c8caf9f7)
![image](https://github.com/OpenXRay/xray-16/assets/130172696/4d719c56-a97d-4762-bb6a-471626337004)

**BugTrap error report**
OpenXRay Rx64 build 7988, Dec 20 2020
AppVeyor build 822 from commit[edbaac6c3639077e89f4e568145489630c2ce41c] branch[HEAD] (built by OpenXRay)
 
command line 

* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSE4.1, SSE4.2, AVX, AVX2
* CPU cores/threads: 12/12
* CPU0 current freq: 2592 MHz, max freq: 2592 MHz
* CPU1 current freq: 2592 MHz, max freq: 2592 MHz
* CPU2 current freq: 2592 MHz, max freq: 2592 MHz
* CPU3 current freq: 2592 MHz, max freq: 2592 MHz
* CPU4 current freq: 2592 MHz, max freq: 2592 MHz
* CPU5 current freq: 2592 MHz, max freq: 2592 MHz
* CPU6 current freq: 2592 MHz, max freq: 2592 MHz
* CPU7 current freq: 2592 MHz, max freq: 2592 MHz
* CPU8 current freq: 2592 MHz, max freq: 2592 MHz
* CPU9 current freq: 2592 MHz, max freq: 2592 MHz
* CPU10 current freq: 2592 MHz, max freq: 2592 MHz
* CPU11 current freq: 2592 MHz, max freq: 2592 MHz

Initializing File System...
$fs_root$ = C:\Games\OpenXRay\bin
using fs-ltx fsgame.ltx
FS: 76 files cached 0 archives, 4188Kb memory used.
Init FileSystem 0.006735 sec
-----loading c:\games\openxray\bin\gamedata\configs\system.ltx

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenXRay build version: 7988, Dec 20 2020

**Additional context**
Project looks cool. It'd be a lot cooler if it worked, thou.

**Comment by Hrusteckiy** [comment]
Dude, run the game from game root. Just set game root as working directory in your `.lnk` file.

**Comment by ghost** [comment]
> Dude, run the game from game root. Just set game root as working directory in your `.lnk` file.

And where is that file? It's not in the OpenXRay folder, nor in it's subfolders. I just checked manually. 
Also, please take note that I said I am using the Portable build, therefore, I did not compiled from source.

And you should also pay attention to the fact that I said the game demands a file that isn't anywhere to be found. Yes, I did check each folder manually.

Althou, perhaps I have made a mistake. Taking into account how light this folder is, do I need the original game? Perhaps I misunderstood that this is a standalone app, when in reality it's just a mod.

**Comment by ghost** [comment]
I thought the game was necessary only for compiling, since I didn't scrolled down when downloading the precompiled build.
It is a mod, and it requires the original game. It isn't standalone yet.
