### ISSUE TITLE
Clear Sky crash at start

### ISSUE THREAD

**Issue by donizettilorenzo** [Swartz27/xray-16#1566]
Just using the lastest Nightly Build and the related package (2020-2021, maybe it must be updated?)

_FATAL ERROR
 
[error] Expression    : back_exist
[error] Function      : CUIFrameLineWnd::InitTexture
[error] File          : D:\a\xray-16\xray-16\src\xrUICore\Windows\UIFrameLineWnd.cpp
[error] Line          : 43
[error] Description   : ui_inGame2_edit_box_1_

**Comment by Xottab-DUTY** [comment]
I guess, special gamedata for Clear Sky is missing?

**Comment by donizettilorenzo** [comment]
No, it is there ( *the related package* )

**Comment by donizettilorenzo** [comment]
Any update for the CS gamedata package so I can test the new OXR builds? Thanks!

**Comment by donizettilorenzo** [comment]
OK, found the culprit: xpatch_openxray_plus not removed from "patches"

**Comment by Xottab-DUTY** [comment]
I guess, this can be closed now.
