### ISSUE TITLE
The game launches on the second screen in a multi-screen system.

### ISSUE THREAD

**Issue by SsSAtonioSsS** [Swartz27/xray-16#1588]
The engine from December 2021 RC1 runs the game on the second monitor and ignores the primary monitor.
In OpenXRay engine (build 558) there was no such problem.
How do I switch monitors for display?

**Comment by Xottab-DUTY** [comment]
December 2021 RC1 release has work-in-progress functionality for screen management.

1. In main menu, press Alt+Win, then press LMB on the game screen and just move it to your main monitor.
2. Open console and type `vid_monitor`, select your main monitor and press enter to select, then press enter to submit the command.
3. Type `vid_restart` and that should realign the window to the main monitor.
