### ISSUE TITLE
Segfault in CGamePersistent::RegisterModel

### ISSUE THREAD

**Issue by Zenitur** [Swartz27/xray-16#1605]
Здравствуйте. Я могу по-русски написать, вы не против? Спасибо.

В октябре 2009 года состоялся выпуск двух программных продуктов, это Ubuntu 9.10 и Сталкер: Зов Припяти. Я играл в него в Ubuntu и мечтал, что когда-нибудь разработчики выпустят нативную Linux-версию. Что ж, прошло 15 лет, пришло время ~~переустанавливать шиндовс~~ исполнять мечту.

Чтобы установить драйвер amdgpu, надо обновить ядро, libdrm и mesa, а также установить тяжеленный компилятор llvm. Боюсь, что я так затрахаюсь, что у меня не хватит сил поиграть. Поэтому я установил драйвер fglrx 15.12.

Запускаю игру и... она работает. Я даже удивился, что, спустя столько лет, это возможно.

Однако она падает при нажатии "новая игра", "выберите уровень сложности".

Логи тут:
[openxray_zenitur.log](https://github.com/OpenXRay/xray-16/files/14234024/openxray_zenitur.log)
[fglrx-15-12-glxinfo.txt](https://github.com/OpenXRay/xray-16/files/14234041/fglrx-15-12-glxinfo.txt)

Скрин тут:
![Screenshot-Stalker-COP-on-Ubuntu-9-10](https://github.com/OpenXRay/xray-16/assets/3435752/44c5f518-79a9-4455-b946-ee43fc95938b)

Сборка тут:
[S.T.A.L.K.E.R. - Call of Pripyat (Linux x86_64 build 07.14.2023).zip](https://github.com/OpenXRay/xray-16/files/14234005/S.T.A.L.K.E.R.-.Call.of.Pripyat.Linux.x86_64.build.07.14.2023.zip)

**Comment by Xottab-DUTY** [comment]
fglrx тут не причём, это видео-драйвер, а, согласно логу, вылет происходит чисто в игровой части движка при загрузке модели рук игрока.

Это похоже на вылет, который происходит на бинарниках, собранных клангом.
Чем собран движок? Его можно собрать клангом, но стабильность не гарантируется. Лучше собирать GCC.

**Comment by Zenitur** [comment]
Движок собран GCC 9.1. Кланг... Ну, могу конечно собрать. Версия 7.0 пойдёт?

P.S. Если будешь смотреть сборку - там бинарники strip-нутые. Могу с отладочными символами выложить.

**Comment by Xottab-DUTY** [comment]
> Кланг... Ну, могу конечно собрать.

Не надо, я же говорю, им наоборот и не нужно собирать :)

**Comment by Zenitur** [comment]
Проблема вряд ли в коде рук. На более новой системе, с драйвером AMDGPU, эта же сборка работает.

**Comment by Xottab-DUTY** [comment]
> Проблема вряд ли в коде рук. На более новой системе, с драйвером AMDGPU, эта же сборка работает.

Драйвера на видеокарту здесь не причём. Валится код загрузки моделей.
Похоже, что здесь та же самая проблема как и в #1224.

Если это действительно так. то баг мог быть исправлен в свежих коммитах и следует собирать именно их.
Но, судя по всему, пришлось собирать со старых коммитов из-за #1595. Что ж, тогда ждём исправления сборки со старым SDL2 на самых новых коммитах.

**Comment by Xottab-DUTY** [comment]
Так как #1595 исправлен, то этот Issue теперь уже, скорее, дубликат #1224, так что закрываю.
Можно открыть заново в случае новых проблем или создать новый Issue.
