### ISSUE TITLE
Cannot use the letter Y in the name of a save file

### ISSUE THREAD

**Issue by Gold-Vibes** [Swartz27/xray-16#1614]
**Describe the bug**
Trying to create a save file in the game using the December 2021 RC1 version of the OpenXray engine doesn't let you use the letter Y. 

**To Reproduce**
1. Fresh install of Call of Pripyat from GOG on Windows 10 Pro under C:\Games
2. Download the latest stable version and extract the archive for December 2021 RC1 from the link under [https://github.com/OpenXRay/xray-16/wiki/[EN]-How-to-install-and-play](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-install-and-play) (Which was followed from https://github.com/OpenXRay/xray-16 section "Install and Play")
3. Copy all files to the game root directory as stated in the instructions
4. Accept the overwriting of fsgame.lxt
5. Run Stalker-COP.exe as stated in the instructions
6. Create a new game using a renderer setting that will load without crashing 
7. Hit the Escape key then left-click to Save Game
8. Type in the name of the save file you want that includes the letter  y 
9. Game incorrectly interprets the letter y on the keyboard as if the user clicked the lower button to accept the file name and save the file to the hard drive

**Expected behavior**
I expect to be able to name a save game file with any English letters with the possibility of using spaces and numbers before accepting the name and having the game engine create a save file with the name I typed (I don't know the naming restrictions regarding numbers/symbols/dashes etc. off hand and it is late). I expect the following names to be valid:
abcxyz
thy
year
why
Yolo 

**Screenshots, videos**
The image is at https://imgur.com/MvXySR8 which is a part of a few sessions of testing the OpenXray engine.

**BugTrap error report**
No crashes

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - OpenXRay build December 2021 RC1

**Additional context**
This was an error found while troubleshooting/testing other problems which can be found at https://imgur.com/a/uIK67q9. As soon as I typed the y key the game would accept the filename and return to the main menu.

**Comment by AMS21** [comment]
![Screenshot_20240216_150814](https://github.com/OpenXRay/xray-16/assets/19614997/aab026f1-549e-4c7a-95a6-7bf13286e4b9)
Cannot reproduce on `Linux 6.7.0-0-MANJARO x86_64` built from 92c550c591a57491371e7b8d3d3494d4224a9c38

Also the build you're using is pretty old so it might be fixed already or a windows specific bug.

Could you please check with the latest [nightly](https://github.com/OpenXRay/xray-16/releases/tag/latest-nightly) version if the issue still exists there?

**Comment by Xottab-DUTY** [comment]
I can't reproduce it on Windows too.
If I remember correctly, this was reported somewhere in 2021-2023 and was fixed in 2022-2023.

**Comment by Gold-Vibes** [comment]
> ![Screenshot_20240216_150814](https://private-user-images.githubusercontent.com/19614997/305442493-aab026f1-549e-4c7a-95a6-7bf13286e4b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMjM5NDYsIm5iZiI6MTcwODEyMzY0NiwicGF0aCI6Ii8xOTYxNDk5Ny8zMDU0NDI0OTMtYWFiMDI2ZjEtNTQ5ZS00YzdhLTk1YTYtN2JmMTMyODZlNGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDIyNDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkN2U1NTk2MTVlMzJiNmZiZGIxYmRlNTAzMzcwODY4ZGFmZWQzZmJiMGE2YWZkZDc3NTMxN2IxZjEwNDQzNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmukIM0MSD0GXwPnnzmKd8iNCkzbPFpdh9CFq1Ht5eI) Cannot reproduce on `Linux 6.7.0-0-MANJARO x86_64` built from [92c550c](https://github.com/OpenXRay/xray-16/commit/92c550c591a57491371e7b8d3d3494d4224a9c38)
> 
> Also the build you're using is pretty old so it might be fixed already or a windows specific bug.
> 
> Could you please check with the latest [nightly](https://github.com/OpenXRay/xray-16/releases/tag/latest-nightly) version if the issue still exists there?

Which naming would be the proper nightly release to try? 
I don't know the difference in features and stability between: 

OpenXRay.Release.64-bit.7z 
OpenXRay.Release.Master.Gold.64-bit.7z 

Are nightly releases considered stable enough? 

Thank you for your help!

**Comment by Xottab-DUTY** [comment]
> > ![Screenshot_20240216_150814](https://private-user-images.githubusercontent.com/19614997/305442493-aab026f1-549e-4c7a-95a6-7bf13286e4b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMjM5NDYsIm5iZiI6MTcwODEyMzY0NiwicGF0aCI6Ii8xOTYxNDk5Ny8zMDU0NDI0OTMtYWFiMDI2ZjEtNTQ5ZS00YzdhLTk1YTYtN2JmMTMyODZlNGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDIyNDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkN2U1NTk2MTVlMzJiNmZiZGIxYmRlNTAzMzcwODY4ZGFmZWQzZmJiMGE2YWZkZDc3NTMxN2IxZjEwNDQzNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmukIM0MSD0GXwPnnzmKd8iNCkzbPFpdh9CFq1Ht5eI) Cannot reproduce on `Linux 6.7.0-0-MANJARO x86_64` built from [92c550c](https://github.com/OpenXRay/xray-16/commit/92c550c591a57491371e7b8d3d3494d4224a9c38)
> > Also the build you're using is pretty old so it might be fixed already or a windows specific bug.
> > Could you please check with the latest [nightly](https://github.com/OpenXRay/xray-16/releases/tag/latest-nightly) version if the issue still exists there?
> 
> Which naming would be the proper nightly release to try? I don't know the difference in features and stability between:
> 
> OpenXRay.Release.64-bit.7z OpenXRay.Release.Master.Gold.64-bit.7z
> 
> Are nightly releases considered stable enough?
> 
> Thank you for your help!

[Installation instructions page](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-install-and-play) has the links to nightly builds and proper naming that is easy to understand!
Basically, `Release` is version for modmakers and `Release Master Gold` is version for players, I suggest you choose the latter.

Yes, nightly builds are considered stable. Though, I'm unsure if it has bugs that are unknown to us yet. We are currently stabilizing the branch and searching for bugs to fix.

**Comment by hfrox** [comment]
Having this bug compiled on pop os 24.04 following the instructions latest build (OpenXRay Release Master Gold build 9396, Oct 29 2024)
