### ISSUE TITLE
Game crashes due to "SOUND: Invalid emitter state"

### ISSUE THREAD

**Issue by antoncxx** [Swartz27/xray-16#1627]
**Describe the bug**
Game crashes when firing a weapon.

**To Reproduce**

It is difficult to say the exact steps to reproduce this, but from my observation the crash occurs when firing a weapon. You might need to fire couple of magazines for the crush to happen.

**Expected behavior**
Game works without crashing.

**Screenshots, videos**

**BugTrap error report**
[OpenXRay_error_report_240305-225049.zip](https://github.com/OpenXRay/xray-16/files/14504609/OpenXRay_error_report_240305-225049.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenXRay build version: dev 04a805a5b49e0257e37440101b4406a1ab0a70e9
 - STALKER COP, no mods

**Additional context**
The error window, that pops up does not block the main thread.

**Comment by Xottab-DUTY** [comment]
I just pushed a commit to address the issue.
@antoncxx, @LOyoujoLI, @yohjimane, please test if it's actually fixed!

**Comment by Xottab-DUTY** [comment]
Oh, I just catched this crash after the fix. Not fixed.

**Comment by Xottab-DUTY** [comment]
Now it's fixed. Thanks for reporting the issue!
