### ISSUE TITLE
AppVeyor linux builds

### ISSUE THREAD

**Issue by YALdysse** [Swartz27/xray-16#1630]
Please, create Linux builds on AppVeyor.

**Comment by Xottab-DUTY** [comment]
You can download precompiled Linux builds from [GitHub Actions](https://github.com/OpenXRay/xray-16/actions/workflows/cibuild.yml?query=branch%3Adev).
Finding a download link is quite almost the same as with AppVeyor.
Please, tell me if you need a guidance here!

AppVeyor builds were broken for about half of a year or more, and after update on AppVeyor side I couldn't get any clue how to fix them, so I just removed them.
Moreover, we plan to remove discontinue using AppVeyor anyway. GitHub Actions has all we need.
