### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by MANDYLA89** [Swartz27/xray-16#1634]
xrEngine.exe caused BREAKPOINT in module "C:\Games\STALKER Mason's story 2.0\bin\xrCore.dll" at 0033:00007FFB309F3D03, xrDebug::Fail()+659 byte(s)

**Comment by Xottab-DUTY** [comment]
Пожалуйста, всегда скидывайте полный лог.
Эта строчка ничего не даёт.

**Comment by Xottab-DUTY** [comment]
Закрыл, т.к. оформлено не по форме Bug report. Тут не то что архива с баг-репортом нет, даже лога нет.
