### ISSUE TITLE
Fatal Error. SOUND: Invalid emitter state

### ISSUE THREAD

**Issue by ioshevchenko** [Swartz27/xray-16#1640]
**Describe the bug**
При переходе на аномалию "Котел" происходит вылет игры. Также происходит вылет при перестрелке (Например на лесопилке)

**Expected behavior**
Спокойное прохождение.

**Screenshots, videos**
[Видео](https://youtu.be/SntTd4gxMAw)

**BugTrap error report**
[OpenXRay_error_report_240322-175813.zip](https://github.com/OpenXRay/xray-16/files/14724362/OpenXRay_error_report_240322-175813.zip)
[OpenXRay_error_report_240322-183924.zip](https://github.com/OpenXRay/xray-16/files/14724879/OpenXRay_error_report_240322-183924.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenXRay dev branch

**Comment by Xottab-DUTY** [comment]
Спасибо, починил!
