### ISSUE TITLE
Multiple issues regarding the Fullscreen/ Windowed modes

### ISSUE THREAD

**Issue by OwlCacone** [Swartz27/xray-16#1647]
1) When using Windowed Borderless the game starts in a black screen with what look like horizontal slices of pixels appearing and disappearing in milliseconds. These "horizontal slices" seem to be the intended picture - a cinematic, gameplay, or the main menu - appearing underneath a layer of the black screen. 
Pressing Alt + Enter fixes it. 
Every menu, is still usable, the game still responds to commands.
Alt + Tabbing out, and back into the game results in a permanent black screen until force quitting in this mode.
Vertical Sync does not work in this mode, with the Alt + Enter "fix"

2) Setting the mode to Fullscreen results in the game brightness dimming slightly and flickering non-stop. Pressing Alt + Enter fixes this flicker, but caps the framerate at ~30.

3) Setting the mode to Fullscreen (Fast Alt + Tabbing) results in a hard crash as soon as the setting is applied.

-------------------------------------------------------------------------------------------------------------------------------------------------

Steps to reproduce the behavior for issue 1):
1. Enter the settings menu
2. Select "Windowed Borderless" as the current Window Mode
3. Click "Apply"
4. Restart the game
5. See error

Steps to reproduce the behavior for issue 2):
1. Enter the settings menu
2. Select "Fullscreen" as the current Window Mode
3. Click "Apply"

Steps to reproduce the behavior for issue 3):
1. Enter the settings menu
2. Select "Fullscreen (Fast Alt + Tabbing)" as the current Window Mode
3. Click "Apply"
*Booting with this setting enabled launches the game in a "normal" state, but also informs the user of a crash via the BugTrap pop-up window.

-------------------------------------------------------------------------------------------------------------------------------------------------

All of the Window Modes should result in a clear image, with no crashes relating to them, or changes in visual tearing/ framerate

Unfortunately, my recording software is being uncooperative and as such I am unable to record these issues visually

A zip file containing the error report - regarding Issue 3) - is attached\
[OpenXRay_error_report_240402-062554.zip](https://github.com/OpenXRay/xray-16/files/14831054/OpenXRay_error_report_240402-062554.zip)

 - OS: W11 (Version 22H2)
 - GPU: AMD Radeon RX 7600 (Driver version 24.3.1)
 - OpenXRay Release Master Gold build 9185, Apr  1 2024

This build was running in conjunction with the newly released OpenXRay Gunslinger mod, which only supports R4 (DX11) as the renderer at this time. The renderer might be causing a portion of the issues listed.

**Comment by Xottab-DUTY** [comment]
@OwlCacone, according to user.ltx in the crash report, you use 1920x1080 resolution. Is it native (maximal) resolution of your monitor?

I can't reproduce that on my PC with basic OpenXRay, also the report file is from OpenXRay Gunslinger.
There might be some issues with basic OpenXRay as well, but it also might be specific to OpenXRay Gunslinger.
@yohjimane, any thoughts?

**Comment by yohjimane** [comment]
@Xottab-DUTY Yeah, i chatted with someone else who was seeing this bug- they couldn't repro on base OXR, so I'm thinking I maybe messed something up...

**Comment by OwlCacone** [comment]
@Xottab-DUTY Yes, native res is 1920x1080. I have not used base OXR, so it's likely something to do with the fork for Gunslinger
