### ISSUE TITLE
Regression: Crash on launch - SoundRender_Source.cpp

### ISSUE THREAD

**Issue by shinra-electric** [Swartz27/xray-16#1654]
**Describe the bug**
Crash on launch after commit [5567727](https://github.com/OpenXRay/xray-16/commit/55677278859941f703c1ddee1f5f9715631f5f63). 

The issue is `Invalid max distance`  in the assert on line 254 of `SoundRender_Source.cpp`
`m_info.maxAIDist >= 0.1f && m_info.maxDist >= 0.1f`

**To Reproduce**
Launch game

**BugTrap error report**
[openxray_crash.log](https://github.com/OpenXRay/xray-16/files/14915634/openxray_crash.log)

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1 Sonoma
 - OpenXRay build version - built from dev branch

**Comment by Xottab-DUTY** [comment]
Thanks!
