### ISSUE TITLE
Error reading Attributes. gameplay\info_jupiter.xml

### ISSUE THREAD

**Issue by Citrodata** [Swartz27/xray-16#1663]
**Describe the bug**
The game just crashes when starting and also doesn't really stop and just takes up system resources.

**To Reproduce**
1. Start the game on linux.
Command used: `LD_LIBRARY_PATH="./bin:$LD_LIBRARY_PATH" ./bin/xr_3da -fsltx ./fsgame.ltx`

**BugTrap error report**
[openxray_max.log](https://github.com/OpenXRay/xray-16/files/15143067/openxray_max.log)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - OpenXRay: master

**Additional context**
Im using the German Steam version of the game.

**Comment by Xottab-DUTY** [comment]
> -fsltx ./fsgame.ltx

You must use full absolute path to fsgame.ltx. Some parts of the engine correctly determine what `./` means, but some don't.
Please, tell us if the issue is fixed with the absolute path or not!

**Comment by Citrodata** [comment]
Okay i fixed with changing the game_mode option.
Now im just getting this error

```
Cannot find file \home\me\.games\openxray\gamedata\config\system.ltx.
Reinstalling application may fix this problem.
```
But i have it there.
Currently trying with the gog version.

**Comment by Xottab-DUTY** [comment]
> Okay i fixed with changing the game_mode option. Now im just getting this error

What game are you running? And why you didn't told it in the first place!!11

> ```
> Cannot find file \home\me\.games\openxray\gamedata\config\system.ltx.
> Reinstalling application may fix this problem.
> ```
> 
> But i have it there. Currently trying with the gog version.

From what I can see here, the path contains `config` folder, which corresponds to Shadow of Chernobyl (Clear Sky and Call of Pripyat uses `configs` folder).
This game is not supported by OpenXRay.

**Comment by Xottab-DUTY** [comment]
@Citrodata, so, did you tried to launch Shadow of Chernobyl, or I was wrong it you tried different game? If so, were you able to fix the issue?

**Comment by Citrodata** [comment]
I tried it with Shadow of Chernobyl.
It worked with other games, so sorry to bother.
