### ISSUE TITLE
Engine for Nintendo Switch

### ISSUE THREAD

**Issue by artslay** [Swartz27/xray-16#1669]
Возможно ли собрать движок под Nintendo Switch? Его уже запускали на L4T (Ubuntu под Switch), но можно ли собрать его как файл .nro используя [deko3d](https://github.com/devkitPro/deko3d) и [libnx](https://github.com/switchbrew/libnx) при помощи [devkitA64](https://devkitpro.org/wiki/Getting_Started)?

**Comment by Xottab-DUTY** [comment]
Ввиду того, что мы базируемся на оригинальном движке X-Ray и позиция GSC компании пока непрозрачна, а Nintendo Switch это коммерческий продукт, то мы даже пробовать не будем в консоли лезть.

Плюс, на текущий момент устройство рендера не позволяет удобно добавлять поддержку графических API, поэтому deko3d добавит проблем)

**Comment by xfreshx** [comment]
@artslay я собирал и запускал, но сразу уперся в кучу вещей несовместимых со Switch. Конечно сейчас, после официального релиза эта задача, вероятно, утратила актуальность, но ниже список того, с чем предстоит разобраться, если такое желание появится:

1. Статическая сборка проекта, т.к. Switch не умеет в динамические библиотеки
2. Отсутсвие mmap/munmap в ядре HorizonOS заставляет написать альтернативу
3. Рендерер надо переделать, потому что Switch поддерживает только одно окно, в то время как openxray сразу создает несколько и меняет их за кадром
4. Куча мелких вещей в виде разного рода зависимостей, которые надо пересобрать под aarch64 мспользуя devkitPro тулчейн. 

Мой заброшеный подход к снаряду находится здесь, за 3 года он безнадежно устарел: https://github.com/xfreshx/xray-16
