### ISSUE TITLE
latest b40433b19 threads fix not run 

### ISSUE THREAD

**Issue by johndoe71rus** [Swartz27/xray-16#1670]
**Describe the bug**

**To Reproduce**
1. build b40433b19 
2. run CoP
3. Get FATAL ERROR

**BugTrap error report**
[openxray_johndoe.log](https://github.com/OpenXRay/xray-16/files/15285677/openxray_johndoe.log)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4]
 - OpenXRay build version b40433b19

ps. кажется сообщения в дискорд не пропускает

**Comment by johndoe71rus** [comment]
commit[5770e20cff04b3f96f972b7eb08dd0f8c72b6b0c] branch[dev]
успешно запускается 
[openxray_johndoe.log](https://github.com/OpenXRay/xray-16/files/15285730/openxray_johndoe.log)

**Comment by Xottab-DUTY** [comment]
Починил, спасибо!

**Comment by johndoe71rus** [comment]
судя по фиксу ifdef XR_PLATFORM_WINDOWS таски в линукс мак не завезли пока?

**Comment by Xottab-DUTY** [comment]
> судя по фиксу ifdef XR_PLATFORM_WINDOWS таски в линукс мак не завезли пока?

Нет. Это ограничения самих платформ: на винде можно в любом потоке создавать окна, на маке только в основном, под линуксом либо тоже самое, либо зависит от использования иксов или Wayland (не уверен, может от чего-то другого зависеть).

**Comment by johndoe71rus** [comment]
не починил, чини еще 
[openxray_johndoe.log](https://github.com/OpenXRay/xray-16/files/15285923/openxray_johndoe.log)

**Comment by Xottab-DUTY** [comment]
> не починил, чини еще [openxray_johndoe.log](https://github.com/OpenXRay/xray-16/files/15285923/openxray_johndoe.log)

Запустишь через GDB?

**Comment by johndoe71rus** [comment]
вспомнить бы как...

**Comment by johndoe71rus** [comment]
вот что то. стека нет 
[gdb_openxray.txt](https://github.com/OpenXRay/xray-16/files/15285960/gdb_openxray.txt)

**Comment by Xottab-DUTY** [comment]
> вот что то. стека нет [gdb_openxray.txt](https://github.com/OpenXRay/xray-16/files/15285960/gdb_openxray.txt)

Блин, а он не показывает в какой функции упал (т.к. релиз без дебаг-символов)
Можешь запустить Debug из-под GDB?

**Comment by johndoe71rus** [comment]
дебуг сборку?

**Comment by Xottab-DUTY** [comment]
Да

**Comment by johndoe71rus** [comment]
собралось 
[gdb_debug_openxray.txt](https://github.com/OpenXRay/xray-16/files/15286137/gdb_debug_openxray.txt)

**Comment by Xottab-DUTY** [comment]
@johndoe71rus, чёт я понять не могу в чём дело. Вызывается инициализация SDL2, далее он уходит в X11, далее в libxcb, там пытается выделить память, уходит в системный аллокатор, а он, в свою очередь, ругается и вызывает вылет.

**Comment by johndoe71rus** [comment]
я тем более не знаю. commit[73338b342954b823c17196f19378682b5f14a6ab] branch[dev] ведет себя так же.
не дебуг
[openxray_johndoe.log](https://github.com/OpenXRay/xray-16/files/15342970/openxray_johndoe.log)

**Comment by Xottab-DUTY** [comment]
@sobkas, do you maybe know what the issue it could be?

**Comment by Xottab-DUTY** [comment]
> я тем более не знаю. commit[[73338b3](https://github.com/OpenXRay/xray-16/commit/73338b342954b823c17196f19378682b5f14a6ab)] branch[dev] ведет себя так же. не дебуг [openxray_johndoe.log](https://github.com/OpenXRay/xray-16/files/15342970/openxray_johndoe.log)

Очень надо бы, чтобы показывало в каких функциях вылет.
Ощущение, что Debug вылетает в каком-то другом месте)
Попробуй, пожалуйста, `RelWithDebInfo` собрать и запустить два раза:
1. Без GDB и покажи какой лог выдаст
2. Из-под GDB и тоже лог нужен

**Comment by johndoe71rus** [comment]
так, есть новость. собрал commit[5770e20cff04b3f96f972b7eb08dd0f8c72b6b0c]
он запускается. 
intel i5-7400
[Uploading openxray_i5_7400.log…]()
amd 620e
[Uploading openxray_amd_620e.log…]()
но есть проблема при завершении "выйти в виндовс" остаются в работе 2 процесса, игра и ее .sh  скрипт
![2024-05-17-215403_1920x1080_scrot](https://github.com/OpenXRay/xray-16/assets/7861172/1c3e7a45-82dc-466c-89c7-e9c82c058d49)
![2024-05-17-074054_1280x1024_scrot](https://github.com/OpenXRay/xray-16/assets/7861172/3747dc0c-8b10-4135-8fe0-e7a3833c0cfb)
Система одна, разные варианты железа.

завтра могу сделать еще тест на athlon 3000g со встройкой, если там эта версия будет ном, стоит собирать 7333 и тестить с дебугом?

**Comment by johndoe71rus** [comment]
решил собрать и запустить  7333
лог консоли обоих запусков 
 [openxray_console_log.txt](https://github.com/OpenXRay/xray-16/files/15369417/openxray_console_log.txt)

логи игры 
[openxray_johndoe.log](https://github.com/OpenXRay/xray-16/files/15369418/openxray_johndoe.log)
[openxray_johndoe_gdb.log](https://github.com/OpenXRay/xray-16/files/15369419/openxray_johndoe_gdb.log)

**Comment by johndoe71rus** [comment]
бинари commit[5770e20cff04b3f96f972b7eb08dd0f8c72b6b0c] собранного на тестовой системе, скопированные на машину athlon 3000g запустились. 
[openxray_johndoe.log](https://github.com/OpenXRay/xray-16/files/15369432/openxray_johndoe.log)

**Comment by Xottab-DUTY** [comment]
@johndoe71rus, а почему закрыл?

**Comment by johndoe71rus** [comment]
так после него 5770e20cff04b3f96f972b7eb08dd0f8c72b6b0c и сегодняшний собираются и работают. 
Загрузка cpu норм

**Comment by Xottab-DUTY** [comment]
Странно, 5770e20cff04b3f96f972b7eb08dd0f8c72b6b0c это коммит от 5 мая, а ты создал issue 12-го.
Ну, ладно. Если последний коммит работает, то хорошо. Я рад.
