### ISSUE TITLE
[Clear Sky] Weird RGB artifacts

### ISSUE THREAD

**Issue by Skajdrowski** [Swartz27/xray-16#1673]
**Describe the bug**
Lightning gets messed up randomly through gameplay with bright flickering RGB colors casted on everything.

**To Reproduce**
1. Load any existing save file
2. Quit game (Do not exit to desktop)
3. Make a new game

**Screenshots, videos**
![Screenshot (15)](https://github.com/OpenXRay/xray-16/assets/25054230/522cdc1c-3a3e-4c04-8acd-b22918d4ceed)

**BugTrap error report**
[openxray_skajdrovski.log](https://github.com/OpenXRay/xray-16/files/15325138/openxray_skajdrovski.log)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - GPU: Nvidia GeForce RTX 4060
 - GitHub Actions build 4788 (9099377553) from commit[b693218b45e92aecb14924beea30a55d8abd445c] branch[dev] (built by OpenXRay/xray-16)

**Comment by Xottab-DUTY** [comment]
This looks similar to #1454.

**Comment by Skajdrowski** [comment]
> This looks similar to #1454.

Yes, it's the same issue
