### ISSUE TITLE
Support volumetric clouds

### ISSUE THREAD

**Issue by bolatulyerdos** [Swartz27/xray-16#1674]

**Comment by Xottab-DUTY** [comment]
Do you mean volumetric clouds?

**Comment by bolatulyerdos** [comment]
> Do you mean volumetric clouds?

Yes.

**Comment by Xottab-DUTY** [comment]
This will require gamedata (shaders) changes. Currently we are focused on engine mostly.
For now I'll close this issue. To be reconsidered in future.
