### ISSUE TITLE
Demo record, cam_2, cam_3 not functioning correctly

### ISSUE THREAD

**Issue by yohjimane** [Swartz27/xray-16#1691]
**Describe the bug**
Caused by regression in this commit: 84f09c511d8d21535b47d3fe2e011abab9417d34

Can be fixed by adding this line back: https://github.com/OpenXRay/xray-16/commit/84f09c511d8d21535b47d3fe2e011abab9417d34#diff-8c9a94aa05d6fc560256f64b35bdde19e45da565a0d3998750c9f2f15d504bfdL399

When activating demo_record command, input keys don't work correctly until pressing period key.

When activating cam_2 / cam_3 keybinds, camera stays in static position while actor can still move around.

**To Reproduce**
1. Activate demo_record, cam_2 or cam_3
2. Observe camera functionality doesn't work the same as before this commit: 84f09c511d8d21535b47d3fe2e011abab9417d34

**Expected behavior**
When using demo_record, you should be able to move the camera around using wasd, spacebar keys and left/right mouse buttons.

When using cam_2/cam_3, camera should follow the actor and be affected by mouse movement.

**Comment by Xottab-DUTY** [comment]
Fixed in bd73c34fd1c3eb59c1cef018114a7b2bb9995cdf
