### ISSUE TITLE
No Fonts with Ubuntu Client

### ISSUE THREAD

**Issue by xslushedx** [Swartz27/xray-16#1694]
I have compiled a current version under Ubuntu. Call of Pripyat starts without any problems but there is no writing visible in the options menu or in-game. Am I missing any special fonts ? If I set the language to English the error goes away but it doesn't work in German.

**Comment by Hrusteckiy** [comment]
Please, check your `localization.ltx` file. And do you have a localization pack for German?

**Comment by Xottab-DUTY** [comment]
Closed due to no updates from the author.
