### ISSUE TITLE
compilation failed : error: unable to find library -lLua51 on FreeBSD

### ISSUE THREAD

**Issue by Martinfx** [Swartz27/xray-16#1697]
**Describe the bug**
Hi, i have problem find library "-lLua51" .
Maybe only add path -DCMAKE_LUA_LIBRARIES ? 

**To Reproduce**
1. Clone https://github.com/Martinfx/FreeBSD-Ports/pull/144
2. sudo make 
3. build failed

**Screenshots, videos**
`FAILED: /usr/home/maxfx/Documents/FreeBSD-Ports/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Debug/xrScriptEngine.so 
: && /usr/local/bin/clang++18 -fPIC -pipe -g -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -fdelayed-template-parsing -Wno-unused-command-line-argument -Wno-inconsistent-missing-override -stdlib=libc++ -Wno-attributes -Wl,--no-undefined   -mfpmath=sse -msse3 -Og -Wall -Wextra -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-parentheses -Wno-unused-label -Wno-unused-parameter -Wno-switch -pipe -g -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include  -fstack-protector-strong -fuse-ld=lld -shared -Wl,-soname,xrScriptEngine.so -o /usr/home/maxfx/Documents/FreeBSD-Ports/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Debug/xrScriptEngine.so src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/script_callStack.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/script_debugger.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/script_debugger_threads.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/script_lua_helper.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/BindingsDumper.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/ScriptExporter.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/pch.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/xrScriptEngine.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/LuaStudio/LuaStudio.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/script_process.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/script_thread.cpp.o src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/script_stack_tracker.cpp.o -L/usr/local/lib -Wl,-rpath,"\$ORIGIN:/usr/local/lib:/usr/home/maxfx/Documents/FreeBSD-Ports/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Debug:"  /usr/home/maxfx/Documents/FreeBSD-Ports/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Debug/xrAPI.so  /usr/home/maxfx/Documents/FreeBSD-Ports/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Debug/xrLuaFix.a  /usr/home/maxfx/Documents/FreeBSD-Ports/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Debug/xrLuabind.a  /usr/home/maxfx/Documents/FreeBSD-Ports/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Debug/xrLuajit-debug.so  /usr/home/maxfx/Documents/FreeBSD-Ports/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Debug/xrCore.so  -lpthread  -lexecinfo  /usr/local/lib/libSDL2.so  -lLua51  -Wl,-rpath-link,/usr/local/lib && :
ld.lld: error: unable to find library -lLua51
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
*** Error code 1
`
**Desktop (please complete the following information):**
 - OS: FreeBSD 13.3 Amd64
 - OpenXRay build version 6f5590d

**Additional context**

**Comment by Xottab-DUTY** [comment]
Our CMake scripts try to link to Lua51 only in one case – when XRAY_USE_LUAJIT option is off. This option must be always enabled, because we only support LuaJIT at this point (i.e. the option is not ready yet).

@Martinfx can you check that this option is for sure **enabled**?

**Comment by Martinfx** [comment]
Yes, i tested with "CMAkE_ON=       XRAY_USE_LUAJIT" and the same result

**Comment by Martinfx** [comment]
> Our CMake scripts try to link to Lua51 only in one case – when XRAY_USE_LUAJIT option is off. This option must be always enabled, because we only support LuaJIT at this point (i.e. the option is not ready yet).
> 
> @Martinfx can you check that this option is for sure **enabled**?

I enabled CMAKE_ON=       XRAY_USE_LUAJIT

```
k/xray-16-2188-november-2023-rc1/bin/x64/Release/xrAPI.so  /wrkdirs/usr/ports/games/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Release/xrLuaFix.a  /wrkdirs/usr/ports/games/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Release/xrLuabind.a  /wrkdirs/usr/ports/games/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Release/xrLuajit.so  /wrkdirs/usr/ports/games/xray-16/work/xray-16-2188-november-2023-rc1/bin/x64/Release/xrCore.so  -lpthread  -lexecinfo  /usr/local/lib/libSDL2main.a  /usr/local/lib/libSDL2-2.0.so.0.3000.8  -lxrLuaJIT && :
ld.lld: error: unable to find library -lxrLuaJIT
```

**Comment by Martinfx** [comment]
I used last commit ec2263a26286bff5304cad74430bdbce98409e1c and it works
