### ISSUE TITLE
call of pripyat crashes after trying to  render new parts of the map

### ISSUE THREAD

**Issue by jan-doez-animationz** [Swartz27/xray-16#1722]
i play call of pripyat it loads i move in the direction of the arrow thats on the map and it crashed

logs show me this:
~ Couldn't create surface from image: Parameter 'src' is invalid
OpenXRay Release Master Gold build 9375, Oct  8 2024 (Linux 64-bit, shared)
Custom build from commit[bff0d62ac2d5d346778a22a016f17f61bc0d3148] branch[dev]
 
command line 

* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSE41, SSE42, AVX
* CPU threads: 4

Starting INPUT device...
Initializing File System...
$fs_root$ = /home/jan/.local/share/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat/
using fs-ltx fsgame.ltx
SOUND: OpenAL: system default sound device name is Built-in Audio Analog Stereo
FS: 39503 files cached 29 archives, 24Kb memory used.
Init FileSystem 0.403174 sec
-----loading \home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
-----loading \home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
Loading module: xrRender_GL
Available render modes[1]:
renderer_r3
Executing config-script "user.ltx"...
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] successfully loaded.
Selected renderer: renderer_r3
Initializing Engine...
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx"...
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx] successfully loaded.
Executing config-script "user.ltx"...
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\grading_default.ltx"...
! Cannot open script file [\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\grading_default.ltx]
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\rspec_low.ltx"...
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\rspec_low.ltx] successfully loaded.
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\shaders_vanilla.ltx"...
! Cannot open script file [\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\shaders_vanilla.ltx]
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx"...
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx] successfully loaded.
~ Invalid syntax in call to 'sv_adm_menu_ban_time'
~ Valid arguments: ui_mp_am_10_minutes/ui_mp_am_30_minutes/ui_mp_am_1_hour/ui_mp_am_6_hours/ui_mp_am_1_day/ui_mp_am_1_week/ui_mp_am_1_month/ui_mp_am_3_monthes/ui_mp_am_forever
~ Invalid syntax in call to 'sv_suspicious_actions_ban_time'
~ Valid arguments: ui_mp_am_10_minutes/ui_mp_am_30_minutes/ui_mp_am_1_hour/ui_mp_am_6_hours/ui_mp_am_1_day/ui_mp_am_1_week/ui_mp_am_1_month/ui_mp_am_3_monthes/ui_mp_am_forever
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] successfully loaded.
SOUND: Selected device is Built-in Audio Analog Stereo
Starting RENDER device...
* GPU vendor: [Intel] device: [Mesa Intel(R) HD Graphics 4000 (IVB GT2)]
* GPU OpenGL version: 4.2 (Core Profile) Mesa 24.2.4 - kisak-mesa PPA
* GPU OpenGL shading language version: 4.20
* GPU OpenGL VTF units: [16] CTI units: [96]
* DVB created: 4096K
* DIB created: 512K
! Renderer doesn't support blender 'effects\shadow_world'
* HWDST/PCF supported and used
Starting engine...
* [ Linux ]: free[3745768 K], reserved[13100 K], committed[5388840 K]
* [ Render ]: textures[4149 K]
* [ x-ray  ]: process heap[199 K]
* [ x-ray  ]: economy: strings[7914 K], smem[0 K]
* phase time: 0 ms
* phase cmem: 217 K
Loading objects...
Loading models...
Loading textures...
* [prefetch] time:   1639 ms
* [prefetch] memory: 148 Kb
* phase time: 1642 ms
* phase cmem: 367 K
* phase time: 68 ms
* phase cmem: 367 K
* phase time: 0 ms
* phase cmem: 368 K
* Loading spawn registry...
* 6464 spawn points are successfully loaded
* Loading objects...
* 11093 objects are successfully loaded
* Game jan___ - beginning of the game is successfully loaded from file '\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\savedgames\jan___ - beginning of the game.scop' (1.412s)
* phase time: 1412 ms
* phase cmem: 643 K
* phase time: 29 ms
* phase cmem: 643 K
* phase time: 10 ms
* phase cmem: 643 K
* client : connection accepted - <All Ok>
* phase time: 10 ms
* phase cmem: 643 K
* phase time: 1 ms
* phase cmem: 643 K
* phase time: 449 ms
* phase cmem: 867 K
* phase time: 152 ms
linux mint 22 64 bit

**Comment by jan-doez-animationz** [comment]
ran it through terminal this is what pops up 
~ Couldn't create surface from image: Parameter 'src' is invalid
OpenXRay Release Master Gold build 9375, Oct  8 2024 (Linux 64-bit, shared)
Custom build from commit[bff0d62ac2d5d346778a22a016f17f61bc0d3148] branch[dev]
 
command line 

* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSE41, SSE42, AVX
* CPU threads: 4

Starting INPUT device...
Initializing File System...
$fs_root$ = /home/jan/.local/share/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat/
using fs-ltx fsgame.ltx
SOUND: OpenAL: system default sound device name is Built-in Audio Analog Stereo
FS: 39503 files cached 29 archives, 23Kb memory used.
Init FileSystem 0.331808 sec
-----loading \home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
-----loading \home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
Loading module: xrRender_GL
Available render modes[1]:
renderer_r3
Executing config-script "user.ltx"...
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] successfully loaded.
Selected renderer: renderer_r3
Initializing Engine...
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx"...
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx] successfully loaded.
Executing config-script "user.ltx"...
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\grading_default.ltx"...
! Cannot open script file [\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\grading_default.ltx]
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\rspec_low.ltx"...
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\rspec_low.ltx] successfully loaded.
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\shaders_vanilla.ltx"...
! Cannot open script file [\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\shaders_vanilla.ltx]
Executing config-script "\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx"...
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx] successfully loaded.
~ Invalid syntax in call to 'sv_adm_menu_ban_time'
~ Valid arguments: ui_mp_am_10_minutes/ui_mp_am_30_minutes/ui_mp_am_1_hour/ui_mp_am_6_hours/ui_mp_am_1_day/ui_mp_am_1_week/ui_mp_am_1_month/ui_mp_am_3_monthes/ui_mp_am_forever
~ Invalid syntax in call to 'sv_suspicious_actions_ban_time'
~ Valid arguments: ui_mp_am_10_minutes/ui_mp_am_30_minutes/ui_mp_am_1_hour/ui_mp_am_6_hours/ui_mp_am_1_day/ui_mp_am_1_week/ui_mp_am_1_month/ui_mp_am_3_monthes/ui_mp_am_forever
[\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] successfully loaded.
SOUND: Selected device is Built-in Audio Analog Stereo
Starting RENDER device...
* GPU vendor: [Intel] device: [Mesa Intel(R) HD Graphics 4000 (IVB GT2)]
* GPU OpenGL version: 4.2 (Core Profile) Mesa 24.2.4 - kisak-mesa PPA
* GPU OpenGL shading language version: 4.20
* GPU OpenGL VTF units: [16] CTI units: [96]
* DVB created: 4096K
* DIB created: 512K
! Renderer doesn't support blender 'effects\shadow_world'
* HWDST/PCF supported and used
Starting engine...
* [ Linux ]: free[2214408 K], reserved[74600 K], committed[6846472 K]
* [ Render ]: textures[4149 K]
* [ x-ray  ]: process heap[199 K]
* [ x-ray  ]: economy: strings[7914 K], smem[0 K]
* phase time: 0 ms
* phase cmem: 216 K
Loading objects...
Loading models...
Loading textures...
* [prefetch] time:   1595 ms
* [prefetch] memory: 148 Kb
* phase time: 1598 ms
* phase cmem: 367 K
* phase time: 63 ms
* phase cmem: 367 K
* phase time: 0 ms
* phase cmem: 367 K
* Loading spawn registry...
* 6464 spawn points are successfully loaded
* Loading objects...
* 11093 objects are successfully loaded
* Game jan___ - beginning of the game is successfully loaded from file '\home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\savedgames\jan___ - beginning of the game.scop' (1.416s)
* phase time: 1416 ms
* phase cmem: 642 K
* phase time: 31 ms
* phase cmem: 642 K
* phase time: 11 ms
* phase cmem: 642 K
* client : connection accepted - <All Ok>
* phase time: 8 ms
* phase cmem: 642 K
* phase time: 1 ms
* phase cmem: 642 K
* phase time: 419 ms
* phase cmem: 866 K
* phase time: 130 ms
* phase cmem: 866 K
* phase time: 90 ms
* phase cmem: 866 K
* phase time: 38 ms
* phase cmem: 866 K
* [DETAILS] VertexConsts(256), Batch(61)
* [DETAILS] 10126 v(20), 5368 p
* [DETAILS] Batch(61), VB(197K), IB(31K)
* phase time: 7 ms
* phase cmem: 866 K
* Loading HOM: \home\jan\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\levels\zaton\level.hom
* phase time: 4 ms
* phase cmem: 866 K
* phase time: 1 ms
* phase cmem: 866 K
* phase time: 5 ms
* phase cmem: 866 K
* phase time: 5 ms
* phase cmem: 866 K
* t-report - base: 1421, 187413 K
* t-report - lmap: 16, 4093 K
~ [ui\pda_tasks_16.xml] stretch attribute is unsupported for [background]
! Can't find texture 'ui_ingame2_pda_buttons_background_e'
! Can't find texture 'ui_pda2_fr_l'
! Can't find texture 'ui_pda2_fr_r'
! Can't find texture 'ui_pda2_fr_t'
! Can't find texture 'ui_pda2_fr_lt'
! Can't find texture 'ui_pda2_fr_rb'
! Can't find texture 'ui_pda2_fr_rt'
! Can't find texture 'ui_pda2_fr_lb'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_back'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_l'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_r'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_t'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_b'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_lt'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_rb'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_rt'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_lb'
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [background]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line1]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line2]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line3]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line4]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line_left]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line_right]
* phase time: 613 ms
* phase cmem: 866 K
! Unknown command:  dump_infos
* MEMORY USAGE: 953 K
* End of synchronization A[1] R[1]
* phase time: 12488 ms
* phase cmem: 953 K
* [ Linux ]: free[345064 K], reserved[74624 K], committed[8715816 K]
* [ Render ]: textures[204537 K]
* [ x-ray  ]: process heap[953 K]
* [ x-ray  ]: economy: strings[24620 K], smem[10208 K]

**Comment by jan-doez-animationz** [comment]
increased my render distance and game seems to crash each time when trying to render more parts of the map

**Comment by Xottab-DUTY** [comment]
Is that the full log?

**Comment by jan-doez-animationz** [comment]
> Is that the full log?

I should have probably closed this since i installed it through luxtorpeda and it worked perfectly fine but from what i remember that was the whole log no error at the end i can try and install it manually again to see it still happens

**Comment by jan-doez-animationz** [comment]
it runs perfectly fine guess the problem was fixed
