### ISSUE TITLE
мышь перестает работать в игре, если подключен джойстик.

### ISSUE THREAD

**Issue by JIuBeP** [Swartz27/xray-16#1725]
Но если отключить джойстик, мышь по прежнему не работает.

**Comment by Xottab-DUTY** [comment]
@JIuBeP, проверь, пожалуйста.

**Comment by JIuBeP** [comment]
Супер, спасибо! Теперь работает и то и это, без проблем!

**Comment by Xottab-DUTY** [comment]
А мне не помогло...
