### ISSUE TITLE
Compile fail in VS2022

### ISSUE THREAD

**Issue by ClickClick5** [Swartz27/xray-16#1726]
I'm partially new to GitHub in VS, but I've tried to set this manually and VS2022 is not happy with the current "unknown" identifier. What needs to go here? This is in xrCore!

Thanks!

[
![Screenshot 2024-10-23 141558](https://github.com/user-attachments/assets/c189086e-ded8-4b94-9e8a-4bedd689e39a)
](url)

**Comment by AMS21** [comment]
Looking at the way its used later it should be a string. `pcstr` is just a regular c-string if I recall correctly.

**Comment by Xottab-DUTY** [comment]
I just fixed the error itself, but better solution is to install git from http://git-scm.com

**Comment by Xottab-DUTY** [comment]
Explanation: the pre-build script in xrCore is used to determine current build information: the branch and commit id (hash). It uses git program for that.
If git isn't installed, the script does nothing and we just use dummy `unknown` string. The problem was that I forgot the quotation marks.

**Comment by ClickClick5** [comment]
...I tried all sorts of things, and I think " " as well, but here we are! Thanks!
I'm also installing git vs having VS pull it in.
