### ISSUE TITLE
Отсутствует gamedata в 32-битной сборке

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [Swartz27/xray-16#1727]
Недавно заметил что в 32-битной сборке нет архива xpatch_openxray_plus.db в папке patches
![изображение](https://github.com/user-attachments/assets/4bcd86cb-8a65-4ff8-bec6-c974decfe13a)

**Comment by Georgiy-Timoshin** [comment]
Теперь и в 64-битной тоже нет

**Comment by Xottab-DUTY** [comment]
Спасибо!

**Comment by Xottab-DUTY** [comment]
Теперь точно починил.
