### ISSUE TITLE
Failed to build by instruction

### ISSUE THREAD

**Issue by kacejot** [Swartz27/xray-16#1728]
**Describe the bug**
I can't configure CMake project with next output:
[cmake output.txt](https://github.com/user-attachments/files/17512830/cmake.output.txt)

**To Reproduce**
VS2022 is used
![image](https://github.com/user-attachments/assets/d990b0ee-9e1c-425d-8b6a-455659740bb3)
1.  cloned using command:
```bash
git clone https://github.com/OpenXRay/xray-16.git --recurse-submodules
```
2. run vs code and try to configure.

**Desktop (please complete the following information):**
 - OS:
![image](https://github.com/user-attachments/assets/54d7ce5f-46ca-48fb-a823-bd620cf02b86)
- OpenXRay commit: [0637118](https://github.com/OpenXRay/xray-16/commit/063711839690b76ca9343cd032590e2693df203a)

**Additional context**
Here is what fails
LuaJIT-proj/CMakeLists.txt:187
```cmake
...
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "e2k") # MCST Elbrus 2000
    set(TARGET_LJARCH "e2k")
else()
    message("${TESTARCH_OUTPUT}")
    message(FATAL_ERROR "Unsupported luajit target architecture (see output above)")
endif()
...
```

Looks like cl.exe command does not work as expected and preprocessing lj_arch.h fails for some reason. Don't know why.

**Comment by Xottab-DUTY** [comment]
CMake isn't supported for the Windows build at this point, so VS Code can't be used, only Visual Studio with MSBuild.
Open engine.sln in the src folder.

There is #1661 to fix that, but I don't remember if it's ready to merge, and it's really outdated.
