### ISSUE TITLE
CoP: xrengine.exe caused BREAKPOINT in module "C:\Program Files (x86)\Steam\steamapps\common\Stalker Call of Pripyat\bin\xrCore.dll" at 0033:00007FFF5DF836AA, xrDebug::Fail()+762 byte(s)

### ISSUE THREAD

**Issue by RealLotto** [Swartz27/xray-16#1735]
The game consistently crashes when you start a play session
Logs as below: 
[errorlog.log](https://github.com/user-attachments/files/17938528/errorlog.log)
[OpenXRay_PC.log](https://github.com/user-attachments/files/17938529/OpenXRay_PC.log)

**Comment by Xottab-DUTY** [comment]
According to the log, it seems that you have a mod that is incompatible with OpenXRay.
