### ISSUE TITLE
Ошибка с вылетом при переходе в Лиманск (ЧН):

### ISSUE THREAD

**Issue by LATEXPHONE** [Swartz27/xray-16#1737]
Та же ошибка #1010 с вылетом при переходе в Лиманск (ЧН):
no first body, can't set axis rel=1 (C:\projects\xray-16\Externals\ode\ode\src\joint.cpp:2506)

Перепробованы все версии (2021, 2020, Nightly), переустновки, проверены форумы — решения нет, а проблема до сих пор всплывает.

Система Windows 10, запуск на macOS Sequoia 15.1 и через Wine, и через CrossOver 
 
[logandsave.zip](https://github.com/user-attachments/files/17927298/logandsave.zip)

_Originally posted by @LATEXPHONE in https://github.com/OpenXRay/xray-16/issues/1010#issuecomment-2502386620_

**Comment by Xottab-DUTY** [comment]
Решения проблемы для релиза 2021-го года скорее нет, чем есть.
В ночных сборках поддержка ЧН гораздо более полная и работает лучше. В том числе, нет и этого бага.

**Comment by Xottab-DUTY** [comment]
> Перепробованы все версии (2021, 2020, Nightly)

Не верю. В nightly-версиях просто физически нет вылета `no first body, can't set axis rel=1`. Он убран.

Большая просьба проверить ещё раз 🙏
