### ISSUE TITLE
MacOS 15.1 arm64 crash 

### ISSUE THREAD

**Issue by DoktorCranium** [Swartz27/xray-16#1738]
MacOS 15.1 arm64  
fresh sources from master branch compile fine 

When runnning following error is observed (Version from around may 2024 worked on the MacOS 14.5) 

user@M2 Stalker % export DYLD_LIBRARY_PATH=$HOME/Games/Stalker
./xr_3da
~ Couldn't create surface from image: Parameter 'src' is invalid
OpenXRay Release Master Gold build 9430, Dec  2 2024 (Apple ARM 64-bit, shared)
Custom build from commit[ec2263a26286bff5304cad74430bdbce98409e1c] branch[dev]
 
command line 

* CPU features: ARMSIMD, NEON
* CPU threads: 8

Initializing File System...
Starting INPUT device...
$fs_root$ = /Users/user/Library/Application Support/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat/
using fs-ltx fsgame.ltx
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : xr_terminate
[error] File          : /Users/user/SRC/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 850
[error] Description   : Unexpected application termination
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xr_terminate()
std::__terminate(void (*)())
std::terminate()
std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>)
TaskManager::TaskWorkerStart()
void* std::__1::__thread_proxy[abi:ne180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::thread Threading::RunThread<void (TaskManager::*)(), TaskManager*>(char const*, void (TaskManager::*&&)(), TaskManager*&&)::'lambda'(void (TaskManager::*&&)(), TaskManager*&&), void (TaskManager::*)(), TaskManager*>>(void*)
7   libsystem_pthread.dylib             0x00000001977332e4 _pthread_start + 136
8   libsystem_pthread.dylib             0x000000019772e0fc thread_start + 8
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : xr_terminate
[error] File          : /Users/user/SRC/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 850
[error] Description   : Unexpected application termination
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xr_terminate()
std::__terminate(void (*)())
std::terminate()
std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>)
TaskManager::TaskWorkerStart()
void* std::__1::__thread_proxy[abi:ne180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::thread Threading::RunThread<void (TaskManager::*)(), TaskManager*>(char const*, void (TaskManager::*&&)(), TaskManager*&&)::'lambda'(void (TaskManager::*&&)(), TaskManager*&&), void (TaskManager::*)(), TaskManager*>>(void*)
7   libsystem_pthread.dylib             0x00000001977332e4 _pthread_start + 136
8   libsystem_pthread.dylib             0x000000019772e0fc thread_start + 8
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : xr_terminate
[error] File          : /Users/user/SRC/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 850
[error] Description   : Unexpected application termination
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xr_terminate()
std::__terminate(void (*)())
std::terminate()
std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>)
TaskManager::TaskWorkerStart()
void* std::__1::__thread_proxy[abi:ne180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::thread Threading::RunThread<void (TaskManager::*)(), TaskManager*>(char const*, void (TaskManager::*&&)(), TaskManager*&&)::'lambda'(void (TaskManager::*&&)(), TaskManager*&&), void (TaskManager::*)(), TaskManager*>>(void*)
7   libsystem_pthread.dylib             0x00000001977332e4 _pthread_start + 136
8   libsystem_pthread.dylib             0x000000019772e0fc thread_start + 8
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : xr_terminate
[error] File          : /Users/user/SRC/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 850
[error] Description   : Unexpected application termination
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xr_terminate()
std::__terminate(void (*)())
std::terminate()
std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>)
TaskManager::TaskWorkerStart()
void* std::__1::__thread_proxy[abi:ne180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::thread Threading::RunThread<void (TaskManager::*)(), TaskManager*>(char const*, void (TaskManager::*&&)(), TaskManager*&&)::'lambda'(void (TaskManager::*&&)(), TaskManager*&&), void (TaskManager::*)(), TaskManager*>>(void*)
7   libsystem_pthread.dylib             0x00000001977332e4 _pthread_start + 136
8   libsystem_pthread.dylib             0x000000019772e0fc thread_start + 8
zsh: trace trap  ./xr_3da

**Comment by VovanSSS** [comment]
I have the same problem

**Comment by Xottab-DUTY** [comment]
Duplicate of #1731
