### ISSUE TITLE
Game starts but literally almost everything is transparent (clear sky)

### ISSUE THREAD

**Issue by funghiforthen** [Swartz27/xray-16#1739]
I followed the installation steps. only bin and gamedata folders in cs root. issue both with nightly and 2021 build. like what :o im on windows 11 (atlas custom, but i have no similar issues elsewhere)

![Screenshot (1)](https://github.com/user-attachments/assets/001493cd-b88a-4c6f-8e2f-87446245dc45)

**Comment by Pogogo007** [comment]
I managed to fix it on my end by copying all the shaders from CoP r3 folder into the r3 folder in openxray clear sky (no replacing existing files)

**Comment by funghiforthen** [comment]
Ty. Taken from where? The actual game? Sry

**Comment by Pogogo007** [comment]
From the unpacked .db files from Call of Pripyat. I used AXRToolset to unpack the db files

**Comment by funghiforthen** [comment]
Smart move, I guess? 

☺️

**Comment by funghiforthen** [comment]
Ty

**Comment by Xottab-DUTY** [comment]
It should now work correctly even with original Clear Sky shaders.
