### ISSUE TITLE
Arch Linux - XRay crash on FillLanguageToken

### ISSUE THREAD

**Issue by d34dinsid3k1tty** [Swartz27/xray-16#1743]
**Describe the bug**
Game crashed

**To Reproduce**
1. Run `./xr_3da -fsltx ../fsgame.ltx`

**Expected behavior**
A runned game

**What's I got**
Crash, I tried to debug it in GDB, it's returns me Segmentation fault on one of language functions

```
Thread 1 "Primary thread" received signal SIGSEGV, Segmentation fault.
0x00007ffff5cba79e in CStringTable::FillLanguageToken() () from xrEngine.so
```

I have a small collection of files, but I only wanted to test OpenXRay, I think that I was skipped some files and that's why game crashing instead of running. But I'm unsure, here is my log from engine starting:

```
~ Couldn't create surface from image: Parameter 'src' is invalid
OpenXRay Release Master Gold build 9438, Dec 10 2024 (Linux 64-bit, shared)
Custom build from commit[66dd56b2151e673cb13314631c4df8e75b82e937] branch[dev]
 
command line -fsltx ../fsgame.ltx 

* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSE41, SSE42
* CPU threads: 2

Initializing File System...
Starting INPUT device...
$fs_root$ = /run/media/sech1p/c52138be-62dc-4507-80ac-db34fe17c94c/XRay/xray-16/bin/x86_64
using fs-ltx ../fsgame.ltx
FS: 1101 files cached 0 archives, 7Kb memory used.
Init FileSystem 0.035752 sec
-----loading \run\media\sech1p\c52138be-62dc-4507-80ac-db34fe17c94c\XRay\xray-16\bin\x86_64\gamedata\configs\system.ltx
-----loading \run\media\sech1p\c52138be-62dc-4507-80ac-db34fe17c94c\XRay\xray-16\bin\x86_64\gamedata\configs\system.ltx
SOUND: OpenAL: system default sound device name is Built-in Audio Analog Stereo
Loading module: xrRender_GL
Available render modes[1]:
renderer_r3
Executing config-script "user.ltx"...
~ Invalid syntax in call to 'renderer'
~ Valid arguments: renderer_r3
[\run\media\sech1p\c52138be-62dc-4507-80ac-db34fe17c94c\XRay\xray-16\bin\x86_64\_appdata_\user.ltx] successfully loaded.
Selected renderer: renderer_r3
[1]    114770 segmentation fault (core dumped)  ./xr_3da -fsltx ../fsgame.ltx
```

My files:

```
configs/system.ltx
configs/game.ltx
configs/alife.ltx
levels/l01.ltx
levels/l01.level
levels/level.ltx
shaders/ # I copied shaders from res directory in OpenXRay repo
strings/english.ltx
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - OpenXRay build version: 9438

**Comment by Xottab-DUTY** [comment]
Please, use absolute path for `-fsltx` key. Relative won't work correctly.

> I have a small collection of files, but I only wanted to test OpenXRay, I think that I was skipped some files and that's why game crashing instead of running.

Does that mean you don't have all original game files? Do you have at least models, animations, etc.?

**Comment by d34dinsid3k1tty** [comment]
Despites I have OG game I just wanted bare minimum to test if engine works, I wasn't inserted them (models, animations, etc.)

**Comment by d34dinsid3k1tty** [comment]
Despites I have OG game I just wanted bare minimum to test if engine works, I wasn't inserted them (models, animations, etc.)

btw Bare Minimum like checking if world works. Without any NPCs

**Comment by d34dinsid3k1tty** [comment]
Solved, it's caused by lack of translations (.xml files)
