### ISSUE TITLE
Incorrect work of burer's telekinesis

### ISSUE THREAD

**Issue by FreeZoneMods** [Swartz27/xray-16#886]
CStateBurerAttackTele class uses CTelekinesis::get_objects_count method  to iterate over all active objects. It's incorrect - this method does not return the total number of objects, but the number of objects in the TS_Keep and TS_Raise states. To get the total number of active objects we need to use CTelekinesis::get_objects_total_count.
So, we need to review every call of get_objects_count  in CStateBurerAttackTele, replace the incorrect calls with get_objects_total_count and check the logic of the surrounding code.

**Comment by jjdredd** [comment]
What issue does this mistake cause and how can we test it?
