### ISSUE TITLE
disable dynamic lights linux

### ISSUE THREAD

**Issue by fnyaker** [Swartz27/xray-16#890]
hi
i'm just wondering how can i disable dynamic lights stuff like shadows on linux, because i play that game on a potato laptop and that dynamic light stuff slow down the game (25 fps 800x600)

have a nice day !

**Comment by Xottab-DUTY** [comment]
Hi. We want to port static lighting renderer to OpenGL too and that will fix the problem. I can't say when that will happen, though.

Do you already have all settings set to minimum?

**Comment by fnyaker** [comment]
thanks ! 
and yes full minimal settings !
(my gpu is a uhd600 on a celeron 4000) (my friend have exactly the same pc on windows and it run with static lights at 60 fps without problems)

**Comment by Xottab-DUTY** [comment]
At the time of 2021, I forgot about `r2_sun` console command (in-game, on advanced graphics options tab it should be called something like "sun shadows"). You can use it to disable dynamic sun lights.
I guess, that would be the answer to the question.

Regarding porting static lighting (R1) to OpenGL, it's better to open a separate issue for that or add it to already existing similar task – #488. (it's not added yet)
