### ISSUE TITLE
GOG version problem?

### ISSUE THREAD

**Issue by huntermad** [Swartz27/xray-16#892]
My version is GOG [Version 2.0.0.12] which worked fine with original engine but Open-xray engine stopped after selecting difficulty and start the game. The game showed this error message

**BugTrap error report**

Error Reason:
----------------------------------------
xrEngine.exe caused ACCESS_VIOLATION in module "C:\WINDOWS\SYSTEM32\ig75icd32.dll" at 0023:62A08FFB, DllMain()+1530795 byte(s)

**Additional context**
Does it happen because GOG version doesn't have Stalker-COP.exe?

**Comment by Xottab-DUTY** [comment]
Not enough info:
Full log/error report needed.
How did you installed it?

It should not be launched directly, using xrEngine.exe from the bin folder. If GOG version has its own launcher instead of Stalker-COP.exe, then it's okay :) Otherwise, shortcut, created by the game installer, should be used.

**Comment by huntermad** [comment]
This is error file
https://drive.google.com/file/d/1VvWb8JA98fpSUfi_tiYpBCu0Anx-v7k0/view?usp=sharing

I just used the GOG launcher and get into the game, only after selecting difficulty and hit start that the game kicked me out due to error.


PS, it seems the error would occur after like 1 min or 2 after opening the game  not due to the start button

**Comment by huntermad** [comment]
Sorry, didn't realize Google change the Drive sharing settings.

**Comment by Xottab-DUTY** [comment]
Just checked the file... Something is wrong with the drivers. (maybe outdated or missing)

Please, install Microsoft Visual C++ Redistributable 2019, latest DirectX and drivers.

**Comment by huntermad** [comment]
Updated Drivers and it worked but there are strips of distortion on the scree now but still playable

**Comment by Xottab-DUTY** [comment]
Can you show a screenshot?

**Comment by huntermad** [comment]
It is more flickers of strips of distortions on my screen on loading, it is harder to spot in game but you realize there is some flashing when you  focus on the map/compass.

**Comment by huntermad** [comment]
It seems the problem came from Intel Graphic Driver which may be the reason it isn't in Windows Update list

**Comment by Xottab-DUTY** [comment]
Hmm... What if you enable V-Sync? Or disable SSAO?

**Comment by Xottab-DUTY** [comment]
Closed because there's not enough feedback.
