### ISSUE TITLE
Сегфолты каждые 10-15 минут [Clear Sky]

### ISSUE THREAD

**Issue by danshat** [Swartz27/xray-16#897]
Крашит с сегфолтом, как будто бы в случайные моменты игры на Болотах, промежутки времени также случайные, 10-15 минут.
ОС: Arch Linux, Linux 5.14.11
Логи: [openxray_danshat.log](https://github.com/OpenXRay/xray-16/files/7336881/openxray_danshat.log)

**Comment by vitaly-gaiduk** [comment]
@danshat лучше ещё предоставлять дамп процесса, так как проблема трудноповторима.
По умолчанию в Arch Linux дампы здесь:
`/var/lib/systemd/coredump`
Нужно проверить, возможно дампы от падений у тебя уже есть.
Поменять папку можно так (создав предварительно новую):
`sudo sysctl -w kernel.core_pattern=/coredumps/core-%e-%s-%u-%g-%p-%t`

Если нету: сними лимит на дамп, если этого ещё не сделано, действует в текущем шелле:
`ulimit -S -c unlimited`
Если нужно перманентно, добавь строчку в _/etc/security/limits.conf_:
`* soft core unlimited`

**Comment by danshat** [comment]
@vitaly-gaiduk Спасибо, вроде есть, полагаю, сталкеровский. [Раз](https://drive.google.com/file/d/1x36mEsKpGMraNCXCKBt23xCZ58ezWRn8/view?usp=sharing) [два](https://drive.google.com/file/d/1PZl917-U9RbPsHm8G2Aca5PBU9SaK0eW/view?usp=sharing)

**Comment by vitaly-gaiduk** [comment]
@danshat похоже на то, напиши ещё с какой ветки и коммита у тебя сборка, чтобы было проще вести проблему.

**Comment by Xottab-DUTY** [comment]
Это в логе есть :)
> Custom build from commit[0ed84c0781e3eb6daf5227d30c48974ece59b948] branch[dev]

Но, по вылетам, в логе ничего нет. Есть адреса функций, но это нечеловекочитаемо...
Если запустить из-под GDB, по идее, должно показать что-то более внятное, вплоть до номера строки в исходниках. (при условии, что исходники, из которых движок скомпилен, лежат там же, где были во время сборки)
Было бы неплохо.

Ну, или, если кто-то сможет достать из дампов что-то :)

**Comment by vitaly-gaiduk** [comment]
@Xottab-DUTY точно, не подумал посмотреть :)
Да, по адресам только в самом собранном файле посмотреть получится.
С GDB можно будет backtrace посмотреть - поэтому дамп должен помочь.
Вроде можно увидеть название функции, даже если исходники не там.

В виртуалке не прогрузить движок до этого места похоже, поэтому либо устанавливать машину с Arch Linux, либо если @danshat готов помочь, то можно выполнить несколько шагов, чтобы получить trace :)
1) Распаковать у себя дамп (осторожно, извлекаемый файл может быть больше, чем в 2 раза):
`unzstd <name.zst>`
Установить, если unzstd нету:
`sudo pacman -S zstd`
2) Запустить движок вместе с GDB (установить LD_LIBRARY_PATH если нужно):
`gdb ./xr_3da <путь-к-распакованному-дампу>`
3) Скопировать вывод из отладчика после команды:
`(gdb) bt`

**Comment by danshat** [comment]
```
(gdb) bt
#0  0x00007f2b5fbb40e2 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7ffdfaa4cfa0
```
Полагаю, это также малоинформативно
[Полный лог gdb](https://pastebin.com/1B841aXx)
Исходники в той же папке так и лежат, где собирал

**Comment by vitaly-gaiduk** [comment]
@danshat пока да, но спасибо что выложил весь лог и сделал шаги!
Я пропустил то, что запускать движок надо с опцией _-cs_, так как у нас Clear Sky. В логе gdb как раз написано, чем сгенерирован дамп:
`Core was generated by 'xr_3da -cs'.`

Поэтому запускать нужно всё же как-то так (под рукой сейчас нету linux, не могу точно проверить):
`gdb -c <dump file> --args ./xr_3da -cs`

Скопируй вывод после такого запуска тоже сюда :)

Но ещё момент: движок у тебя собран в Release сборке, т.е. без debug символов, поэтому вероятно ещё понадобится собрать хотя бы в Mixed конфигурации, чтобы увидеть информативный стек.

**Comment by danshat** [comment]
@vitaly-gaiduk Странно. Через PKGBUILD арча Mixed у меня [не собирается](https://pastebin.com/SZAXsj6P) вовсе (при ручной сборке ругается на ту же бибу), Debug и RelWithDebInfo собираются и ставятся, но gdb все равно [заявляет,](https://pastebin.com/VHUhD49L) что `(No debugging symbols found in xr_3da)`. Исходники новые и пакет до этого удалил с помощью `pacman -R openxray-dev`. Можно как-то проверить, какой сборки сейчас стоит пакет?

**Comment by Xottab-DUTY** [comment]
Посмотрел лог сборки.
Нужно обновить подмодули:
`git submodules update --init --recursive`

**Comment by danshat** [comment]
Ничего не поменялось вроде бы, да и клонировал репу я с `--recurse-submodules`, это по идее тоже самое.

**Comment by vitaly-gaiduk** [comment]
@danshat нужно перейти в `Externals/luabind` и убедиться, что сабмодуль на нужном коммите: [d4d1966](https://github.com/OpenXRay/luabind-deboostified/tree/d4d1966aa6c253f413446a15133174640b8b1de5).

В сборке я не копался, не понимаю, почему нет символов, но можно попробовать такой хак. Перед сборкой очистить кэш CMake и в шелле сборки экспортировать две переменные:
`export CFLAGS=-ggdb`
`export CXXFLAGS=-ggdb`

CMake должен добавить эти флаги компиляции к остальным.

**Comment by danshat** [comment]
```
danshat:luabind (d4d1966) $ git status 
HEAD отделён на d4d1966
```
```
CMake build Debug, CFLAGS=-ggdb  -mfpmath=sse -msse3, CXXFLAGS=-ggdb -Wno-attributes -Wl,--no-undefined -fvisibility=hidden  -mfpmath=sse -msse3 -Og
```
`(No debugging symbols found in xr_3da)`

Однако символы, как будто бы, нашлись после ручной сборки версии Debug через make и make install, а не PKGBUILD.
Почему-то не помогло: https://pastebin.com/UCpqEJdT
Может, попробовать выбить новый дамп? Раз уж новый бинарник собрали.

UPD:
```
danshat:bin $ readelf -S xr_3da | grep -i debug
  [29] .debug_info       PROGBITS         0000000000000000  0000211b
  [30] .debug_abbrev     PROGBITS         0000000000000000  00014897
  [31] .debug_loclists   PROGBITS         0000000000000000  00015d99
  [32] .debug_aranges    PROGBITS         0000000000000000  0001614d
  [33] .debug_rnglists   PROGBITS         0000000000000000  000161ad
  [34] .debug_line       PROGBITS         0000000000000000  000161e8
  [35] .debug_str        PROGBITS         0000000000000000  00016a1b
  [36] .debug_line_str   PROGBITS         0000000000000000  0002a45a
```

**Comment by vitaly-gaiduk** [comment]
@danshat Debug версия неиграбельна, поэтому лучше перезапустить Mixed или RelWithDebInfo и получить дамп, да.

**Comment by danshat** [comment]
Пока гулял, нашел еще вот это, когда поменял основное оружие драг-н-дропом, но это уже совсем другая история: https://pastebin.com/3WmEshRs

А вот, кажется, и искомый вылет нашелся: https://pastebin.com/Y1UrmiRe

**Comment by Castlesoap** [comment]
По логу понятно из-за чего крашится, просто в xr-danger.script нужно добавить проверку, что объект является сталкером.

if best_danger_object:character_community() == self.object:character_community()  then

нужно поменять на:

if **IsStalker(best_danger_object) and** best_danger_object:character_community() == self.object:character_community()  then

**Comment by Xottab-DUTY** [comment]
Нет, крашится не из-за этого. Это просто спам, который к вылетам не приводит. (во всяком случае, на оригинальной геймдате ЧН ни разу не вылетало у меня)

**Comment by Castlesoap** [comment]
Не посмотрел я исходники, каюсь!Там есть строчка, которая вернет управление функции, ну да ладно. Но поправить всё-таки стОит хотя бы для оптимизации. Зачем вызвать лишний раз метод, который не применим к сталкерам?

**Comment by danshat** [comment]
https://pastebin.com/qsCKBKJs Вот еще такое есть. На размер кордампов, оказывается, в арче лимит 2 гб, он их обрезал зачем-то.

**Comment by nickgsm** [comment]
Вчера собрал крайнюю dev версию, и также сегфолты одолели. А сегодня пересобрал с RelWithDebInfo и блин третий час игры по болотам и ниразу не вылетела. :( :)

**Comment by danshat** [comment]
@nickgsm Оно у меня тоже ситуативно как-то было. Я от Агропрома до Лиманска прошел и ни разу не вылетел, под конец игры регулярно крашился опять.

**Comment by nickgsm** [comment]
Ну я новую начал и играть не возможно было. По проверяю пока так может начнёт падать, потом опять соберу релиз если не упадёт.

**Comment by Xottab-DUTY** [comment]
Так как было много правок, которые, потенциально, увеличили стабильность, закрываю.

Можно будет открыть по новой, если какие-то вылеты опять обнаружатся.
