### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by RonFusaishi** [Swartz27/xray-16#906]
OS: Artix Linux

==> Making package: openxray-dev 1.6.02_1854da909-1 (Tue Nov  9 12:55:22 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> Extracting sources...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- MASTER_GOLD: ON
Using mimalloc memory allocator
CMake build Release, CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -mfpmath=sse -msse3, CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions
       -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wno-attributes -Wl,--no-undefined -fvisibility=hidden  -mfpmath=sse -msse3
-- Found FreeImage: /usr/include, /usr/lib/libfreeimage.so
-- Found FreeImagePlus: /usr/include, /usr/lib/libfreeimageplus.so
git commit: 1854da9096fcf1f43ab727efa23cf8bd157fa004
git branch: dev
CMake Error at Externals/LuaJIT-proj/luajit.cmake:169 (message):
  Unsupported luajit target architecture
Call Stack (most recent call first):
  Externals/LuaJIT-proj/CMakeLists.txt:1 (include)

-- Configuring incomplete, errors occurred!
See also "/home/lone/builds/xray-16/bin/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by Xottab-DUTY** [comment]
> Unsupported luajit target architecture

@007exe, maybe, you have an idea of what's happening?

**Comment by 007exe** [comment]
@RonFusaishi It looks like you haven't cloned the repository with submodules. Try to initialize and download submodules (while in the xray-16 directory) run `git submodule init & git submodule update` or download `git clone https://github.com/OpenXRay/xray-16.git --recurse-submodules.`
P.S. This PKGBUILD is for developers. I recommend using the package from the [AUR](https://aur.archlinux.org/packages/openxray-git/)

**Comment by RonFusaishi** [comment]
> @RonFusaishi It looks like you haven't cloned the repository with submodules. Try to initialize and download submodules (while in the xray-16 directory) run `git submodule init & git submodule update` or download `git clone https://github.com/OpenXRay/xray-16.git --recurse-submodules.` P.S. This PKGBUILD is for developers. I recommend using the package from the [AUR](https://aur.archlinux.org/packages/openxray-git/)

Thank you very much!, it worked 

sorry im a bit new to git, so im unaware of "Submodules" .
