### ISSUE TITLE
CoP Misory Mod with Gunslinger Crash

### ISSUE THREAD

**Issue by alexander9822** [Swartz27/xray-16#910]
**Describe the bug**
I installed Misery with Gunslinger, Then I installed openxray release version and apon starting new game it CTD with error log

**To Reproduce**
1. Install Misery with Gunslinger
2. Install openxray
3. Start new game.

**Expected behavior**
I expected to start new game

**BugTrap error report**
[openxray_alexander faiers.log](https://github.com/OpenXRay/xray-16/files/7541418/openxray_alexander.faiers.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OpenXRay latest build

**Additional context**
I also did the fix that was described in another bug report on github here: https://github.com/OpenXRay/xray-16/issues/439 in which your have remove the end and put an underscore in.
I have also attached the files the error log refences.

[scripts.zip](https://github.com/OpenXRay/xray-16/files/7541431/scripts.zip)

**Comment by Xottab-DUTY** [comment]
Gunslinger is only compatible with vanilla engine.

**Comment by alexander9822** [comment]
This is version on gunslinger designed to work with misery see here: https://stalkerportaal.ru/load/zov_pripjati_repack/misery_2_2_1_gunslinger_mod/135-1-0-3183

**Comment by alexander9822** [comment]
Its works without openxray

**Comment by alexander9822** [comment]
the problem only happens with openxray

**Comment by Xottab-DUTY** [comment]
> Its works without openxray

Yes! And it won't work with OpenXRay.

Gunslinger has a special launcher, that applies assembly patches to the original engine and these patches are only compatible with original engine.

**Comment by jjdredd** [comment]
> Gunslinger has a special launcher, that applies assembly patches to the original engine and these patches are only compatible with original engine.

insane
