### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by Bestaford** [Swartz27/xray-16#916]
**libfreeimage3, libfreeimageplus3 and freeimage-devel are installed**

! Couldn't create surface from image: Couldn't open logo.bmp
OpenXRay Rx64 build 8330, Nov 27 2021
Custom build from commit[d885d5d10f93dde0a7ab1b3a0897d384f5245af5] branch[HEAD]
 
command line 

* Detected CPU: AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G    [AuthenticAMD], F15/M0/S0, 'rdtsc'
* CPU features: RDTSC, Invariant TSC, MMX, SSE, SSE2, SSE3, MONITOR/MWAIT, SSSE3, SSE4.1, SSE4.2, AVX, AVX2
* CPU cores/threads: 2/2
* CPU current freq: 2419 MHz

Initializing File System...
$fs_root$ = /home/bestaford/.local/share/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat/
using fs-ltx fsgame.ltx
FS: 39390 files cached 32 archives, 15Kb memory used.
Init FileSystem 0.784171 sec
-----loading \home\bestaford\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
-----loading \home\bestaford\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
! Failed to determine on which monitor the game is launched.
! SDL: Invalid window
Starting INPUT device...
No joysticks available
Loading module: xrRender_GL
! Failed to load module: xrRender_GL
! Failed loading xrRender_GL.so: /home/bestaford/Downloads/usr/bin/xrRender_GL.so: undefined symbol: _ZNK8fipImage12saveToMemoryE
Available render modes[0]:
Executing config-script "user.ltx"...
! Cannot open script file [user.ltx]
 
FATAL ERROR
 
[error] Expression    : selectedRenderer
[error] Function      : InitializeRenderers
[error] File          : /home/appveyor/projects/xray-16/src/xrEngine/EngineAPI.cpp
[error] Line          : 104
[error] Description   : Can't setup renderer
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
CEngineAPI::InitializeRenderers()
CEngineAPI::Initialize()
RunApplication()
./xr_3da(+0x1619) [0x559d142b5619]
./xr_3da(+0x137f) [0x559d142b537f]
/lib64/libc.so.6(+0x405c0) [0x7fae523da5c0]
/lib64/libc.so.6(__libc_start_main+0x7e) [0x7fae523da67c]
./xr_3da(+0x145a) [0x559d142b545a]
Trace/breakpoint trap (core dumped)

**Comment by Bestaford** [comment]
is this function only supported on Windows?
https://freeimage.sourceforge.io/fnet/html/CC93ED54.htm

**Comment by Xottab-DUTY** [comment]
> is this function only supported on Windows? [freeimage.sourceforge.io/fnet/html/CC93ED54.htm](https://freeimage.sourceforge.io/fnet/html/CC93ED54.htm)

On Linux, you mean?)

Hmm, I don't know...


But, well, I just wan't to remove FreeImage and that will fix the problem.
![image](https://user-images.githubusercontent.com/2989212/143768023-48b2cb15-6573-456e-90c2-5d6411c11002.png)

**Comment by Bestaford** [comment]
so i just want play CoP without Proton...

**Comment by Xottab-DUTY** [comment]
[In another issue](https://github.com/OpenXRay/xray-16/issues/394#issuecomment-488382655), I've found that there was a problem with the FreeImage installation and downgrade helped.

Can you try to reinstall and\or downgrade (just one version lower) FreeImage in your system to see if it helps?

**Comment by Bestaford** [comment]
downgrade packages in opensuse is big problem, but i just place needed .so libs with engine and launch it with export LD_LIBRARY_PATH=

**Comment by Bestaford** [comment]
so, i downgraded freeimage to 3.17, download all needed libs and it works
