### ISSUE TITLE
Consider using Intel ISPC for math in the renderer and in level compilers

### ISSUE THREAD

**Issue by Xottab-DUTY** [Swartz27/xray-16#920]
https://github.com/ispc/ispc

Idea to consider:
- Convert HLSL to ISPC
  - https://github.com/zigguratvertigo/hlsl-to-ispc

Something similar:
- https://github.com/ROCm/HIP

**Comment by jjdredd** [comment]
Looks nice

**Comment by Xottab-DUTY** [comment]
Closing due to:
1. Less portable than just C++ and HLSL/GLSL.
3. S.T.A.L.K.E.R. doesn't have super very hard workloads.
4. It's better to use open-source solutions for baking lights, so we don't invent everything ourselves.
