### ISSUE TITLE
[Linux/Unix] Support linking with mold

### ISSUE THREAD

**Issue by Xottab-DUTY** [Swartz27/xray-16#925]
https://github.com/rui314/mold

**Comment by jjdredd** [comment]
wow didn't realize gnu linker was so slow. how stable/tested is mold?

**Comment by Xottab-DUTY** [comment]
I don't know 🙂

**Comment by timmypidashev** [comment]
Can confirm it does start to feel sluggish if building from source on linux.

**Comment by Xottab-DUTY** [comment]
mold is reaaaaaaaallllly fast

**Comment by Xottab-DUTY** [comment]
To use it, just supply `-DXRAY_LINKER=mold` to the `cmake` command.
