### ISSUE TITLE
Linux: CoP Game freezes after emission is over

### ISSUE THREAD

**Issue by russkel** [Swartz27/xray-16#931]
**Describe the bug**
Game freezes at "Game Over" text after dying in an emission. Running vanilla CoP data files from steamapps.

**To Reproduce**
1. Be outside when an emission is occuring.
2. Do not take cover.
3. When screen goes red and Game Over text appears the game will freeze.

**Expected behavior**
Game continues as expected.

**BugTrap error report**
Doesn't seem to be a crash report. The process hangs but doesn't crash.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
OpenXRay Rx64 build 8371, Jan  7 2022
Custom build from commit[1dc1c10508f6f7c9364149589cad8997d3aed6c2] branch[makepkg]

Additional info:

Happens running in window mode or full screen.

**Comment by jjdredd** [comment]
Is there some save we can use to test the emission?

**Comment by russkel** [comment]
There sure is.

[russ - emission.scop.zip](https://github.com/OpenXRay/xray-16/files/7834638/russ.-.emission.scop.zip)

**Comment by russkel** [comment]
I also noticed the log file seems to be incomplete at the end, as if it was abruptly ended:

```
* Game russ - emission is successfully loaded from file '\home\russ\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\savedgames\russ - emission.scop' (0.649s)
* phase time: 649 ms
* phase cmem: 1019 K
* phase time: 25 ms
* phase cmem: 1020 K
* ph
```

Should there be more entries? Is there an issue with the buffering to file?

**Comment by Xottab-DUTY** [comment]
Flush to disk happens on exit or after a crash. It should be either full or empty, it's strange that you have something in the middle like this... 🤔 

However, there's a command line key: `-force_flushlog`, that makes engine write to disk after each log entry.

**Comment by russkel** [comment]
I have just played this save game again and ran to cover in the cave, I survived the emission but it still hangs. I have experienced only one emission before this inside the ship, which didn't have the lightning or red light effects.
How can I go about debugging this?

**Comment by BielBdeLuna** [comment]
I have the same problem, even in cover from the emission when the emission ends the game locks up. 
I could pass the first emission but the second I get the lock up.
I'm using Ubuntu, and using the last commit.
It happens at the moment the emission ends, and unfortunately I got no special messages in the linux terminal.

**Comment by russkel** [comment]
I attempted to have a look at this after compiling the engine in debug mode, but there's a ton of assert issues before the game world even loads. There's a few rough edges around Linux support it seems, around the physics engine being a version that was Windows only.

**Comment by jjdredd** [comment]
It looks like the problem is in the collisions code.

**Comment by BielBdeLuna** [comment]
maybe related to this? https://github.com/OpenXRay/xray-16/issues/970

**Comment by jjdredd** [comment]
> maybe related to this? #970

Quite possible. I actually overlooked this obvious problem when debugging.

```	
	// if s <= 0 then we've got a problem. if we just keep going then
	// we're going to get stuck in an infinite loop. instead, just cross
	// our fingers and exit with the current solution.
	if (s <= 0) {
	  dMessage (d_ERR_LCP, "LCP internal error, s <= 0 (s=%.4e)",s);

```

https://github.com/OpenXRay/xray-16/blob/dev/Externals/ode/ode/src/lcp.cpp#L1302

**Comment by BielBdeLuna** [comment]
no, the error is not right! 
it's nothing to do with the cinematic or the teleporting... it's got to do with the combat of AI actors, it seems to throw this error sometimes when they become ragdoll.

**Comment by BielBdeLuna** [comment]
after compiling with `-DMASTER_GOLD OFF` while I've been able to complete most of Zaton and get to Yanov Station with only two crashes to desktop unrelated to Emissions (good old stalker) and at the same time having overcome at least two emissions during the time It took to play all that way without any crashes related to them:
- Maybe the crashes after emissions is related to **code optimization**? 
- or to something that changes when `-DMASTER_GOLD` is `OFF`?

**Comment by BielBdeLuna** [comment]
I noticed that after the emission finishes sometimes characters teleport to the location the player is sheltered from the emission then those characters that got teleported in die immediately, you can loot them and also take the weapon they just beared in their arms. so they actually got killed by the system selectively, they might be chars that didn't make it to any shelter, and somewhat the system decided to teleport them in the shelter the player is in(?) 
maybe the system decides that far away characters (from the player) on route to a shelter but no in time to arrive to it during an emission, should teleport to the shelter after the emission finishes? only that this time the payer was inside the shelter and saw the trick?
But as far as I know the chars should die before the emission ends not at the same time (or a game frame later)
maybe all of this is what makes the process fail?

**Comment by jjdredd** [comment]
variable `max_depth` (which is object interpenetration depth?) happens to be `inf`, which leads to an infinite loop in
`bool CPHActivationShape::Activate(...)`

**Comment by jjdredd** [comment]
I tested on `09100750762e2fc2b4a8b7e79b6f424db164a9e3` and died in an emission. the game didn't freeze and I was able to exit to main menu. Please check this again.

**Comment by jjdredd** [comment]
Seems to me that the issue is gone

**Comment by Xottab-DUTY** [comment]
The issue is too old. It might have been fixed, it might have been not.
For the bookkeeping, I'm closing this. Please, reopen it if issue is still there.
