### ISSUE TITLE
Зависание после разговора с Ковальским

### ISSUE THREAD

**Issue by denzor200** [Swartz27/xray-16#949]
**Describe the bug**
Зависает сцена(не вся игра целиком) после того как поговорить с Ковальским. Управление при этом теряется, игру приходится килять чтобы выйти.
Сохранение для скорейшего воспроизведения прилагается ниже.

**To Reproduce**
1. Загрузить игру с приложенным сохранением;
2. Начать диалог с Ковальским, сообщить ему о наемниках;
3. Согласиться помочь разобраться с наемниками;
4. Наблюдать зависание сцены(персонаж Ковальский при этом будет стоять и не предпринимать дальнейших действий для развития сцены, управление актором при этом будет потеряно)

**Expected behavior**
Ожидается что сцена будет проиграна до конца, без зависаний персонажа, по-окончании сцены игроку будет возвращено управление актором.

**BugTrap error report**
Падений при этом не обнаружено.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - OpenXRay Custom build from commit[d233d82174e766c94df5ace8d8740fde411869ce] branch[dev]

**Additional context**
 - Ссылка на сохранение: https://drive.google.com/file/d/1qOrkZVWieTxEplx-aTK7X0jT773E41gn/view?usp=sharing

**Comment by ChugunovRoman** [comment]
@denzor200 после загрузки сейва у Ковальского была логика `remark@a22_wait_cam` если с ним заговорить то этот баг воспроизведется, но если выйти из комнаты и вернуться опять к нему то логика у него переключится на `walker@stand_base` и бага уже не будет. Это все что мне пока удалось выяснить на данный момоент :thinking:

**Comment by Xottab-DUTY** [comment]
Сохранение уже несовместимо с текущей версией OpenXRay.
Попробуй воспроизвести баг уже на новой версии движка!
Потенциально, баг мог быть исправлен, так что пока закрою.

**Comment by tsunamaru** [comment]
@Xottab-DUTY баг актуален, воспроизводится у меня в https://github.com/OpenXRay/xray-16/commit/13c775dc153ef8e5249a991838add1ae953b375c (Windows x64 Release Master Gold)

Сейв: [savedgames.zip](https://github.com/user-attachments/files/20512187/savedgames.zip)

**Comment by Xottab-DUTY** [comment]
Согласно данным со S.T.A.L.K.E.R. Wiki:
> Пока не пройден этот квест, категорически не рекомендуется самовольно посещать лабораторию X8. Иначе после разговора с Ковальским игра, скорее всего, будет зависать, и придётся переигрывать. Если по каким-то причинам не осталось сохранений до самовольного входа в лабораторию X8, единственный выход из положения — отказаться от прохождения квеста. Также избежать зависания в таком случае можно, если после задания «Разговор с глазу на глаз» не сразу доложить полковнику Ковальскому о встрече Гарика с наёмниками, а сделать это после нескольких часов сна.

Квест багнутый, проблема оригинальной игры.
https://stalker.fandom.com/ru/wiki/Один_выстрел
