### ISSUE TITLE
[ Linux ] - Segmentation Fault every time I try to start a new game

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#960]
**Describe the bug**
every time I start a new game in Call of Pripyat I get a segmentation fault

**BugTrap error report**
[openxray_biel bestué de luna.log](https://github.com/OpenXRay/xray-16/files/8147185/openxray_biel.bestue.de.luna.log)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - OpenXRay build version: Custom build from commit[35fbe9728941dda2654dd62249c3a22c8b758e3b] branch[dev]

**Comment by r-a-sattarov** [comment]
Confirm. I get the same bug on Elbrus architecture.

`Thread 1 "Primary thread" received signal SIGSEGV, Segmentation fault`
`exc_data_page delayed interrupt at 0x45557a11b8b0 ALS3 | ALS5`
`0x000045557a11b8c0 in CRenderTarget::u_calc_tc_noise(_vector2<float>&, _vector2<float>&) () from /usr/lib64/xrRender_GL.so`

`#0  0x000045557a11b8c0 in CRenderTarget::u_calc_tc_noise(_vector2<float>&, _vector2<float>&) () from /usr/lib64/xrRender_GL.so`
`#1  0x000045557a11c478 in CRenderTarget::phase_pp() () from /usr/lib64/xrRender_GL.so`
`#2  0x0000455579c8a680 in CRenderTarget::phase_combine() () from /usr/lib64/xrRender_GL.so`
`#3  0x000045557a0eb9b8 in CRender::Render() () from /usr/lib64/xrRender_GL.so`
`#4  0x000045555571c600 in IGame_Level::OnRender() () from /usr/lib64/xrEngine.so`
`#5  0x000045557cca3a40 in CLevel::OnRender() () from /usr/lib64/xrGame.so`
`#6  0x00004555556818b8 in MessageRegistry<pureRender>::Process() () from /usr/lib64/xrEngine.so`
`#7  0x000045555567db48 in CRenderDevice::DoRender() () from /usr/lib64/xrEngine.so`
`#8  0x000045555567c070 in CRenderDevice::ProcessFrame() () from /usr/lib64/xrEngine.so`
`#9  0x000045555567f960 in CRenderDevice::message_loop() () from /usr/lib64/xrEngine.so`
`#10 0x000045555567ec88 in CRenderDevice::Run() () from /usr/lib64/xrEngine.so`
`#11 0x0000455555741208 in Startup() () from /usr/lib64/xrEngine.so`
`#12 0x00004555557429d8 in RunApplication() () from /usr/lib64/xrEngine.so`
`#13 0x000000000001cc90 in main ()`

[openxray_e2k.log](https://github.com/OpenXRay/xray-16/files/8172467/openxray_e2k.log)
[openxray_e2k_gdb.log](https://github.com/OpenXRay/xray-16/files/8172475/openxray_e2k_gdb.log)

**Comment by johndoe71rus** [comment]
can you post glxinfo -B output?

**Comment by BielBdeLuna** [comment]
```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon(TM) Vega 10 Graphics (RAVEN, DRM 3.41.0, 5.13.0-30-generic, LLVM 12.0.1) (0x15d8)
    Version: 21.2.6
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 1405 MB, largest block: 1405 MB
    VBO free aux. memory - total: 3008 MB, largest block: 3008 MB
    Texture free memory - total: 1405 MB, largest block: 1405 MB
    Texture free aux. memory - total: 3008 MB, largest block: 3008 MB
    Renderbuffer free memory - total: 1405 MB, largest block: 1405 MB
    Renderbuffer free aux. memory - total: 3008 MB, largest block: 3008 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 5120 MB
    Currently available dedicated video memory: 1405 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon(TM) Vega 10 Graphics (RAVEN, DRM 3.41.0, 5.13.0-30-generic, LLVM 12.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by r-a-sattarov** [comment]
> can you post glxinfo -B output?
```
$ glxinfo -B
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD OLAND (DRM 2.50.0, 5.4.0-3.15-e8c-nn, LLVM 9.0.1) (0x6613)
    Version: 20.3.5
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: AMD
OpenGL renderer string: AMD OLAND (DRM 2.50.0, 5.4.0-3.15-e8c-nn, LLVM 9.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 20.3.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 20.3.5
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by jspyro** [comment]
To add another datapoint: I'm experiencing (presumably) the same issue with **Clear Sky**. 

- OS: Ubuntu 20.04
- OpenXRay build version: Custom build from commit[35fbe97] branch[dev]

[xr_3da.log](https://github.com/OpenXRay/xray-16/files/8180593/xr_3da.log)
[glxinfo.log](https://github.com/OpenXRay/xray-16/files/8180594/glxinfo.log)
