### ISSUE TITLE
[Linux] Ключ запуска -fsltx <путь> не работает если <путь> содержит пробелы

### ISSUE THREAD

**Issue by xrombik** [Swartz27/xray-16#963]
Если передать путь к ресурсам игры через ключ `-fsltx`, то игра не запускается, если путь к ресурсам содержит пробелы, например:
`/mnt/sda2/Programs/Steam/steamapps/common/Stalker Call of Pripyat/fsgame.ltx`

Выполняем команды для запуска:

```
$ cd xray-16/bin/x64/Release
$ export LD_LIBRARY_PATH=$(pwd)
$ ./xr_3da -fsltx "/mnt/sda2/Programs/Steam/steamapps/common/Stalker Call of Pripyat/fsgame.ltx" -nosplash
```
Тогда вывод в консоли имеет вид:

```
OpenXRay Release Master Gold build 8423, Feb 28 2022 (Linux 64-bit, shared)
Custom build from commit[35fbe9728941dda2654dd62249c3a22c8b758e3b] branch[fix-msst-2]
 
command line -fsltx /mnt/sda2/Programs/Steam/steamapps/common/Stalker Call of Pripyat/fsgame.ltx -nosplash 

* Detected CPU: Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz [GenuineIntel], F6/M7/S10, 'rdtsc'
* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, MONITOR/MWAIT, SSSE3, SSE4.1
* CPU cores/threads: 4/4
* CPU current freq: 3003 MHz

Initializing File System...
$fs_root$ = /mnt/sda2/Programs/Steam/steamapps/common
using fs-ltx /mnt/sda2/Programs/Steam/steamapps/common/Stalker
```

**Ответ здесь**
- имеем
`using fs-ltx /mnt/sda2/Programs/Steam/steamapps/common/Stalker`

- а должно быть
`using fs-ltx /mnt/sda2/Programs/Steam/steamapps/common/Stalker Call of Pripyat/fsgame.ltx`

Очевидно - путь обрывается по пробелу.

**Систма**
 - OS:  MX Linux 19
 - OpenXRay build version 8423

**Comment by jjdredd** [comment]
Исправлено в https://github.com/OpenXRay/xray-16/pull/846 
ожидает ревью

**Comment by eagleivg** [comment]
Строго говоря, не баг. Пути в линуксе должны экранировать пробельные (и некоторые другие символы), подробнее тут: https://debianinstall.ru/ekranirovanie-v-os-linux/

Более того, так как пробел разделитель между аргументами, такой PR может поломать ввод других аргументов после -fsltx

**Comment by jjdredd** [comment]
> Строго говоря, не баг. Пути в линуксе должны экранировать пробельные (и некоторые другие символы), подробнее тут: https://debianinstall.ru/ekranirovanie-v-os-linux/
> 
> Более того, так как пробел разделитель между аргументами, такой PR может поломать ввод других аргументов после -fsltx

Думаю что баг потому что у @xrombik путь в кавычках

**Comment by Xottab-DUTY** [comment]
Так путь в кавычках и должен работать правильно, беря все символы от начала кавычек до конца.

**Comment by jjdredd** [comment]
> Так путь в кавычках и должен работать правильно, беря все символы от начала кавычек до конца.

Я о том же. Мой ответ был  адресован @eagleivg

**Comment by Xottab-DUTY** [comment]
Дубликат #570
