### ISSUE TITLE
[COP] - Fatal Error while loading an autosaved game

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#974]
**Describe the bug**
while loading an autosave (created by an Emission start) I got a crash

**To Reproduce**
I can't reproduce, the game loads fine from the same save

**BugTrap error report**
here is the console last lines where the loading started:

<details>
  <summary>Click here to expand/collapse.</summary>
  <p>
(...)

[LUA]  ...ll of Pripyat\sim_squad_scripted:(476):set_location_types for squad [bandit_sim_squad_novice40908]
[LUA]  ... - Call of Pripyat\trade_manager:(79):TRADE [zat_b7_stalker_raider_37402]: current = generic_sell   sell = generic_sell
* [ Linux ]: free[135896 K], reserved[27488 K], committed[5988436 K]
* [ Render ]: textures[783874 K]
* [ x-ray  ]: process heap[1780 K]
* [ x-ray  ]: economy: strings[27810 K], smem[10256 K]
* Loading script: ui_load_dialog.script
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
[LUA]  ...- Call of Pripyat\ui_load_dialog:(6):18.000000
* [ Linux ]: free[132524 K], reserved[27488 K], committed[5991808 K]
* [ Render ]: textures[783874 K]
* [ x-ray  ]: process heap[1780 K]
* [ x-ray  ]: economy: strings[27809 K], smem[10256 K]
[LUA]  ... - Call of Pripyat\sound_manager:(31):UnRegister sm npc [camp609]:[22215]
[LUA]  ... - Call of Pripyat\sound_manager:(31):UnRegister sm npc [camp1488]:[21107]
[LUA]  ... - Call of Pripyat\sound_manager:(31):UnRegister sm npc [camp1488]:[21080]
 
FATAL ERROR
 
[error] Expression    : m_spawned
[error] Function      : lua_game_object
[error] File          : /home/biel/code/xray-16/src/xrGame/GameObject.cpp
[error] Line          : 1161
[error] Description   : (null)
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
/lib/x86_64-linux-gnu/xrGame.so(+0xd9cb9a) [0x7f58a7552b9a]
/lib/x86_64-linux-gnu/xrGame.so(+0xd9cc28) [0x7f58a7552c28]
/lib/x86_64-linux-gnu/xrGame.so(+0xcc5fe0) [0x7f58a747bfe0]
/lib/x86_64-linux-gnu/xrGame.so(+0xcc63d8) [0x7f58a747c3d8]
/lib/x86_64-linux-gnu/xrGame.so(+0xcc3c3c) [0x7f58a7479c3c]
/lib/x86_64-linux-gnu/xrGame.so(+0xcc3ccd) [0x7f58a7479ccd]
/lib/x86_64-linux-gnu/xrGame.so(+0x123e579) [0x7f58a79f4579]
/lib/x86_64-linux-gnu/xrGame.so(+0x124162d) [0x7f58a79f762d]
/lib/x86_64-linux-gnu/xrGame.so(+0xc8f7a2) [0x7f58a74457a2]
/lib/x86_64-linux-gnu/xrGame.so(+0x1531fdd) [0x7f58a7ce7fdd]
CObjectList::Update(bool)
/lib/x86_64-linux-gnu/xrGame.so(+0xebbe51) [0x7f58a7671e51]
/lib/x86_64-linux-gnu/xrGame.so(+0xda76ad) [0x7f58a755d6ad]
CEventAPI::Signal(CEvent*, unsigned long, unsigned long)
CEventAPI::OnFrame()
CApplication::OnFrame()
CRenderDevice::FrameMove()
CRenderDevice::ProcessFrame()
/lib/x86_64-linux-gnu/xrEngine.so(+0x43e2b) [0x7f58bf079e2b]
terminate called after throwing an instance of 'char*'
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /home/biel/code/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 848
[error] Description   : application is aborting
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
/lib/x86_64-linux-gnu/xrCore.so(+0x428ab) [0x7f58bee7e8ab]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f58be88e520]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0xf8) [0x7f58be8e2828]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f58be88e476]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd7) [0x7f58be8747b7]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa1a31) [0x7f58beb31a31]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xad4ec) [0x7f58beb3d4ec]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xac4b9) [0x7f58beb3c4b9]
/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x9a) [0x7f58beb3cc3a]
/lib/x86_64-linux-gnu/libgcc_s.so.1(+0x11484) [0x7f58bea87484]
/lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_RaiseException+0x311) [0x7f58bea87b21]
/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_throw+0x3c) [0x7f58beb3d7ec]
/lib/x86_64-linux-gnu/xrGame.so(+0xd9cbba) [0x7f58a7552bba]
/lib/x86_64-linux-gnu/xrGame.so(+0xd9cc28) [0x7f58a7552c28]
/lib/x86_64-linux-gnu/xrGame.so(+0xcc5fe0) [0x7f58a747bfe0]
/lib/x86_64-linux-gnu/xrGame.so(+0xcc63d8) [0x7f58a747c3d8]
/lib/x86_64-linux-gnu/xrGame.so(+0xcc3c3c) [0x7f58a7479c3c]
/lib/x86_64-linux-gnu/xrGame.so(+0xcc3ccd) [0x7f58a7479ccd]
Trampa de traçat/punt d’aturada (s'ha bolcat la memòria)
  </p>
</details>

**Desktop (please complete the following information):**
 - OS: [Ubuntu 21.10]
 - OpenXRay build version [ff7b9d2f152b4e06f3cd0dd943f30f8f60f43e1f] but compiled with `-DMASTER_GOLD OFF`

**Comment by Xottab-DUTY** [comment]
We had many stabilization commits during 2022-2023.
Closing as stale and not reproducible.
