### ISSUE TITLE
[CS] - ERROR: Invalid AI map at kamp point [mar_smart_terrain_6_8_kamp_1]

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#977]
**Describe the bug**
in Clear Sky some kind of AI map got not loaded while traversing the swamps( exiting the elevated house over the water ) and it crashed.

**To Reproduce**
random crash

**Screenshots**
none.

**BugTrap error report**
<details>
  <summary>Click here to expand/collapse.</summary>
  <p>
(...)

[LUA]  ...- Clear Sky\release_body_manager:(8):add to release_objects_table [14838]

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
! SV:ge_destroy: [14840] not found on server

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
! [LUA]  There is no spawn callback on object with id 1303 from object with id 15089!
stack traceback:

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_127722] = [false]
[LUA]  DISABLE INVULNERABILITY. npc[sim_default_csky_127722] = [false]
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_127722] = [false]
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_127722] = [false]
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(101):DEBUG: set_scheme: scheme='walker', section='walker@follow_mar_smart_terrain_5_12_guard_2_walk', gulag_name='mar_smart_terrain_5_12'
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(103):DEBUG: set_scheme: storage assigned

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
! [LUA][ERROR]  ERROR: Invalid AI map at kamp point [mar_smart_terrain_6_8_kamp_1]
stack traceback:
	...ld\S.T.A.L.K.E.R. - Clear Sky\gamedata\scripts\_g.script:974: in function 'abort'
	...T.A.L.K.E.R. - Clear Sky\gamedata\scripts\xr_kamp.script:309: in function 'getDestVertex'
	...T.A.L.K.E.R. - Clear Sky\gamedata\scripts\xr_kamp.script:58: in function <...T.A.L.K.E.R. - Clear Sky\gamedata\scripts\xr_kamp.script:54>
 
FATAL ERROR
 
[error] Expression    : 0
[error] Function      : ErrorLog
[error] File          : /home/biel/code/xray-16/src/xrScriptEngine/ScriptEngineScript.cpp
[error] Line          : 38
[error] Description   : ERROR: Invalid AI map at kamp point [mar_smart_terrain_6_8_kamp_1]
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
/lib/x86_64-linux-gnu/xrScriptEngine.so(+0x3c2ff) [0x7fae3eecc2ff]
/lib/x86_64-linux-gnu/xrScriptEngine.so(+0x3fb2a) [0x7fae3eecfb2a]
/lib/x86_64-linux-gnu/xrLuajit.so(+0x667c5) [0x7fae3ed997c5]
/lib/x86_64-linux-gnu/xrLuajit.so(lua_pcall+0xb9) [0x7fae3ed4ce69]
luabind::detail::pcall(lua_State*, int, int)
/lib/x86_64-linux-gnu/xrGame.so(+0x102c00f) [0x7fae27e8c00f]
/lib/x86_64-linux-gnu/xrGame.so(+0x1534f43) [0x7fae28394f43]
CSheduler::ProcessStep()
CSheduler::Update()
/lib/x86_64-linux-gnu/xrGame.so(+0xdaaac3) [0x7fae27c0aac3]
CRenderDevice::FrameMove()
CRenderDevice::ProcessFrame()
/lib/x86_64-linux-gnu/xrEngine.so(+0x43e2b) [0x7fae3f73ce2b]
CRenderDevice::Run()
Startup()
RunApplication()
xr_3da(+0x1885) [0x5578e0cb9885]
xr_3da(+0x15bf) [0x5578e0cb95bf]
Trampa de traçat/punt d’aturada (s'ha bolcat la memòria)
  </p>
</details>

**Desktop (please complete the following information):**
 - OS: [Ubuntu 21.10]
 - OpenXRay build version [c75c2d733f3ce5378b5115d858734c6d2ece67cf] with ```-DMASTER_GOLD=OFF```

**Comment by Xottab-DUTY** [comment]
Thank you!

This is a duplicate of #828, so I'll close it.
