### ISSUE TITLE
[CS] - Thread 16 "Task Worker" received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#978]
**Describe the bug**
random crash.

**To Reproduce**
random crash

**Expected behavior**
don't crash...

**Screenshots**
nope.

**BugTrap error report**
here is the last part of the gdb, returning every function

<details>
 <summary>Click here to expand/collapse.</summary>
<p>
(...)

[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_014568] = [false]
[LUA]  DISABLE INVULNERABILITY. npc[sim_default_csky_014568] = [false]
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_014568] = [false]
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_014568] = [false]
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_014590] = [false]
[LUA]  DISABLE INVULNERABILITY. npc[sim_default_csky_014590] = [false]
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_014590] = [false]
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_014590] = [false]
[LUA]  ...A.L.K.E.R. - Clear Sky\sim_board:(609):Squad esc_boars_lair_guard_3_10 exit smart esc_smart_terrain_4_11. Quan = 1
[LUA]  ...A.L.K.E.R. - Clear Sky\sim_board:(851):Reset nearest squads [esc_smart_terrain_4_11]
[LUA]  ...ear Sky\sim_faction_brain_mutant:(66):faction [monster] brain update
[LUA]  ...A.L.K.E.R. - Clear Sky\sim_board:(629):Player monster lose point esc_smart_terrain_4_11!
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_022341] = [false]
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(101):DEBUG: set_scheme: scheme='walker', section='walker1@mar_smart_terrain_5_8_guard_1_walk', gulag_name='mar_smart_terrain_5_8'
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(103):DEBUG: set_scheme: storage assigned
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_022327] = [false]
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(101):DEBUG: set_scheme: scheme='walker', section='walker1@mar_smart_terrain_5_8_guard_2_walk', gulag_name='mar_smart_terrain_5_8'
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(103):DEBUG: set_scheme: storage assigned
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_022341] = [false]
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(101):DEBUG: set_scheme: scheme='walker', section='walker@mar_smart_terrain_5_8_guard_1_walk', gulag_name='mar_smart_terrain_5_8'
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(103):DEBUG: set_scheme: storage assigned
[LUA]  RESET INVULNERABILITY. npc[sim_default_csky_022327] = [false]
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(101):DEBUG: set_scheme: scheme='walker', section='walker@mar_smart_terrain_5_8_guard_2_walk', gulag_name='mar_smart_terrain_5_8'
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(103):DEBUG: set_scheme: storage assigned
[LUA]  ...A.L.K.E.R. - Clear Sky\sim_board:(609):Squad esc_dogs_lair_guard_2_14 exit smart esc_smart_terrain_4_13. Quan = 1
[LUA]  ...A.L.K.E.R. - Clear Sky\sim_board:(851):Reset nearest squads [esc_smart_terrain_4_13]
[LUA]  ...ear Sky\sim_faction_brain_mutant:(66):faction [monster] brain update
[LUA]  ...A.L.K.E.R. - Clear Sky\sim_board:(629):Player monster lose point esc_smart_terrain_4_13!
[LUA]  ....A.L.K.E.R. - Clear Sky\xr_sound:(57):SOUND_CALLBACK from [24640]
[LUA]  ....A.L.K.E.R. - Clear Sky\xr_sound:(57):SOUND_CALLBACK from [24612]
[LUA]  RESET INVULNERABILITY. npc[sim_default_renegade_015263] = [false]
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(101):DEBUG: set_scheme: scheme='walker', section='walker1@mar_smart_terrain_8_8_guard_3_walk', gulag_name='mar_smart_terrain_8_8'
[LUA]  ...A.L.K.E.R. - Clear Sky\xr_walker:(103):DEBUG: set_scheme: storage assigned

Thread 16 "Task Worker" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe5fbf640 (LWP 173149)]
0x00007fffe100ffe6 in CPHSimpleCharacter::UpdateDynamicDamage(dContact*, unsigned short, dxBody*, bool) () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe10103b1 in CPHSimpleCharacter::InitContact(dContact*, bool&, unsigned short, unsigned short) () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe0fcffe8 in CollideIntoGroup(dxGeom*, dxGeom*, dxJointGroup*, CPHIsland*, int const&) () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe0fd0fca in NearCallback(CPHObject*, CPHObject*, dxGeom*, dxGeom*) () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe0fcb2e4 in CPHObject::CollideDynamics() () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe0fcb5d8 in CPHObject::Collide() () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe100f259 in CPHSimpleCharacter::Collide() () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe0fce06c in CPHWorld::Step() () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe0fcdcdc in CPHWorld::FrameStep(float) [clone .part.0] () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007fffe0fcde94 in CPHWorld::OnFrame() () from /lib/x86_64-linux-gnu/xrGame.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007ffff7f012ab in CRenderDevice::ProcessParallelSequence(Task&, void*) () from /lib/x86_64-linux-gnu/xrEngine.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007ffff7d2d1fd in TaskManager::ExecuteTask(Task&) () from /lib/x86_64-linux-gnu/xrCore.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007ffff7d2d7da in TaskManager::TaskWorkerStart() () from /lib/x86_64-linux-gnu/xrCore.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007ffff7d2f0c4 in Threading::ThreadEntry(void*) () from /lib/x86_64-linux-gnu/xrCore.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007ffff7769947 in start_thread (arg=<optimized out>) at pthread_create.c:435
435	pthread_create.c: El fitxer o directori no existeix.
(gdb) ret
warning: Function does not return normally to caller.
Make start_thread return now? (y or n) y
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:102
102	../sysdeps/unix/sysv/linux/x86_64/clone.S: El fitxer o directori no existeix.
(gdb) continue 
Continuing.
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /home/biel/code/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 848
[error] Description   : segmentation fault
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
/lib/x86_64-linux-gnu/xrCore.so(+0x427ab) [0x7ffff7d077ab]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7ffff7717520]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x44) [0x7ffff77f9a44]

Thread 16 "Task Worker" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7d0731f in xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*) () from /lib/x86_64-linux-gnu/xrCore.so
(gdb) ret
Make selected stack frame return now? (y or n) y
#0  0x00007ffff7d077ab in segmentation_fault_handler(int) () from /lib/x86_64-linux-gnu/xrCore.so
(gdb) quit
A debugging session is active.

	Inferior 1 [process 173129] will be killed.

Quit anyway? (y or n) y
</p>
</details>

**Desktop (please complete the following information):**
 - OS: [Ubuntu 21.10]
 - OpenXRay build version [c75c2d733f3ce5378b5115d858734c6d2ece67cf] with ```-DMASTER_GOLD=OFF```

**Additional context**
using the modified `gamedata/srcripts/xr_kamp.script` provided by @Xottab-DUTY in https://github.com/OpenXRay/xray-16/issues/828

**Comment by BielBdeLuna** [comment]
can I provide any more input to locate those errors using gdb?

**Comment by Xottab-DUTY** [comment]
I assume this is fixed with the new builds.

@BielBdeLuna, could you check?
