### ISSUE TITLE
[CS] - finding a lot of breakable boxes repeated inside one into the other

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#980]
**Describe the bug**
- there are a lot of boxes that contain an exact copy of another box inside.
- when you touch them they separate.
- they contain different content when broken.

**To Reproduce**
some of the boxes ( not all ) when touched separate in two boxes that reside exactly one into the other.

**Expected behavior**
there should be only a single box per position and not one into the other

**Screenshots**
none captured.

**BugTrap error report**
none.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 21.10]
 - OpenXRay build version [last version] with ```-DMASTER_GOLD=OFF```

**Additional context**
using the modified `gamedata/srcripts/xr_kamp.script` provided by @Xottab-DUTY in https://github.com/OpenXRay/xray-16/issues/828

**Comment by Xottab-DUTY** [comment]
Can you record a video or, at least, capture a screenshot? :)

**Comment by BielBdeLuna** [comment]
I think this is related too: https://github.com/OpenXRay/xray-16/issues/970#issuecomment-1078114195

**Comment by jjdredd** [comment]
I suppose two boxes, initially placed one on top of the other could have fallen through one into another due to collision detection
problem.

**Comment by BielBdeLuna** [comment]
a box that contains a box inside but that looks like just a single box:
![one box](https://i.ibb.co/sJDn7rx/Captura-de-pantalla-de-2022-04-01-17-30-04.png)
https://ibb.co/M5jrdLw

when pushed or stepped on by the player... ***PLOP!***
they push each other's off from one another.

![two boxes](https://i.ibb.co/6gt1Y8L/Captura-de-pantalla-de-2022-04-01-17-30-16.png)
https://ibb.co/WgzPn0j

Sometimes both are empty, sometimes both have something different and some times one contains something and the other nothing. In that case they didn't contain a thing:
![the two boxes are empty](https://i.ibb.co/3vzgB5k/Captura-de-pantalla-de-2022-04-01-17-30-29.png)
https://ibb.co/qC5TkLx

**Comment by Xottab-DUTY** [comment]
It more looks like a duplicate... Like, for some reason they've got spawned twice..

**Comment by Decane** [comment]
There is a duplicate section in all.spawn, [fixed by the SRP](https://github.com/Decane/SRP/blob/47ffc7376cebd2d6ede2c007805a12c644ef1058/SRP%20v1.1.4%20-%20Version%20History.txt#L338).

**Comment by Xottab-DUTY** [comment]
@Decane, so, this is vanilla bug and can be replicated on vanilla?

**Comment by Decane** [comment]
Yep.

Per SRP/gamedata/spawns/Alterations.txt:

> [1235] <deleted>
> 
> • Duplicate section: 'mar_physic_destroyable_object_0028'. Identical to 'mar_physic_destroyable_object_0027' of [1234] above it. This alteration resolves the issue with the duplicate supply box spawn at the back of the UAZ-469 at the Trailhead.

**Comment by Xottab-DUTY** [comment]
Thanks!

Then, I'm closing it, since this repository doesn't contain gamedata fixes
