### ISSUE TITLE
[CS] - sun shaft have a black square around the sun masking them out

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#987]
**Describe the bug**
the sun shafts have a square around the sun, like a mask that masks out the sun shafts from the render

**To Reproduce**
I have the following settings: 
- OpenGL
- the video at maximum capacity
- all the graphic settings on the UI are set to minimum( only the distance is at maximum ) 
- there aren't any console vars changed
- no mods
- looking at the sun displays the sun shafts with the square around the sun masking them out.

**Expected behavior**
no squares around the sun

**Screenshots**
- In this first image the sun shafts display the square around the sun clearly
![first image](https://i.ibb.co/SPgw4Jf/Captura-de-pantalla-de-2022-03-29-13-23-51.png)
https://ibb.co/s249dtW

- In this second picture, we se sun shafts that bug trough the wall, **but I'm not interested in that bug**, this is useful to see that in the direction of the sun the square masks out the sun shafts
![second image](https://i.ibb.co/sJVMJBf/Captura-de-pantalla-de-2022-03-29-13-33-08.png)
https://ibb.co/Kzr3z1P

**BugTrap error report**
none

**Desktop (please complete the following information):**
 - OS: [ Ubuntu 21.10]
 - OpenXRay build version [df92f231619c46ee06b1022e5ef843cf685966ad]

**Additional context**
no mods used

**Comment by BielBdeLuna** [comment]
It doesn't happen in **COP**

**Comment by Xottab-DUTY** [comment]
@vTurbine hello there, maybe you have some ideas? :)

**Comment by BielBdeLuna** [comment]
the sun didn't display this bug in at least e203f8458531be27be225e4e04f17b5241581a8e

**Comment by BielBdeLuna** [comment]
last commits solved this somewhat

**Comment by Xottab-DUTY** [comment]
This was probably fixed by a4b118ccf90156cbf6cf541940b8507676901d18. Can you check, just to confirm?
