### ISSUE TITLE
[CS] - Strange Lines in the PDA UI

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#988]
**Describe the bug**
PDA displays some strange vertical lines underneath the content.

**To Reproduce**
simply open the PDA, the factions war, and the map screens display such lines

**Screenshots and Expected behavior**
- Here is how the factions screen look in OpenXRay:
![factions screen in OpenXRay](https://i.ibb.co/YR63BKY/Captura-de-pantalla-de-2022-03-29-13-23-13.png)
https://ibb.co/TvZkMnp

it should look like this:
![how should look](https://media.moddb.com/images/mods/1/29/28603/PDA_FACTIONS.jpg)

- Here is how the map screen look in OpenXRay:
![map screen in OpenXRay](https://i.ibb.co/9gP7ntk/Captura-de-pantalla-de-2022-03-29-13-23-00.png)
https://ibb.co/XLHqX8r

it should look like this:
![how should look](https://media.moddb.com/images/mods/1/40/39151/00283346.jpg)

**BugTrap error report**
none.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 21.10]
 - OpenXRay build version [df92f231619c46ee06b1022e5ef843cf685966ad]

**Additional context**
no mods used

**Comment by BielBdeLuna** [comment]
in **COP** the PDA looks fine

**Comment by Xottab-DUTY** [comment]
Thank you!

This bug is mentioned in #382 as a checkmark and it is so small that I don't see any need in keeping it as a separate issue.
