### ISSUE TITLE
[COP] Can't turn off LUA debug logging

### ISSUE THREAD

**Issue by CasualDev242** [Swartz27/xray-16#991]
I know this issue is turned off in "Release Gold", but I attempted to disable it in the source code and compile it myself without any luck.
How do I turn this feature off to avoid console spam?

**Comment by CasualDev242** [comment]
I just realized I wasn't being clear. I want to turn this off in the "Release" build.

**Comment by Xottab-DUTY** [comment]
Just replace `MASTER_GOLD` with `NDEBUG` on this line:
https://github.com/OpenXRay/xray-16/blob/dev/src/xrScriptEngine/ScriptEngineScript.cpp#L18
