### ISSUE TITLE
Remove Crypto++

### ISSUE THREAD

**Issue by Xottab-DUTY** [Swartz27/xray-16#994]
It's enormous big for our small usage

**Comment by dino8890** [comment]
Which alternative library can we use here instead? I'm willing to take a shot at this,

**Comment by Xottab-DUTY** [comment]
Previously, libcrypto from OpenSSL was used.
Maybe, we can rollback to it or find some other projects on GitHub..

**Comment by dino8890** [comment]
I've been eyeing libsodium as well. I'll look into a few, compare them and then get back to you.

**Comment by Xottab-DUTY** [comment]
When considering libs, the availability is also important. (in a binary package form or a small source that we can compile ourselves and its fast to compile)
E.g. I looked at https://pkgs.org/ for libsodium – it's not widespread, while openssl is available on many many distributions (and there's libressl that replaces openssl on some distributions)
